== Chapter I.

[.chapter-synopsis]
* His education
* Early life
* Powerful visitation of divine love, and conversion
* His appearance in the ministry.

I was born in the city of Dublin, the 9th day of the ninth month, 1729.
My parents were Thomas and Martha Neale,
who removed shortly afterwards into the compass of Edenderry monthly meeting.
About the sixth year of my age, my mother died; soon after, my father removed to America,
and left me, with a brother and two sisters,
under the care and guardianship of my uncle and grandmother; who were very tender of us,
gave us such schooling as that neighbourhood afforded,
and took care of our morals and conduct.
In a few years my grandmother died, and left us under the care of our uncle;
who removed to Christians-town, in the county of Kildare.
My grandfather had purchased an estate, which he left to me,
if I should survive my father, which accordingly came to pass,
he dying when I was about seventeen years of age.

In my early years, though deprived of my parents, the Lord my God was near,
and took me up, and at times moved upon my spirit and melted my heart,
before I well knew what it was that affected me.
When very young and capable of reading the Scriptures,
and other writings tending to instruct me in that which was good and profitable,
I felt my spirit tendered;
and I enjoyed a sweetness of mind that made me very sedate and grave,
and often the tears would run down my cheeks.
In these seasons I felt myself very comfortable;
and had a belief that I was seen by the all-wise Creator, who knew all things;
but such impressions soon wore off,
and the levity of my natural disposition got into dominion, when amongst my play-fellows.

Thus I went on for some time; when I was attacked by the small-pox:
it reduced me very low, and few thought I should recover.
In this disorder, I thought I was not fit to die, and therefore entered into covenant,
that if the Lord would bring me through,
I would be more careful of my words and actions than ever I had been before.
I still remember some of the prospects I had when lying on that sick bed:
but it pleased infinite Goodness to raise me up.
I was then about my twelfth year; and after this, though I often remembered my covenant,
yet my natural propensity to youthful follies and amusements prevailed much,
and stifled the good resolutions I had formed; so that,
not keeping to the sense that was awakened in my mind,
I too much forgot the visitations with which I had been
favoured from the gracious Hand of merciful help:
and not being enough restrained, I took liberties in hunting, coursing, and shooting,
whereby I was introduced into unprofitable company,
which often lays a foundation for repentance.
As I grew in years my passion for these amusements increased, so that I was hurried on,
as with a torrent, into irregularities that lead to the chambers of death.

Thus I continued till my father`'s death, which as already mentioned,
was about my seventeenth year; near which time I had a dawn of sense given me,
that my life was very unprofitably spent.
I knew but little of business, and was desirous of being placed in some line of life,
by which I might be enabled, in addition to my income, to live reputably amongst men,
and follow some occupation, so as to be kept out of idleness: in consequence whereof,
when about eighteen years of age, I was placed with a merchant in Dublin,
a very sensible humane man, to serve him till I should be twenty-one.
In this situation I was as much, or more exposed than before; for having money of my own,
I contracted acquaintance with many young people in that city,
very injurious to my growth in that which was good.
Being remarkably active and strong, and excelling most in a variety of bodily exercises,
it made me vain; and emulation prompted me to endanger my health,
by abusing the strength with which Providence had endued me for better purposes.

In this time of servitude I got intimate with several young men in the college,
I believe some of the most moral that were there;
and I took liberties inconsistent with the principles in which I was educated.
We sometimes frequented the play-house, and after these amusements,
when on my return home,
O! the anxiety and remorse that covered my mind and overwhelmed my spirit!

I was then willing to covenant to be more careful in future,
and avoid what now seemed so distressing: but when those seasons of diversion approached,
I felt my inclination to arise with redoubled strength, and my passion for gratifying it,
like an irresistible torrent, insurmountable: so I went,
like a man bereft of understanding.
When all was over, I was ready to accuse myself as one of the weakest of mortals,
and to deplore my unsteadiness and want of resolution.

Thus I continued for a considerable part of the three years I spent in Dublin, sinning,
and deploring my weakness and the commission of those things
that afterwards stung like a serpent and bit like an adder.
At particular times when sitting in meetings, I was sensible of the virtue of Truth,
and was very much brought down and humbled in my mind: but my associates would cry out,
"`This is a religious fit,--come let us take a coach and go to the Park, Black-rock,
or some such place, and drive it away.`"
Thus the convictions of the good Spirit were counteracted by
those who were not subject to its government,
but were agents to him, who rules in the children of disobedience,
and keeps in bondage and darkness.

I remember in an afternoon meeting a valuable Friend was concerned to
speak in a prophetic line,--that the Lord would visit the youth,
and pour forth of his spirit upon them, and raise up Samuels for himself.
I thought she looked steadily towards me, and her words made a deep impression on me.
But endeavours were used that same evening to eradicate these impressions,
which through weakness and frailty were but too successful;
so that I feared I should never be able to stand my ground,
and was almost persuaded to give over striving.
But my gracious and good Lord still followed me with his loving-kindness,
and at times created a hope that I might overcome the enemies of my own house:
and in time, blessed be his holy Name,
I felt strength to resist their wiles and insinuations;--but alas!
I had many combats.

I well remember a remarkable dream,
which had a very great effect upon me:--I thought the
enemy of all good came and attacked me violently,
that we wrestled a considerable time, and I was in great conflict;
he brought me to my knees, but still could not throw me down,
and after much struggling he vanished.
I awoke, and my shirt was as if dipped in water, from the agony of this conflict.
Though I was young, it made a great impression on me,
and since that time I have seen my dream fulfilled.
But for the interposition of the Lord`'s mercies,
I should have been long since overthrown,
and become a cast-away:--great are His mercies,--He still continues to be long-suffering,
and abundant in goodness and truth to poor rebellious man;
striving by His good Spirit to draw him from sin and iniquity,
and calling him as out of Egyptian darkness and bondage,
to come into the glorious liberty of being his son;--as is expressed in sacred writ,
"`Out of Egypt have I called my son.`"
Though this alludes to our blessed Lord`'s coming out of Egypt,
when his life was sought by Herod, it also may be applicable to mankind in general,
in sin and in their natural state,
which may be justly styled Egyptian darkness and bondage;--to whom the call is,
by the Spirit of our Lord Jesus, to come out of this sinful state, witness the new birth,
and be baptized by His pure spiritual baptism, that of the Holy Ghost and fire;
which purges the floor of the heart, brings into newness of life,
and makes it a temple where acceptable prayer is offered up,
by the power and excellent working of the pure Truth,
which prepares every acceptable sacrifice,
in our devotion and religious exercises during our pilgrimage through this world.

Thus I went on, between hope and fear, the remainder of my apprenticeship;
my frailties often precipitating me to the verge of ruin.

During this time I had a visitation from the Most High, by a fever and ague,
which brought me very low; my former covenant appeared fresh in my remembrance,
and I was now afraid to ask, because before I did not perform.
I continued for some time in a low condition,
until infinite Goodness restored me once more to health, to try my fidelity; but,
to my shame and confusion, I ran into greater evils than ever:
thus ungrateful and hardhearted, I could fully subscribe to that declaration,
"`The heart of man is deceitful above all things,
and desperately wicked:`"--I seemed running the full length of my chain.

My conviction and remorse were at times strong;
but company and the levity of my temper quenched these convictions,
and I went on towards destruction,
in rebellion and disobedience against the divine Monitor, which, in boundless mercy,
still followed me.

I continued in this state until I was my own master; when,
intending to pay a visit in Munster, to form acquaintances and follow some business,
I prepared for my journey, equipped like a young man of the world, had a livery servant,
and set forward in good spirits on my expedition.
As I passed along, I called at Paddock, where Mary Peisley lived,
to inquire after her health and that of the family: my uncle Samuel Neale accompanied me.
We made some little stay there,
and I found myself delighted with their instructive conversation:
it sunk into my mind beyond what was common; and when we left the place,
I remarked how pleasing such company and conversation were,
compared with what was generally to be met with.

I pursued my journey to Limerick,
where I stayed some days with my relation John Taverner:
here I fell into very dissipated company, old acquaintances that I had in Dublin.
From thence I proceeded to Cork,
and on the road felt my mind impressed with solid reflections,
which I have since thought preparatory to what soon followed;
for I was conscious that my weakness and frailties were great,
my time running swiftly away,
and I was irresolute with respect to standing
against temptation and the allurements of sin,
and sin-pleasing pleasures.
In this disposition I reached Cork,
and there mingled with my old acquaintances and got new ones.

I remember being at a play one evening, up late that night,
and lying pretty long next morning, which was first-day,
an acquaintance asked me to go to meeting,
and at the same time informed me there were strangers to be there,
telling me who they were: I said I would,
for at my worst state I generally attended meetings.
So to meeting I went, and it was a memorable one to me:
for in it my state was so opened to that highly favoured instrument in the Lord`'s hand,
Catherine Payton (who with my beloved friend Mary Peisley were
visiting the churches,) that all I had done seemed to have
been unfolded to her in a wonderful manner.
I was as one smitten to the ground, dissolved in tears, and without spirit.
This was a visitation from the Most High, beyond all others that I had as yet witnessed:
I was so wrought upon by the power and Spirit of the holy Jesus, that like Saul,
I was ready to cry out; "`Lord, what wouldest thou have me to do?`"
I was almost to ashamed to be seen, being so bedewed with tears,
and slunk away from the meeting, to get into a private place.
I joined company with a religious young man,
and forsook my gay companions and associates, who beheld me with astonishment.
The change was very rapid, and my doubts and fears respecting myself were very great,
so that I could not trust myself in my former company,
lest my innumerable frailties should prove too powerful for all my good resolutions.
So I abode still and quiet, and kept near these messengers of glad tidings to me.
I went with them to Bandon and Kinsale;
and the same powerful dispensation of divine virtue followed me, breaking in upon me,
and tendering my spirit in a wonderful manner,
in public meetings as well as in private opportunities;
which drew the attention and observation of many.
When I returned to Cork, I kept as private as I well could,
and resolved to quit all my worldly pursuits,
and follow the gentle leadings of that heavenly Light,
which showed me the vanity of worldly glory,
and that the pleasures of sin are but as for a moment.

Our beloved friends intended for the province meeting at Limerick,
and took Kilcommon meeting in their way, whither they went: I also went;
and a considerable degree of concern grew in my mind, both by day and by night.
Their company was precious to me, their conduct and conversation strengthening;
and the inward manifestations of heavenly goodness vouchsafed,
were my crown and rejoicing.
My eyes were measurably opened to behold my insignificancy, rebellion and backsliding:
I saw the perverseness of my nature, and that in me, as man, there dwelt no good thing.
I thought I saw that if I missed the present opportunity of coming as out of Babylon,
I was lost forever: I was come to the length of my chain, my measure was full,
and if I did not embrace the present offer, ruin and destruction would be my portion.
These sights of my condition stimulated me to exert myself in watchfulness and care,
to pursue with ardency the sense that opened in my own mind,
and to feel after the spring and virtue that I witnessed there,
which far exceeded every gratification that I knew before in this life.
My hunger and thirst after righteousness were great:
I delighted much in reading and retirement;
worldly things had no charms for me at this season, when the new creation began to dawn:
although, at times, I felt that the mount of Esau was on fire,
and the consuming thereof hard to bear, yet it was necessary,
in order that I might witness a new heaven and a new earth,
wherein alone righteousness can dwell.

I went with these Friends to many meetings, and still heavenly good attended me,
which encouraged me to persevere and resolve to be stedfast.
I was very comfortable in this good company,
and in that of valuable Friends where I came:
but the time drew near when I must be separated from them;
and though it was a very heavy trial upon me to leave those Friends, who as instruments,
were exceedingly helpful and beneficial to me in my weak state,
yet I concluded to return; and accordingly took leave of my beloved fellow travellers,
and turned my face towards home, which was then in Dublin.

This was about the middle of the summer of 1751, and in the twenty-second year of my age.
I journeyed homeward in great heaviness; fear seized on me,
lest I should not be able to stand my ground amongst my intimates and acquaintances,
professors and profane; being well known in that great and populous city,
and having had many proofs of my own unsteadiness and forgetfulness,
when heretofore favoured with the tendering convictions of Truth on my mind.

At times I had thoughts of leaving the kingdom, and residing in England,
near some valuable experienced Friends,
where I might be safer than amongst my acquaintances in my own country,
who so often allured and drew me from the paths of purity,
into the pursuit of lying vanities.
Thus I reasoned with flesh and blood: but I was instructed to see,
that He who visited me, was able to preserve me,
if I would but be subject and obedient to His wholesome instruction;
and that where I had dishonoured Him by my inconsistencies, there,
by my fidelity to the law He writes in the heart,
I might honour and confess Him before men.
These intimations quieted my mind, and I resolved to meet ridicule, reviling,
and even persecution itself, for the sake of Him, whom I was resolved to follow,
as I felt strength.

In this state of mind I returned to Dublin, and kept pretty quiet,
attended meetings and mingled with a few select Friends.
In this my weak state I frequently went through bye-ways and lanes,
to avoid my old acquaintances, feeling the cross heavy,
as many young people educated in our Society do,
when I met them and spoke the plain language: this is much to be regretted,
for it was the language spoken by our blessed Lord and his disciples,
by the patriarchs and prophets,
and our principles strictly enjoin us to speak it to all men;
but alas! many are unfaithful, which makes them unfruitful in works of righteousness.

This brings to my remembrance a passage in my experience,
which may be of some use when I shall be no more.
When I was with my old master T. S. as an apprentice,
he had occasion to pay rent to the Bishop of Clogher for one of his correspondents:
I was sent with the money, and addressed the Bishop,
not as though I was one called a Quaker.
He took but little notice of me; I thought he treated me rather with contempt:
it stung me to think I had played the coward, and was ashamed to address him as a Quaker;
I therefore entered into an engagement that if ever I went again,
I would address him in the plain language.
The season came that I was to go, and I was warned in my mind to remember my engagement,
I went in some degree of fear;
he was just stepping into his coach to go into the country:
when I addressed him as a Quaker, he very politely received me,
and treated me as if I had been his equal.
When I had done my business,
I returned with a pleasure far transcending any thing I had felt before,
for such an act of obedience: I thought I could leap as an hart, I felt such inward joy,
satisfaction, and consolation.

So that I would have the beloved youth mind their Guide,
and not dishonour that of God in them; for as we are faithful in a little,
we shall be made rulers over more; and we shall have more of the praise even of men,
by keeping to our religious principles, and be in higher esteem by those in authority,
as our forefathers were.

I stayed in Dublin amongst my friends, attending meetings constantly,
and sometimes met a select number at Samuel Judd`'s,
where I was often refreshed and comforted; the Lord was pleased to be with me,
contriting my spirit and humbling me under His mighty hand.
The mount of Esau was still on fire,
which at times was very affecting and hard to be borne;
and were it not for the Divine hand that sustained,
I could not have abode the fierceness of the furnace:
but it is a gradual work and must be accomplished;
the kingdom of sin and Satan must be destroyed,
before the kingdom of the holy Jesus becomes established in the hearts of men.
The house of Saul grew weaker and weaker, and the house of David stronger and stronger,
until it became established: so, in a religious sense, conversion is a gradual work;
the sinful nature declines through the efficacy
of the baptism of the Holy Ghost and fire,
which purges the floor of the heart, and makes it a fit temple,
for the Spirit of the Son of God to dwell in.
This causes a strong combat, a severe conflict,
in which the poor creature suffers deep probation and tribulation;
but it is the way to virtue and glory,
and is the heavenly preparer of paths to walk in acceptably to God: who,
gradually carrying on His own work in the midst of suffering,
visits by His life-giving presence to animate, cheer,
and enable the drooping soul to hold on its way.
By this invisible and glorious work the day of redemption draws nigh,
and the poor pilgrim goes from strength to strength,
and from one degree of experience to another, rejoicing in the Lord Jehovah,
the God of the spirits of all flesh, until the work be completed;
then the poor traveller can say,--"`It is not of him that willeth,
nor of him that runneth, but of God that showeth mercy:`" it is He that works,
both to will and to do of His good pleasure, by His holy Spirit;
as the temple is clean and is kept in that state, which is only to be done,
as we take heed to the power and Spirit of our Lord Jesus Christ,
the Captain of our salvation, watching and praying that we enter not into temptation:
then, and not till then, will the temple of our heart be clean.

After I had spent some time in Dublin, my dear friend Garratt Van Hassen,
having an inclination to go to Mountmellick, to see Friends there-away in their families,
I felt an inclination to accompany him, of which he seemed glad.
When there, he was joined by James Gough,
and they invited me to sit with them in the families they visited.
I was sensible of divine good in most of the families,
and had some openings similar to those spoken of
by them in their religious communications,
which was a strength to my mind.
I remember in one family there was nothing said, no openings in ministry,
and in that family my mind was much shut up, I felt no openings of light or comfort;
which made me believe I had something of a sense such as these worthy Friends had,
and this was some encouragement to me in my infant state.

I kept on with them in the service until they had concluded;
in general I was favoured in spirit,
being often tendered and contrited before the Lord Almighty, and, I hope,
strengthened in living experience.
On our return we called at Christians-town, and stayed a few nights there,
where I met with a remarkable occurrence:
I had been used in former times to walk out with my gun and dog;
it was a retired way of amusing myself, in which I thought there was no harm:
and reasoning after this manner, though I was very thoughtful about leading a new life,
yet I now went out as formerly.
I remember I shot a brace of woodcocks, and on my return home it rained,
and I went to shelter myself by a stack of corn;
when it struck my mind as an impropriety, thus to waste my time in this way of amusement,
so I returned rather heavy-hearted.
Dear Garratt and I lodged together; and next morning he asked me if I was awake,
I told him I was; '`I have something to say to thee,`' said he; I bid him say on.
'`It has been,`' said he,`' as if an angel had spoken to me, to bid thee put away thy gun;
I believe it is proper that thou shouldest put away that amusement.`'
To this purport he spoke; and that same night I dreamed that it was said to me,
intelligibly in my sleep, that if I would be a son of righteousness,
I must put away my gun, and such amusements: it made a deep impression on my mind,
and I concluded to give up everything of the kind, and take up my daily cross,
and follow the leadings of the Lamb, who takes away the sins of the world.

We returned to Dublin soon after; and I stayed there, attending meetings,
and keeping as much as I well could in solitude; until dear Joseph Tomey,
feeling a concern to visit a few meetings in the country,
I was made willing to accompany him.
In this journey, I was under a deep exercise of mind,
and great strugglings between flesh and spirit,
which none fully knew but the good Spirit that searcheth all things,
and comprehendeth all states and conditions.

We went to Ballitore, and into the county of Carlow.
Joseph was clothed with great authority in his ministry;
and was made a nursing father to me in this little journey by day and by night,
for we lay much awake, in great tenderness and contrition of spirit;
so that I may indeed say, I watered my pillow with my tears.
I felt something like a fire in my breast that glowed with uncommon heat:
it gradually increased, and was shut up there, till we came to Mountrath meeting; where,
as I sat, I felt a great concern to say a few words,
which deeply affected my whole frame, and made me tremble exceedingly.
After much reasoning I yielded obedience, which gave me great ease;
my peace flowed abundantly, and I seemed quite in another state.
My companion had an excellent opportunity to preach the gospel to the people,
and the meeting ended in a very solemn frame.
This was the 16th of the twelfth month, 1751.
My beloved friend Mary Peisley was present at
this awful dedication of the temple of my heart,
and I believe had great sympathy with me,
being deeply experienced in the way and working of Truth,
and an eminent instrument in the Lord`'s hand for
promoting truth and righteousness amongst men.
After this I kept very still and quiet, was much inward with the Spirit in my own heart,
and delighted in reading and meditation.

We went from Mountrath to Edenderry, and were there at a marriage:
there were several people at it besides Friends.
I went in much fear to this meeting, but I was helped to bear my testimony,
and my companion had an excellent open season amongst them.
We went from Edenderry to Dublin, where I had much reasoning with flesh and blood,
such as, what would the people think or say of such an one as I,
who had been a gay young man,
a libertine and a persecutor of the holy Jesus in his spiritual appearance,
to appear now as a preacher of righteousness.
When the meeting day came, my fears increased, and in this state I went to meeting;
it was on a first-day, there was a very large gathering,
amongst whom were divers of my associates and old companions.
I was concerned to bear my testimony, which I did in great fear and trembling:
the subject was Paul`'s conversion;--"`Saul, Saul, why persecutest thou me?`"
It was spoken in great brokenness,--I did not say much,
but it had an extraordinary reach over the meeting; many present wept aloud,
and for a considerable space of time.
After meeting I endeavoured to get away unperceived,
though one man (not of our Society) caught me in his arms and embraced me.
Thus was I sustained and strengthened in my setting out in the work of the ministry;
and had an evidence that the people were much reached, and powerfully affected that day.
Afterwards I waded through divers exercises,
and felt deep baptisms attend me for my further purification,
and on account of the people, whose states I must feel, if I ministered aright.
