== Chapter IV.

[.chapter-synopsis]
* His Marriage with Mary Peisley
* Her sudden illness and death.

Ninth month 29th.--Felt my mind inwardly composed and settled,
and strong in desire both for myself and my brethren,
and so continued to attend our meetings at home.

Tenth month 26th.--Was at our meeting at Rathangan appointed for the American Friends,
Abraham Farrington and Samuel Emlen, which proved a solid and instructive season;
they came home with me that evening,
part of which we spent in retirement with several of my relations,
I hope to good purpose.

29th.--Set out for Dublin in order to attend the National meeting;
on my journey overtook several friends going thither,
amongst whom was my much esteemed friend Mary Peisley,
whom I had not seen since her arrival from her American journey;
and it was truly satisfactory after so long an absence
to behold a servant who had followed her Master,
and was upheld by His mighty power to pass
through a variety of provings and dispensations,
which dipped into sympathy with, and quickened a rectified ministry to,
the state and condition of the churches in that land; these she thoroughly visited,
and thereby purchased her own wages, the flowing in of Divine peace and heavenly virtue,
which give a holy hope of quietness and assurance forever.

30th.--The meeting of elders and ministers proved a solid refreshful season;
the two Americans and James Clothier, the English Friend, were there:
cousin Mary Peisley gave a small sketch of her experience in her late trying journey,
in America, both as to her preparation for it and experience in it;
which proved highly agreeable and seasonable, as well as instructive.
She produced a full certificate of the approbation and
unity of the faithful in that land,
and how acceptable and serviceable, her labours had been amongst them.

The meeting proved a solid refreshing season, and ended, in my judgment,
to our humbling enjoyment of Divine approbation; and my request was sealed to me,
though made in secret,
that the Lord of my life would unite our spirits and cause us
to witness a participation of the flowing of Shiloh`'s brook,
which makes richly glad, and sustains and freshens the heritage of our God.

The 31st, being first-day, the several meetings in that city, Dublin, were large.
A+++.+++ Farrington was led to speak of the gradual advancement of
the work and operation of religion in the minds of men,
in the example of Elisha,
who was engaged in his outward occupation when the prophet Elijah was sent to him,
who cast his mantle over him.
This done he feels the moving inspiration,
sacrifices his yoke of oxen that he followed so closely:
an emblem that we must give up all and follow the Lord.

He spoke afterwards of their going together to Gilgal, Bethel, Jericho, and Jordan,
which were different places figuring out the dispensations,
which rightly anointed servants sometimes have to pass through,
before they have filled up in themselves the steps necessary for service and action;
but as they keep close to the prophet through them all,
they will be rightly qualified and helped,
and will find a double portion of the Holy Spirit to rest upon them,
by which they will be made beautiful as their ancestors,
and serviceable as the ancients in their day and time.
In the evening, we had a solid season of retirement at S. Judd`'s,
wherein some instructive hints were dropped.

Eleventh month 1st.--We had a favourable opportunity
together in the opening of our meeting,
and deep counsel was unsealed: in the meeting for business we witnessed the same power,
virtue, and favour,
and several minds were stirred up to bear their testimony to the Truth.
Our business ended the evening of the 2nd, in much harmony, concord, and discipleship,
to an increase, I trust, of humility and thankfulness.
On the 3rd, was our parting meeting, and meeting for ministers and elders;
in both of which we were much owned,
and the prevalency and power of Truth were
sensibly felt by the living and travailing souls.

Having long had a prospect of an union with my beloved
friend and sister in the faith of the Lord Jesus,
Mary Peisley; and it being the ancient order of our church,
I was willing to follow the footsteps of the flock,
and to manifest that my dependence was not on my
own judgment in this weighty undertaking;
so I mentioned it to a select number of our elders and my relations,
and had much peace in this step, deeply desiring the approbation and unity of my friends.
They not feeling any objection, strengthened my belief,
that the God of my life was pleased therewith, and that it was in his counsel,
who had often united our spirits, and baptised us into the Spirit of his dear Son,
our Captain and Law-giver, who helps all those that trust in Him,
with the increase of his Spirit and power;
and who will assuredly give the victory to all who
persevere in well-doing and endure to the end:
that this may be our joint experience and crown of rejoicing,
is the ardent breathing and supplication of my spirit at this time.

On the 27th of the eleventh month, was held our general meeting at Mountmellick;
which was attended with a holy degree of our heavenly Father`'s power,
and the discipline was carried on with renewed zeal,
for the good of the church and the honour of our God.
On the 28th, being first-day, we had a large meeting;
wherein many hearts were bowed under an awful sense of that
goodness which extended fresh ability to ascribe greatness,
honour, and mercy to the God of the spirits of all flesh;
who by His instrumental as well as immediate power is
calling all to come under His holy government;
for He willeth not the death of any soul, but woos and visits in various ways,
to reclaim and purge and make unto Himself a holy nation, a royal priesthood,
to show forth the working of His holy power and matchless love.

Twelfth month 5th.--I was drawn in spirit to be at Edenderry meeting,
which proved a good one, I believe, to several.
My heart was much tendered and melted, under a sense of my Lord`'s goodness;
the gospel stream went freely forth; the wicked were warned,
the weak and feeble encouraged, and the negligent stirred up.
The meeting ended under a covering of glorious Goodness; under the influence whereof,
praise was sounded forth, in solemn supplication, to the Father of mercies,
in the power and ability of his dear Son our Lord, who is forever worthy, saith my soul.
Amen.

9th.--In meeting at Rathangan; the shortness of time was pointed out to my view,
in a lively manner, in the kingly prophet`'s words: "`Lord! make me to know mine end,
and the measure of my days, that I may know how frail I am.`"
This knowledge conveys fear,
and incites to a care to loosen the affections from worldly enjoyments,
which are fleeting and fluctuating: "`for it is certain,`" as saith the Apostle,
that "`we brought nothing into this world, and we can carry nothing out of it,
and having food and raiment let us be therewith content.`"
We have need to prepare for our change, watch our stoppings,
and guard against our natural senses, lest, being outward and carnally bent,
they defile and tincture the spirit; which, in the end,
will have an habitation according to its purity or impurity,
according to its holiness or unholiness.

13th.--Engaged pretty closely about outward affairs,
yet inwardly concerned to breathe to my great Lord to preserve me in them,
so as not to bring deadness or forgetfulness over my spirit,
but to live in remembrance of His holy mercies, and that I am an accountable steward.

14th.--Retreated from outward hurry and commotion,
and inwardly engaged to feed upon holy help,
which was measurably extended for present sustenance and support;
had a sweet composure of spirit this evening, with ability to petition for light, wisdom,
strength and courage, to live to the honour of my Master,
and to spend that life He has graciously redeemed, to His own praise.

24th.--This day several friends came to visit us; spent the evening agreeably,
and had a profitable season of retirement, in which our minds were bowed;
thankful in soul ought we to be for such favours and benefits,
unapproachable in our time and ability:
but when our great Lord is pleased to unseal refreshment,
it drops as the rain and distills as the dew,
and causes withering hope to spring as the morning.

1757, first month 1st.--Went on the visit to Friends`' families,
to Arch-Nevins`'s,--met with home and close work, spent several hours in this visit,
and afterwards went to Thomas Harvey`'s, where we had a satisfactory encouraging time,
and at the conclusion,
the spirit of power and wisdom filled my heart so as to cause humiliation,
and supplication to arise, and to be formed into vocal language,
as ability was extended and directed.
Our minds were much refreshed,
and we parted in a renewed sense of the rewarding hand of our God,
who gives liberally and sustaineth His heritage and people,
whose dependence is placed on Him the God of mercy and power;
in a humble sense hereof we took leave of one another, and I returned home,
being drawn in my spirit to be at our meeting on the morrow.

2nd.--Was at our meeting at Rathangan, in which I felt the holy Hand of help;
my spirit was much broken and affected,
and a testimony filled my heart for my Lord and
Master +++[+++on this wise]--"`Thus saith the Lord,
are not my ways equal, are not your ways unequal, O I house of Israel?
I will judge you every man according to your ways:`"--the paternal care,
the helping regard, the sustaining support and nourishment that were afforded us,
were ranged before the view of the mind;--and also the
appeal the Lord our God made by His prophet,
"`Hear, O heavens: and give ear, O earth; I have nourished and brought up children,
and they have rebelled against me:`"--beseeched and entreated all to "`seek Him,
that maketh the seven stars and Orion, that maketh the day dark with night,
that calleth for the waters of the sea,
and poureth them out upon the face of the earth:`" He will be our Judge,
and proportional to our virtue and vice, so will our rewards be.
The rebellious were warned, the backslider entreated, and the faithful encouraged:
the meeting ended in a solid frame.
Returned home thankful and composed in spirit.

3rd.--Some company coming to my house interrupted that
retirement and inspection I expected;
but in the evening enjoyed it in degree to comfort, and the renewal of arising strength.

4th.--Being third-day of the week,
retired with my family to seek refreshment and inward help:
in the evening was low and poor in mind,
yet attentive to look towards the habitation of holy succour.

5th.--Set forward to visit my beloved Mary Paisley,
and the next day was at their weekday meeting at Mountrath,
which was a melting season to my spirit throughout the whole meeting, and ended well.

12th.--I concluded to return home in obedience to an impulse
or draft of spirit which I felt secretly to draw me,
and not to urge my dear friend to appear at the
next monthly meeting +++[+++to present our marriage].

14th and 15th.--Was thoughtful and down in spirit by intervals,
yet feeling a gradual support underneath,
and conscious of having followed the dictates of what I thought my safest guide,
I cleaved close thereto; which led to retirement and reading,
and an inward seeking and attention for the arising of conquering Goodness,
that crowns the soul with peace and resignation.

16th.--Being drafted in spirit to be at Edenderry meeting where was to be a marriage,
I concluded to go thither, though in a cross to my natural disposition,
and so to be willing to do what my Lord had for me to do,
who had given me a body in which to do His will; and what matter where we are,
or what work or service we are put to,
if we are purchasing peace and laying up for ourselves
a good foundation against the time to come.
And truly my Master vouchsafed His presence and favour,
and fully recompensed my spirit for following His direction;
and I believe the cause did not suffer by my attendance at the said meeting;
several of the townspeople came in, and seemed weighty and solid.
Several things opened to my view;
the humble manner of Jacob`'s going in search of his wife,--his humility,--his trial,
and his vision,--his covenant, and his success for his obedience to his parents.
The meeting I hope ended well; humble supplication was offered for us to our Lord,
I returned home in the evening, enjoying encouraging and sustaining peace.

18th.--Pensive and thoughtful, which begat droopingness of mind;
yet favoured at intervals with confirming peace,
that the rays of light would again appear,
and dissipate every unsettling and anxious reflection,
21st and 22nd.--Hurried and engaged pretty closely in the outward;
yet careful to retire from it to feel after the virtue of
reconciliation to every cross occurrence and harassing care:
taken up in part in writing, 31st,--Joined again the friends on the family visit;
and it proved a time of great favour and merciful condescension;
in the course of this visit the openings of holy Truth were experienced,
and the newness of life accompanied, by which our minds were replenished and sustained,
and we enabled to attribute the glory and honour
of all to the inexhaustible Treasury of wisdom,
life, and love.
We separated in much love and unity, and I returned to my family,
where I found my affairs pretty much to my satisfaction.

Second month 6th.--First-day, I was at Rathangan,
where I witnessed a close and inward travail, with 3,
degree of holy and heavenly nourishment,
which quickened and begot cries and requests to the Author of
true sufficiency for a continuance of the same.
This day was laid before our preparative meeting my intention
of marriage with my nearly united friend Mary Peisley,
in the doing whereof, sweet peace attended my mind,
and my spirit was much tendered and affected,
under a sense of the goodness of the God of my life,
through the opening of that glorious grace which comes by His blessed Son Christ Jesus.

12th.--Went to Mountrath, to see my beloved friend Mary Peisley,
accompanied by some of my relations,
having an expectation of presenting our marriage
before the monthly meeting the day following:
found her well in health, through Divine favour,
but inwardly bowed down under a sense of the
important change which she was likely to make.
It was a time of humiliation and prostration of soul to us both:
and my desires were strong and fervent,
that the Lord of our life might please to be with us, and unite us renewedly,
in his holy unchangeable covenant of light and peace.

13th.--We had a good refreshing meeting together,
and the virtue of Truth was felt to arise:
may our souls be awfully regardful of the condescension of our merciful Lord and Master;
and may fresh obedience to all His requirings still lead to an enlargement in His favour,
mercy and love.
We appeared before the meeting, I believe, in awe and reverence of mind;
and a solemn enjoyment of divine peace and love attended our spirits,
which centred them in calmness and serenity.
20th, The first-day of the week,
in which it fell to my lot to be engaged as well as other Friends in the public service;
several things opened as warnings to the forgetful and wicked,
and the consequence of dwelling in that state,
in which Divine displeasure would certainly overtake them,
though long striving to draw them from it: in the similitude of a just power,
who forbears executing justice, until there is no room left to hope for a return,
and then she appears to have iron hands though leaden heels!
Mercy is long-suffering, and abundant in goodness and truth;
yet when slighted and rejected, she assumes her own authority in judgment,
and turns from her mild and beautiful aspect, into an inexorable, and rigid austerity;
and she rewards adequate to the degrees of impenitency and hardness of heart.
May all turn in the day of mercy,
and humble themselves under the mighty hand of the Lord my God!

After attending the quarterly meeting in Carlow, I went towards Ballinakill,
with my beloved Mary Peisley, and some other Friends;
who were going there on a religious visit to Friends`' families; and, finding my way open,
I joined them in that service.
22nd; Feeling a disposition still to accompany Friends in this visit,
I went with them to finish what remained in the meeting of Mountrath, and the 24th,
returned home in much peace.

Third month 8th and 9th.--Retired, and inwardly drawn to a cautious inquiry,
in which frame I had to petition for holy Help,
to live to the honour of my Lord and Master,
to go in and out before His people in His own pure wisdom;
that in all things He may be glorified and have the praise.

10th.--Our monthly meeting was held at Rathangan; the meeting for worship was low:
towards the latter end a few things seemed to arise and dwell on my mind to offer,
which I did in humility of mind--concerning Christ, the true Physician;
in a natural sense when a family is sick or disordered, if a physician be sent for,
he administers suitably to the several wants and
constitutions of his patients,--some want nourishment,
and for others abstinence is best; and so he prescribes as they stand in need.
And so does the Physician of value to His own dear children:
He offers nourishment according to His good pleasure to those who are weak and feeble,
and who stand in need of it,
when at the same time He restrains it from others of His family,
in order to offer them something more applicable to their wants and disorders,
as abstinence, withholding food from them; that they may come to feel their appetites,
and seek His face and help.
There seemed to me to be another state in the family,
who were willing to partake of heavenly food with the children;
but if it were not handed to them, they were easy and negligent about it,
and ran to their outward affairs,
and thereby neglected that inquiry which might be helpful to them,
why Divine nourishment was withheld from them.

12th.--Went towards Mountmellick,
accompanied by two Friends to meet my dear friend M. Peisley,
who was engaged in a family visit in that quarter.
13th; We presented our marriage the second time before the monthly meeting.
In the evening, I accompanied my beloved friend Mary Peisley, with others appointed,
to two families: in one of which, she directed her testimony to the visitors,
in such a manner, as much affected our spirits: she spoke of the pillars of a house,
in an outward building; the fewer they were,
the greater weight or burden they had to bear: so, in the Lord`'s house,
those who were faithful and upright, must expect to feel weight,
and the fewer they were in number the greater weight must they expect to feel;
she mentioned the necessity of standing firm, and had encouragement for such.

17th.--Being the day of our marriage, many Friends and others attended; it was a solid,
comfortable, and instructive meeting.
James Gough was concerned to mention these words from the prophet Isaiah:
"`Thy Maker is thy husband:`" on which he enlarged in a beautiful and remarkable manner.
In the evening, we had a time of retirement, in which something singular occurred:
I was engaged to speak of the Apostle`'s address to the Thessalonians,
where he called them, "`The church in God:`" it opened to my view,
that we were to be that church by union and communion with Him;
keeping under the sanctification of His power and virtue;
that relations in affinity or consanguinity signified little,
to that of an immortal kindred,
which is between those who are "`The church in God:`" that trials and
afflictions were the lot and portion of the right-minded,
designed to bring us to a nearer union with our God, and make us His church,
prepared for Him to dwell with and in.
I entreated all to prize such seasons as these, and to remember, that,
if they were properly improved,
it would be laying up for ourselves a good foundation against the time to come.
My dear wife had to speak of the sabbath of rest;
that when the Almighty had done His six days`' work in the creation.
He appointed a sabbath, and sanctified it; and that, in the time of the law,
the people were forbidden to do any manner of work on the sabbath day; and said,
there were some present who would have a sabbath,
in which they should have no work to do: I remember thus much;
she spoke but a few sentences with much clearness, and the evidence went with them.
Little did I then suspect that we had each to minister to our own states and conditions.

18th.--We were visited by several of our friends,
and had religious and instructive communion in
the openings and enlargement of divine love.
The 19th, we spent solidly in a sweet and beautiful fellowship,
and my dearest was cheerful and well going to bed,
but about one o`'clock was attacked with her old complaint, the cholic,
in an unusually violent manner, and was in great agony;
several things were administered which formerly relieved her,
but nothing now was sufficient to repel it: thus she continued most of the night,
dozing at intervals.

After the first shock of her pain was over,
which did not in its violence and force last above an hour,
she lay pretty quiet and still, in an awful frame;
and would sometimes raise her voice in a melodious and heavenly sound,
through the efficacy and virtue of that glorious grace,
which had so often animated and enabled her to
sound fourth praises to the King of saints:
and though she did not always express herself in words,
yet there was a language in the sound which richly and fully
manifested that she triumphed over her bodily pain,
as well as over death, hell, and the grave.
For it appeared that she longed to be dissolved,
by her entreating her Lord to give her a release, if consistent with His holy will;
which request He was pleased to answer,
and about half an hour before her departure dismissed her pain; she then said,
"`I praise thy name, O my God! for this favour.`"
Soon after she breathed shorter and shorter, and quietly departed without sigh or groan,
like a person falling into a sweet sleep, after fourteen hours`' illness,
about three o`'clock in the afternoon of the 20th of third month, 1757.

I was constantly with her during her illness,
and have to bear my testimony to her noble and Christian conduct.
My loss is great: I have lost a sweet companion, a true friend, a steady counsellor,
a virtuous example, a valuable instrumental pilot,
and a deep and sincere sympathizer in afflictions and trials.
But my Lord, who knew my motives and views in seeking such a friend, will, I trust,
look down in pity and mercy on my destitute condition, and administer heavenly,
sustaining help, to anchor my mind in such a storm as this;
that I may be able so to live to his honour,
as to gain an admittance into that kingdom which is prepared for the righteous,
when these few moments shall be over, when this mortal veil shall be rent,
and the immortal spirit summoned to appear before its Lord.
O! that my soul may be vigilant and watchful in the great work,
that I may have to join the spirit of my beloved, and her kindred saints,
in singing hosannas and hallelujahs to the Lord God and the Lamb,
who lives and reigns forevermore!

Third month 21st, 22nd, 23rd.--In a drooping, low, exercised condition,
under a sense of my deep trial:
but the God of my life opened a view that my dear wife was happy;
and I am left in a state of daily toil and trial, to wrestle with flesh and blood,
before the reward of "`well done,`" be pronounced.
Methought, I beheld, in the vision of that which gives the victory,
comfort and beauty in the prospect of running well,
and in being vigilant and valiant in the work of God:
and I felt a strong and fervent motion of spirit that it might be my lot so to run,
as to obtain,--and so to suffer,
as to reign with my Lord and Redeemer in the mansions of light and immortality.

24th.--This day my dearly beloved wife was interred.
It was my desire to have a meeting in the meeting-house;
and it pleased the great Lord and Master of her life and labours,
to favour with his Divine presence,
and to exalt his testimony above all opposing spirits,
and enemies of the cross of our Lord Jesus; for which my spirit was bowed,
and praises lived in my heart to His great and ever to be honoured name.
Afterwards, at the grave, we had a renewed evidence of His divine notice and power:
dominion and authority were ascribed to Him, who opens His treasury,
and dispenses His blessings and favours;--ever worthy is He of
thanksgiving and praise by sanctified spirits on earth,
and glorified spirits in heaven.
Amen.

[.small-break]
'''

The following letter from Richard Shackleton to Catherine Payton, gives
gives an account of these affecting events.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Fourth Month 3rd, 1757.

[.salutation]
My dear friend,

It is laid on me by a friend of ours,
to send this messenger of sorrowful tidings to thee.
A scene has opened little expected by us, which I know will nearly affect thee,
as it has us.
I am at a loss how to begin to relate it,
surely many are the instances of the fallacy of our
prospects and uncertainty of our enjoyments here;
repeated are the shocks we get to loosen us from earth, that,
finding no firm footing for our wearied spirits thereon,
we may with more earnest longings seek a city that hath foundations,
a house eternal in the heavens.
May this be the happy effect of our afflictions and disappointments here;
and then we shall experience such dispensations of Providence to be salutary potions,
though for a time they be bitter cups.

But to begin:--thou wert acquainted with the intentions of our
dear friends Samuel Neale and Mary Peisley to marriage.
They accordingly took each other in marriage on the 17th of third month, at Mountrath.
The meeting, (although crowded with various sorts of people,
and many of the neighbouring gentry) was a solemn good opportunity,
and to speak my own opinion as one present, to the honour of Truth.
Samuel Neale married as though he married not.
Appearing towards the beginning of the meeting in a lively testimony,
and at the conclusion, in heart-tendering supplication.

I remarked that after the meeting Mary seemed quite pleasant and easy in her spirit,
but loath to part with some of us who were taking leave of her, in order to return home.

The evening preceding the day of their marriage,
Samuel requested an opportunity in her mother`'s family,
wherein he had to speak of the benefit of laying hold
of every such opportunity of renewing our strength,
and that it was the way to lay up treasure against the day of trouble and disappointment,
which was certainly to be met with in this uncertain stage.
And in the evening of the marriage day, in a like opportunity,
Mary spoke sweetly how the Almighty performed the great work of the creation in six days,
which having finished.
He appointed a sabbath, and day of rest, and sanctified the same.
And that there were present, who would in a little time enjoy the sabbath, etc.
Thus remarkably they spoke severally to their own particular states, little thinking,
I believe, that their testimonies would be so speedily fulfilled on themselves.

They spent the two days following their marriage in sweet fellowship at her mother`'s,
and on the seventh-day evening, Mary was remarkably cheerful, and supped heartily.
But between twelve and one o`'clock that night,
she was seized most violently with her old pain in the stomach,
which for some time affected her so strongly, that she cried out with pain;
but after a while it abated, and she expressed her thankfulness to her great Benefactor.
She then desired one of her sisters to hand her a cup of water,
and said she would see afterwards what a fine sleep she would go into.
After she had drank the water, she seemed much pleased, and fell into a kind of slumber;
and gradually drew her breath weaker and weaker, till she drew it no more,
expiring without any seeming pain, sigh, or groan, on first-day the 20th ult.,
about three o`'clock in the afternoon, and went, no doubt,
to enjoy that sabbath which she so sweetly spoke of a few days before.

Her body was carried the fifth-day following to the meeting-house at Mountrath,
which was very full on the occasion.
Several Friends bore testimony in a lively manner, to the circumspect life, holy zeal,
undaunted courage and faithful services of this eminent instrument in
the Lord`'s hand to publish His Truth among the nations,
and at the conclusion, my dear friend Samuel Neale, to my great surprise and gladness,
kneeled down beside the coffin that contained the
remains of his most beloved earthly treasure,
and prayed to God the Fattier, in the demonstration of the Spirit,
and baptizing power of His Son.
My soul was prostrated in the deepest reverence, and joined in strong cries unto Him,
in whom is all our sufficiency, that He would be near us in this trying day,
and make up our recent loss;
and I believe many more present were greatly affected at the same time.
From thence we proceeded to the graveyard,
where Samuel bore a living testimony to the people,
and our friend James Gough was concerned in supplication;
after which the body was decently interred.

Such was the latter and last end of our dear friend,
concerning whose many excellencies I need not enlarge to thee,
who not only hast been more a witness, but a better judge thereof than I;
but shall only add respecting her, that since her return from America,
she was diligent in attending meetings, both particular and general,
when ability of body was permitted;
but seemed pretty much shut up as to the exercise of her gift in the ministry,
though sometimes she appeared in that manner, always lively, but mostly short.

After the publication of their intentions of marriage,
she found a concern to join other Friends in family visits,
which were performed very fully to the families of her own monthly meeting.
In this service she was remarkably favoured with clear openings, and deep counsel,
which it is to be hoped will be as bread blessed by her Master,
cast at His command upon the waters,
(the unstable minds of the people,) that may be yet found,
though perhaps not till after many days.
After the accomplishment of this service,
she returned home cheerful and easy in her mind: and in a few days after,
she was joined in marriage to her beloved husband, our dear friend.
As the tie of natural affection between them was drawn
still more closely by a pure and spiritual union,
this sudden separation is doubtless a severe trial to the survivor;
but that good Hand which brought him out of Egyptian darkness, into His marvellous light,
and which leads His approved servants through various straits and dispensations,
I hope will still be underneath, and support,
and more and more refine for His further use, till He fits for that heavenly kingdom,
where, O! that we may all meet, never more to part,
when these few afflicting days are over.

[.signed-section-closing]
I am with the salutation of dear love, thy real friend,

[.signed-section-signature]
Richard Shackleton.

--

26th.--Took leave of my friends and relations, in a solemn weighty frame of spirit,
in the enlargement and overflowing of unlimited love,
having fervent supplication quickened in my heart, that we might all be kept clean,
in the protecting care of our Heavenly Father.

28th.--Returned to my own house, in lowness and much thoughtfulness of mind,
accompanied by some of my relations, who came as sympathizers.

31st.--Attended the meeting at Rathangan,
in which my spirit was refreshed and strengthened.
My dear friend Abraham Shackleton and his daughter-in-law Elizabeth were with us,
and we spent the evening in religious converse and retirement, I hope to mutual comfort.
I passed through exercise, before I concluded to go on with them to the Province meeting,
to be held at Moate; but duty prevailed above every other consideration;
and it fastened on my mind that while the church militant was upon earth,
she was in a state of warfare,
and if I were of the church militant I must not be exempt from my portion,
but be willing to be anything that my Lord would have me.
So I willingly gave up, though it was to be as a spectacle to the people.

At night my mind was much exercised and tossed
in reflecting on the singularity of my trial,
and I was earnest in mind to have some confirmation
respecting the cause of the quickness of the separation;
which was graciously vouchsafed, insomuch that I was made thankful and easy:
having an evidence from the Almighty, through the revelation of his Spirit,
respecting the removal of his servant, that her days were filled up.
It seemed to me as though she appeared before me,
and uttered these words as intelligibly as I ever heard her express any: "`__As for me,
I am safe; thou art still in the body;
watch well thy ways:__`"--an unction seemed to accompany
the words which rested on my mind for some days.
I count it a mercy indeed to be thus noticed,
and humbly crave help to live diligently in uprightness.
