== Chapter V.

[.chapter-synopsis]
* Visit to Munster, and some parts of Leinster
* Visit to Wales, and some meetings in England.

1757, fourth month 4th and 5th.--Taken up pretty much in reading, writing,
and retirement, wherein I witnessed calmness of mind and a quiet habitation,
though mixed with low thoughts and a dulness hanging over the spirit.

10th.--Attended our first-day meeting at Rathangan:
my spirit was tendered and humbled under various considerations,
and my soul was exercised and bowed in deep travail;
in which state of mind it was clearly seen (though I was not
engaged to express it,) that the creation of God in the soul
is by the efficacy and work of His blessed Son Christ Jesus,
who said by his servant,--"`Behold I create all things new;`"
and that he also was the beginning of the creation of God.
In the old creation light was first created, and the Almighty "`saw that it was good.`"
So in the new creation light first arises in the soul, and shows to man his condition,
and the necessity of a change, if ever he becomes new; and not only shows,
but helps out of the old state of death, and that by proper gradations.
This is the true Light that enlightens every man that comes into the world;
and as man is faithful to its discoveries he advances in the work of God,
sees more light, which discovers to him his own deformity, and abases self;
for the more we have and enjoy of the light of Christ the more humble we are,
the more jealous of our own corrupt nature,
and the more zealous to live to the honour of God.
And as we keep in a yielding obedience unto the manifestation of this glorious Light,
we become new creatures in Christ Jesus, who declared he would create all things new.
As this new state is witnessed,
man may properly be said to have dominion over his own corrupt propensities
and the evils that are in the world,--having victory only by Christ;
and not only over them,
but he will keep the blessings of the old creation in their proper places,
having dominion over them,
subduing the earthly mind which centres and settles too much on earthly objects.
But alas! how many are there now, making a high and exalted profession,
who are not only led captive by their own lusts and evil habits,
but are slaves and in captivity to those things which were
given as gifts and blessings for a noble and dignified use,
and to be subordinate to man;
instead whereof man is become in the general in bondage to them,
and they have dominion over him; which reversion will ever continue,
until the light is given way unto in the soul, which will bring to the washing-pool,
to the cleansing cistern, and work all things new;
thus there is a getting forward in the celestial race,
and in the end a partaking of that joy and rejoicing which the
sanctified and redeemed in Christ Jesus do now,
ever did, and hereafter ever will partake of and enjoy!

11th.--In retirement and thoughtfulness of mind, to witness profit therefrom.
Being calm and serene in spirit I took a view of my beloved wife`'s papers,
many of which are much to be prized and valued,
containing deep and a truly devoted example in Christian virtues and graces.

12th.--Being retired in my family,
felt a degree of sustaining succour to my soul and refreshment to my spirit;
a great part of the remainder of the day taken up in reading and meditation.
I count it a wonderful mercy and favour that I
am so supported under my trying affliction;
but surely such unmerited love and regard will I trust bring my spirit into humility,
and quicken diligence and excite care to come up in my duty and
station in the church militant whilst embodied in a mortal mansion.

13th.--In a degree of sustaining quietness,
taken up in reading over some of my beloved wife`'s papers,
in which I felt an inward sweetness and strength to arise,
with attentive admiration at the goodness of that holy
regulating Hand which had so wonderfully wrought upon her,
fitted and fashioned her a vessel of honour,
keeping her in that humility which goes before honour,
and preserving her in a depending state, which her writings fully set forth.

14th.--At our week-day meeting at Rathangan,
in which I had to travail for the arising of life and the true Seed into dominion;
my spirit was broken and humbled,
and in prostration of soul I was led forth to petition
our Sovereign Lord for help and strength to His people,
and that He would be graciously pleased to help His church in
this nation to come forward in the holy warfare,
leaning upon the breast of her Beloved, to stem the temptations of the enemy,
and open the spiritual eye to see his workings.

15th.--Was taken up in reading, conversation, etc.;
several of my friends coming to see me:
we had some solid reflections on the ways and workings of our Lord,
and His dealings towards His people the workmanship of his hand.

17th.--Being first-day, my spirit was much humbled in our own meeting,
and my Lord was pleased to appear for my succour and support.
These words were strongly impressed on my spirit,--"`Watch well thy steps and ways.`"
I took it as a seasonable caution for my own state and rested under its admonition,
until I further felt the animating virtue of Truth to arise in my
heart and to kindle an emotion to utter it amongst the people.
The shortness of time was also opened to my view,
and the dangers we were surrounded with,
whilst in these houses of clay--the great need all had to watch well their ways,
which they would be helped to do, as they looked to Him who has all power in His hand.
Those advanced in years had as much need as any, who were just ready to step out of time,
being by the course of nature upon the very verge of eternity,
and the Judge waiting as before the door, to receive their entrance.
And those who were ministers and ciders had much need to watch well their ways,
that they might example the flock,
and have to say,--"`Follow me as we follow Christ,`"
the holy and heavenly Pattern of true rectitude;
who had not (by His own testimony) whereon to lay His head,
so much was He a stranger and pilgrim upon earth.
Those who were parents and heads of families had much need to watch well their ways,
that they might be good examples and waymarks to the youth: and the youth themselves,
that they might be preserved from a fellowship with the people or spirit of the world,
remembering that evil communication corrupts good manners.
I entreated all to watch, for he that betrays was near at hand, now as well as formerly,
to bring into bondage and under his government;
great need therefore have we to watch well our ways, and look to our Head,
our Husband and Guide,
that we may be enabled to join in a holy confederacy to
pull down the kingdom of sin and Satan.
I went afterwards to a Friend`'s house where I had a
sweet time in supplication as we sat at the table.

19th.--Sat in retirement in my little family,
so as to witness supporting succour to my spirit,
being very low and weak in spirit before the said opportunity.
It is cause of great humility of soul to reflect and
meditate on the unmerited mercies of my Lord to me;
may a quickened and awful regard thereto ever accompany and possess my mind.

23rd.--Much taken up with outward affairs,
yet had my eye towards the gate where my Beloved is sometimes pleased
to appear to the refreshing and helping the +++[+++poor pilgrim,]
as well as to the nourishment and growth of that part which
claims an interest in immortality and never-ending felicity.

24th.--First-day of the week, was at Rathangan, and bowed under exercise,
being dipped into several states then present,
to whom I was enabled to impart my concern,
and I think in the demonstration of my Master`'s love and mercy;
sundry things were spoken to; the necessity of seeking the one thing needful,
as Mary did, which will employ most of our time and attention; ourselves, our families,
and the church of Christ demanding, as we are prepared members,
the whole of our attention, besides the necessary employment in our domestic concerns,
and the duty we owe our neighbours of being as lights and way-marks to them.
And as all are thus rightly occupied,
there will be little of that weakness lodging in us,
of prying into and speaking of other people`'s affairs;
detraction and calumny will be entirely excluded, we sitting low;
this will cause our faith to flourish,
and our hearts will be enlarged in the other necessary essential Christian virtues;
patience, knowledge, temperance, godliness, brotherly kindness, and charity.
These will tend to give us the victory over the beast, and over his mark,
and over the number of his name; and will exalt us among the redeemed,
who stand with the golden harps upon the sea of glass,
singing the song of Moses and the Lamb.

25th.--Taken up profitably in reading, retirement, and writing:
also had to mind my outward affairs,
with a serene satisfaction resulting from an
inward attention to the more material duties,
which when devotedly pursued,
make domestic cares not only necessary but pleasant and sweet.

27th.--Retired with my family, in which state I witnessed helping, healing nourishment,
and had opened to me a prospect humbling and trying, which was not the first time;
may the Lord of my life so work in me, and upon me,
as to fit me for His house here on earth, the church militant,
and thereby I may enjoy a mansion in the church triumphant, is my passive, resigned,
and earnest request at this time.

28th.--Our week-day meeting at Rathangan,
in which I felt a mixture of suffering with a
tender and sweet stream of Divine consolation.
Yesterday`'s prospect still lived in the time of my best enjoyment,
and I found my heart closely united to the true seed there assembled,
and had to speak of the Jewish church formerly, when in a travelling exercise,
and baptised under the cloudy and in the sea, under Moses their leader;
the glorious signal they had for journeying as well as standing still, the cloud by day,
and pillar of fire by night; which was an unspeakable mercy to their souls,
for it was proportioned according to their necessities and wants.
In the time of night, the light was more conspicuous when they had most need for it;
and when the light of the outward creation was visible, and in it they could journey,
the cloud went before them as a guide:
and when by Divine appointment the camp was to stand still, this guide,
this pilot and glory rested on the tabernacle.
So that the Lord led Israel in the light of His glory,
with the mercy and righteousness that came from Him.
And now the true Israel is to witness an advancement,
as they witness the cloud and pillar to go before them,
which is made manifest to the true seed;
therefore I entreated all to keep to their own experience,
and not to journey until the cloud be taken up off their own tabernacle,
which will be made manifest to them as they witness redemption.

Fifth month 6th.--Went to Dublin,
and met several of my dear wife`'s nearly united friends, Catherine Payton, L. Bradley, etc.,
etc., with whom I had a renewed baptism of tears,
in remembrance of my beloved one removed: some friends were opened to speak comfortably,
and were dipped into sympathy on that awful subject.

7th.--Our meeting of ministers was held,
in which Catherine Payton had much counsel to communicate
communicate in the depth of wisdom to many states.

8th.--Being first-day, we had large meetings;
wherein the gospel was freely preached in the power and demonstration of it.

10th.--We had a meeting of worship at Meath street meeting-house,
and in the afternoon continued our yearly meeting by adjournments.
Several weighty matters came before our meeting,
which time was taken to consider properly and particularly respecting women`'s meetings.

12th.--Our meeting concluded:
my heart was filled with humble thanksgiving to the Lord my God,
for all His mercies extended to us,
and for the distribution of His holy counsel in this our solemn assembly.
The meeting of ministers and elders, and the parting meeting were held this day.
May a due and weighty sense of heavenly care and regard extended to us,
create a quickened attention to the will of our Lord and Master.

15th.--Being first-day, sat with Friends in their little meeting at Timahoe,
on my way homeward,
and though it was a time of labour and exercise to my spirit in the
communication of some few things which lived in my heart,
yet the power arose, which gives liberty;
and it proved towards the latter end a season of refreshment to me,
and I hope to some others in the meeting.
Went afterwards to see a friend and relation indisposed,
who seemed to me to be in a sweet frame of spirit,
and preparing fast for the kingdom of rest.

16th.--Returned home to my family, and found all things well through holy Goodness.

27th. Went to Edenderry, and was at the meeting of ministers,
in which sweet counsel was imparted,
and encouragement given to some different states and conditions;
who have had intelligence opened, yet are afraid to receive it as true,
lest the adversary should mix some of his subtle injections,
gilding them with beautiful and fair colours,
and thereby to deceive as in the appearance of an angel of light;
from which may my Lord ever preserve my soul.

Sixth month 9th.--Was at our week-day meeting at Rathangan,
which was poor and barren to me,
and it continued a meeting of much exercise to my spirit.
In the evening looked into several papers that belonged to my dear deceased wife,
which tended to revive my mind, which was before much depressed.

10th. Poor and barren in the early part of the day and reflecting
much on a prospect I have had some time ago opened to me,
which this day appears clothed with many dangers and difficulties,
hills and mountains of height and weight appearing as bars and obstructions.

12th.--Was at Baltiboys meeting, which was small and a hard one:
several broken sentences opened to my mind which I dropped to them,
and found them hard to utter: came home in a degree of peace,
though I felt much suffering there.

13th.--In poverty of spirit, and very weak as to inward strength and comfort.

14th.-For a small portion of time this day felt a degree of tenderness to affect my
spirit with a clear sight and sense of many weaknesses and wants attending,
which bowed my spirit;
and desires were raised for my perseverance in stability and the way of righteousness.

16th.--Our week-day meeting at Rathangan, which mostly proved a laborious season,
yet my soul nourishingly partook of a sweet stream of, life,
which quickened deep supplication to the God of true consolation,
for the upholding and building up in a true humble and living dependence on him,
and on the arm of his power.

23rd.--Set out in order to pay a visit to Friends in some parts of this province,
and in the province of Munster, which I had, for some time past,
believed to be a duty incumbent on me.

24th.--Was at a meeting in Dublin; went from thence to Wicklow to the province meeting,
and so proceeded to the county of Wexford: visited all the meetings in that county,
and in the province of Munster.
The virtue of Truth rose into dominion many times,
and my soul was deeply bowed under the renewed experience of the mercy of my Lord,
richly extended to me in this journey.

[.embedded-content-document.letter]
--

[.letter-heading]
To Richard and Elizabeth Shackleton

[.signed-section-context-open]
Wicklow, Sixth month 25th, 1757.

[.salutation]
My Dear Friends,

I am not altogether insensible of the
weight of the trial you have of late passed through,
in the loss of your released happy little one,
and the commotion of your family by the distemper +++[+++small-pox;]
but let us count them all as visitations of a God of mercy,
who knows what to administer to his creatures, how and when.
My sympathy with you is great, my desires for you are strong,
and my salutation is to you in the bowels of unfeigned love,
with this request,--stand in the patience,
look with diligent attention to the Source and Spring of
unbounded mercy that suffers us to pass through such siftings,
in order to fasten and establish our faith in His all-powerful arm;
which must be entirely leaned upon, if we expect to be held up in trials of every kind,
which are and must be our portion whilst in a state of pilgrimage.

Ah! my dear friends in the covenant of life and peace,
in poor tried me you have an example of the instability
of all temporary favours and blessings,
in the fruition of the ultimate of my desires and expectations,
so far as could be enjoyed in such an union as ours;
but all was cancelled by the removal of my memorable friend!
Well, my heart is brought to that state of resignation,
as to praise that Hand with which I was smitten; and to crave yet more stripes,
if it be for my refinement and enlargement in boundless love,
and the attraction of my soul to never ending enjoyment.
I cannot write much: I conceive I am in the way of my duty in saying thus much;
and may add, I am following, I trust, my Leader,
in visiting some meetings in this and the province of Munster,
where I expect trials and besetments; but my hope is in my Lord.

I shall be glad of a few lines from you if you think me worthy of them,
either at Waterford, Cork, or Limerick,
and salute you unfeignedly in a degree of my Father`'s love, and am your real friend,

[.signed-section-signature]
Samuel Neale.

--

After an absence of six weeks and three days, I returned home, 8th of eighth month,
fully satisfied that I had been in the way of my duty: with this resolution,
to be willing always to trust in my Master,
and follow his directions as clearly made manifest,
because my soul has indeed felt the reward that attends obedience.

Eighth month 9th.--I am sensible of a degree of calmness and sweetness,
which renders solitude delightsome.

10th.--Engaged in retrospecting my late journey,
and attending upon that which replenishes and sweetens every bitter cup.

12th and 13th.--Was easy and free in spirit, pondering on the works of my Master;
I had to look into the beautiful reward that attends obedience,
and what a glorious experience it is to die in a state of acceptance with our God.

16th.--In a degree of profitable quietude, engaged in reading, writing, etc.,
sometimes I witnessed a painful clothing of spirit, which I trust is for my refining.
Wrote to J. G. in the evening respecting a poor prodigal who wants to be restored.
"`If thou seest the oppression of the poor,
and violent perverting of judgment and justice in a province, marvel not at the matter:
for He that is higher than the highest regardeth,
and there be higher than they.`"--(Ecc. 5:8)

20th.--Set forward towards Dublin, and took Baltiboys in my way;
and on the 21st was at the meetings in that city,
in which my Master endued me with strength to deliver
what was laid on me with a degree of authority,
in which I had to speak to various states in a sharp testimony,
the wicked and openly profane, the worldly-minded,
and also those who had gifts and were as servants once
occupied and engaged in the great Master`'s service,
but now were fallen asleep and at ease.
I had peace administered for my labour amongst.the people,
and had also the censures of some of them for my pains.

Ninth month 1st.--Our week-day meeting at Rathangan;
in which I felt a close combat to keep to that inwardness and
emptiness of my own thoughts that leads to fulness and fruition.

9th and 10th.--Measurably composed and quiet in the enjoyment of sweet peace;
taken up during a portion of each day in reading and reflection,
I trust forwarding the progress of the immortal spirit in the spiritual race.

17th.--We held our province meeting;
which was measurably owned with our heavenly Father`'s favourable notice:
the meeting for business was comfortable,
several members speaking from a ripened concern and a right regulated zeal.
In the evening had a comfortable opportunity at J. C.`'s,
with his family and divers others; the virtue of Truth was generally felt to flow,
which humbled our hearts, and from thence salutary counsel flowed.

Tenth month 9th.--Being first-day, I was at our meeting at Rathangan,
in which I had exercise and service:
the state of the blind man who sat by the way and begged,
was opened to the view of my understanding;--that our Lord healed by
spitting on the ground and making clay of the spittle,
and anointing his eyes bid him go and wash in the pool of Siloam,
which he accordingly did and received sight.
He had faith in our Lord`'s direction, and therefore was restored:
and now in this gospel day, which is a spiritual dispensation,
we must expect salvation by obedience to the dictates of the Spirit of Truth,
and the inward anointing of the eye of the soul,
which when opened sees things in a true light.
For now we are not to look for an outward Christ and outward miracles,
but "`Christ within the hope of glory.`"
The apostle was fully of this mind, when he says,
"`Henceforth know we no man after the flesh;
for though we have known Christ after the flesh,
yet now henceforth know we him so no more:`" for now he appears the second
time in the hearts of the regenerated souls without sin unto salvation.
Several things respecting the restoration of the blind man I had to speak to,
making comparisons in a spiritual manner;
and the meeting ended in a sweet frame I believe in the sense of the generality.

11th.--Third-day, felt the humbling virtue of my Lord`'s love to be about my tent,
as a new visitation of his mercy,
which wrought a thorough willingness in me to be anything or nothing,
to pass through exercise and conflicts, to visit his seed,
and to approve myself in his service;
unto whom in the riches of his mercy he graciously called,
when in a destitute and forlorn state: former prospects were opened,
and my mind fitted to go and meet some of my brethren, and visit Moate monthly meeting.

18th.--Returned home from visiting Moate monthly meeting.
The company of my dear friend and companion Abraham Shackleton was profitable,
and his service acceptable; his conduct preaches louder than his words,
and his savoury expressions on many occasions,
show him to be an inward and spiritual worshipper,
carrying the seal that manifests him to be one of Wisdom`'s children,
whose nourishment is from the Fountain of immortality.

19th.--Our monthly meeting held at Edenderry;
where I felt liberty of speech as well as matter to communicate,
which I believe was suitable to the states of the people:
the savour of life was precious, and the meeting ended in a good degree of sweetness,
and an enlargement of peace and ease of spirit was my portion.
I had to speak of the dominion and rule of Christ our Head,
and the subjection as well as fidelity in which his officers,
soldiers and subjects ought to be to his laws and administration,
void of partiality or fear, as Shadrach, Meshech and Abednego manifested,
as well as Daniel; though temporal laws were made against them,
to prohibit their obedience to their King and Lord, yet they remained unshaken,
and were rewarded with preservation and deliverance.
So will all those sons and subjects that come up in their religious duties,
conscientiously adhering to the dictates of his Spirit, which ever gives the victory.

23rd.--Went to Edenderry with William Bragg; it proved a large meeting,
but in my sense a low one,--cold raw spirits covered by indifference,
bringing death with them to the meeting-place;
unacquainted with a religious exercise at home,
the same ignorance accompanies them even in the solemn meeting,
by which the righteous seed is oppressed,
and the true worshipper loaded with pain very often.

May the Lord of sufficiency immediately stir up these formal pretenders,
and lay on them his judgments; that the transgressing part may be purified,
and the precious seed set at liberty and be in dominion.

Eleventh month 16th.--A meeting was appointed at Dublin
for those who attended the funeral of S. S.,
deceased, at which was a great gathering: my spirit was concerned and exercised;
there were several of my old acquaintances there; but Truth stood in dominion over all,
strength and utterance were granted, for which and all other mercies afforded,
may my spirit reverence and bow at the footstool of my gracious Lord,
Benefactor and King, whose authority accompanies his poor depending children,
and his own strength animates them to sing his praise.

20th.--Was at Rathangan meeting,
in which I felt the supplies of life flowing from the fountain,
and was animated to exhort my brethren;--the words of
the prophet Micah (vi. 9,) took hold of my spirit,
"`The Lord`'s voice crieth to the city,`" etc.;
to which I was enabled to speak in a good degree of authority;
the tendering life arose in the meeting, and the spirits of a remnant were comforted.

27th.--First-day was at Rathangan meeting,
where I felt a laborious exercise and heavy weight,
being baptized into some states there;
my Master enabled me to speak to them in a degree of power,
but the arising of it was not as high in dominion as at some other seasons,
yet eased my spirit.
The passage in Scripture of the people that attended at
the pool of Bethesda came before me to speak of:
they waited for the water to be moved by the angel,
and whosoever stepped in immediately after, witnessed health and healing.
To me it appeared clear, that the way for us to be enabled to get in at the strait gate,
and to advance in the narrow way, was to witness the healing water of repentance.
This gives us strength and fortitude to pass in at the strait gate,
which is indeed too strait for the impenitent sinner to lug along his load of sins,
and the way too narrow.
It is a point of great wisdom to begin right;
for there are many paths pointed out by the devil and his agents,
to lull people asleep in respect to the great work.
Some advance in one path and some in another; formality enters one,
pride and ostentation another, riches and worldly-mindedness another,
and yet all going wrong; for the guide in those paths allows liberties and indulgences,
which the true and heavenly Guide does not admit of in those he guides, and +++[+++which]
will not allow an advancement until washed by repentance, until cleansed by judgment.
Then there is a journeying forward, the perception of the Guide increased,
the light and the experience are enlarged; for the path becomes more shining still:
the nearer we come to the heavenly city, the more are the glory and light revealed,
as we permit nothing to eclipse it.
Therefore may all first witness being washed,
that they may enter with clean feet into this holy gate;
which though strait and the way narrow, leads to the city of the great King;
where the faithful and believing have entrance and sing the song of praise.

29th.--Retired in my family,
and witnessed a low travailing season,--hard work to get down to the pure seed;
which at length I mercifully witnessed, and also the openings of wisdom in degree,
which seasoned and sweetened my poor empty spirit.

Twelfth month 6th.--Being third-day I sat down with my little family,
and witnessed a measure of consolating goodness extended to us; the shortness of time,
and the incontestible truth of coming nearer every hour to our change,
were solemn reflections and truly interesting.
My mind was very low, and my spirit pained before the said opportunity.

9th.--Set forward towards the province meeting, and lay at Ballitore that night;
in the evening we had a sweet opportunity there, filled with instruction.

10th and 11th.--Attending the meetings, which were satisfactory and profitable:
John Alderson +++[+++from England]
had good service for his Master.

13th.--Had a meeting at Kilconner, at Samuel Watson`'s, which was a good meeting to me;
and several states were reached: in the evening had a good opportunity with the family.
In this family I observed a sweet harmony between the
head and all ranks of inferior classes,
that is, between the master and the rest of the family, wife, son, and servants,
which was very beautiful; they seemed to know their places, and how to keep in them;
the savour of life was amongst them, and the virtue of the grace of love was about them.

19th.--Spent at my own house in an agreeable composure; R. S., J. M.,
and several of my relations spent the day with me,
and in the evening we dropped into retirement,
and witnessed a sweet cementing opportunity;
a living supplication was quickened in my heart which I had to put up for our growth,
stability and preservation.

21st.--Passed in retirement, and taken up with writing, reading and meditation.

22nd.--Being a week-day meeting, attended, and felt therein a measure of supporting help;
which after constant wading,
arose to a strong supplication to our great Master for
the continuance of holy protection and preservation,
and the enlargement of wisdom in the souls of mankind,
those of superior ranks as well as inferior; kings, princes,
and judges,--that ambition`'s crest might be bowed down,--that a stop
might be put to the shedding of blood,--hostile invasions checked,
and the spreading of the gospel influence witnessed;
that those places that now appear as a wilderness,
through the rage and ambition of princes,
may become as a fruitful field and as the garden of the
Lord;--that righteousness and peace may kiss each other,
and mercy and truth flourish in the land!

1758,
Second month 29th.--Left my own home to accompany John Alderson (from
England) and several other Friends to the quarterly meeting in Ulster,
and was at Coothill meeting, which being in a very low way respecting the discipline,
we imparted to them what occurred to us for their help and consideration.
From thence we went towards the quarterly meeting, which proved satisfactory,
and we became refreshed in our spirit, one in another.
After which Abraham Shackleton and I accompanied John Alderson towards Londonderry,
visiting both the families and meetings which constitute that quarterly meeting,
and I returned home in peace,
where I found my family well and my affairs in good order,--thanks be
ascribed to the great Watchman and Shepherd of Israel,
who sleeps not by day nor slumbers by night.

3rd.--Went to our province meeting and returned home the 6th, humbled in spirit,
with my eye to my great Master;
whom I think I am willing to follow in weakness as well as in strength.

8th.--Measurably enjoying a serene quiet,
and engaged in looking into the state of the mind.
Having had a prospect for some time past, of paying a religious visit to Wales,
and some parts of England, and the time now drawing near,
quickens a diligence to leave my concerns in such a
state of regularity as may be easy to my mind;
but my principal object is the discharge of my duty,
that I may do the day`'s work in the day time, manifesting,
that I prefer the cause of Jerusalem before my chiefest joy.

Was at our week-day meeting,
where I parted with my friends in a sense of the flowing of
the strengthening stream of life`'s nourishment;
and in the uniting efficacy of its virtue,
had to praise the Lord God of Sabaoth in the demonstration of his opening power.
Left home in order to pay a religious visit to some part of England and Wales,
in obedience to what I believed to be my duty;
and staying a few days at Dublin to take leave of my friends there,
I crossed over to Liverpool on the 24th, and came to Warrington on the 27th,
where I lodged at Samuel Fothergill`'s,
in whose company I had satisfaction administered to my poor weary spirit.
On the 29th, was at Manchester meeting, which to me was low and poor,
yet felt the arising of peace.
When we have but a little strength we can do but little,
and when we have none may we be still, so far as is required of us;
and passively rest resigned to the Lord, who fills the clouds.
Passing on by Coalbrookdale, Leominster, Pennplace, and Swansea,
was at the yearly meeting for Wales, held at Chepstow the 12th and 13th of fourth month.
The meetings were large, and the testimony +++[+++of Truth]
went freely forth with demonstration and power; my mind was low and baptized,
but the strength of my Lord was to be felt, which bore me up.
The 14th, we crossed the ferry towards Bristol, where I attended the yearly meeting,
and stayed there visiting Friends and meetings some days.

Fifth month 1st.--Was at the men`'s meeting,
where I had a short testimony to bear against seniority of years or superiority of
wealth being qualifications to act for the Lord of sufficiency,
who works by wisdom in his church and members,
and brings them under such regulation as makes them slow to speak.
In this city there is a topping people, high in notion, rich in wealth;
to whom the testimony of Truth has gone forth strongly and clearly;
several of the youth have been reached;
unto these I trust the Lord of the harvest will add a blessing,
by helping them forward in obedience.

The 2nd.--Went to Frenchay, where the quarterly meeting for Gloucestershire was held,
accompanied by my dear friends Mordecai Yarnall and Samuel Emlen +++[+++from America;]
after which took meetings in my way to London:
here I attended the yearly meeting from the 15th to the 20th;
in which great unanimity appeared in conducting the affairs thereof,
and reverential gladness diffused itself through the living members:
in our parting meeting the dominion of life was witnessed.
The 21st, being first-day, I was at Devonshire House meetings--easing to my spirit,
which mostly during this meeting was clothed with sadness and girded with, pain;
this however I trust will work for good, and centre in patience.
26th, was at Gracechurch street meeting, which was somewhat easing to my mind,
though I had nothing to offer in it.

On the 29th of fifth month was at the quarterly
meeting at Colchester for the county of Essex,
in which I was concerned, both in the meeting for worship and discipline,
to bear my testimony to the Truth, of which we make profession;
and in support of some branches of our Christian testimony,
too much slighted and violated in that county: this day felt peace to abound.
Next day, in the meeting of ministers and elders, also in that for worship,
I had some service; but did not feel so much peace to flow in my heart as yesterday,
not taking sufficient time in delivering my testimony, which has often hurt me,
and left my mind sensible of mismanaging the work assigned: but, I trust,
the Lord my God will remedy this infirmity by keeping me in a holy fortitude,
granting confidence in the openings of the Word of life, which, indeed,
is the only true rectifier of every disorder of the mind,
both in conception and expression.
Grant me, O! my God, victory over this infirmity,
that I may more and more honour and glorify thy name!

After attending the quarterly meetings of Woodbridge, Norwich, Lincoln, and York,
with other meetings in the way,
I was on the 7th of seventh month at the quarterly meeting at Kendal.
That honourable elder, James Wilson, was there, in his eighty-third year;
whose living counsel in testimony was very refreshing,
and he appeared in the strength of a young man.
He told me of a meeting he was at in London, with Thomas Wilson,
where was a great concourse of people,
and amongst them two persons of high rank in the world,
who sat very attentively while a Friend was speaking,
and seemed to like what was delivered; but when Thomas stood up, being old, bald,
and of a mean appearance, they despised him; and one said to the other; "`Come, my lord,
let us go, for what can this old fool say?`"
"`No,`" said the other; "`let us stay, for this is Jeremiah the prophet,
let us hear him:`" so, as Thomas went on, the life arose, and the.
power got into dominion, which tendered one of them in a very remarkable manner;
the tears flowed in great plenty from his eyes, which he strove in vain to hide.
After Thomas had sat down, this person stood up,
and desired he might be forgiven of the Almighty,
for despising the greatest of His instruments under heaven, or in His creation.
