== Chapter VI.

[.chapter-synopsis]
* At Lancaster quarterly meeting
* South Wales
* Visits meetings in Ireland
* Marriage to Sarah Beale.

On the 11th of eighth month, 1758, I came to Lancaster to William Dilworth`'s;
the quarterly meeting for ministers and elders was held the same evening,
in which comfortable counsel was imparted in the opening of best wisdom:
James Wilson was engaged to tell us not to quench the
Spirit by reasoning with flesh and blood,
and waiting for large manifestations;
but in the stirring of life to give forth what we have in faith:
but reasoning quenches the Spirit,
and in the flowing of the tide of life the vessel is to move, not in the ebbing.
The 12th, we had a large satisfactory meeting;
many testimonies were borne in the authority of Truth,
and the hearts of many were refreshed; in the afternoon,
the business was wisely and prudently conducted,
which ended the quarterly meeting satisfactorily.
The 13th, attended their week-day meeting,
and the Lord our God was mercifully pleased to favour us with His life-giving presence,
in which we had to praise His glorious name, who is worthy of praise,
dominion and honour for ever.
Amen!
Came that evening to Chorley with J. Routh and S. Taylor,
and parted with my valuable companions, John Griffith, James Wilson, Lydia Lancaster,
Grace Chambers, and several other worthy Friends, whose company, conversation,
and deportment were very grateful to my mind.
Accompanied by Joseph Harwood, I visited the meetings of Cheshire and Derbyshire;
and taking meetings in the way passed on to Wales,
and came to Swansea the 2nd of ninth month,
where next day I attended their first-day meetings, in which I had close labour;
heavenly aid was mercifully extended to ease my spirit.

The following first-day I was in both meetings opened
very much to the people of other societies,
who came in pretty freely; and though it was close labour,
and a time of weakness as to the state of my mind,
the Lord my God richly supplied with the opening of his word,
and the doctrine of the gospel of life and salvation was freely preached to the people,
and the meetings concluded with a sense of Truth over the spirits of the people.
It is remarkable that on fifth-day provision was made for my voyage homeward,
and an expectation of my going that tide;
I told my friends that I could not see myself in a spiritual sense yet gone,
though affection to my family and love to my native country strongly attended;
and though the vessel was under sail, yet she was detained in the harbour,
the tide not flowing high enough to carry her out.
So that great need have we all to stand single
to the Lord and his revealed glorious light,
which will open by degrees our duty to us, and animate us, as humbly relied on,
to fulfil it.
May the Lord my God strengthen my soul with His own pure power and wisdom to wait on Him,
till He gives a sure and certain intelligence of His own pure will, which,
as I live in the performance of, is my sanctification.

Ninth month 11th.--My mind seems resigned to attend the quarterly meeting at Pennplace,
and so to proceed to Carmarthen and Haverfordwest, and then, if the Lord please,
homeward.
And thou knowest, O my God! that my delight is to do thy law,
and to obey thy holy direction: support me, my spirit humbly beseeches,
to the latest period of my days, to walk in thy paths,
that my soul may at last have an entrance into that kingdom,
wherein the righteous redeemed souls have an inheritance.

Tenth month 3rd.--I sailed from Haverfordwest, landed safe at Dunleary,
and came to Dublin; where I stayed several days attending meetings.
On the 12th, I was at our meeting at Rathangan,
in which ancient Goodness was pleased to appear, to the tendering of my spirit,
in commemoration of the mercies received in my late journey.
I was bowed, and my heart reverenced that Power which hitherto had shielded, protected,
and preserved.
In the evening returned home to my family, a peaceful serenity covering my spirit;
for which, and every other blessing received,
may living thanksgivings be rendered to the Lord my God, who is everlasting worthy.
Amen.

13th and 14th.--Spent in emptiness, though at the bottom felt sweet peace,
which indeed is the reward that is the true riches.

16th and 17th.--Taken up pretty much in reading, writing, and retirement, by intervals,
very delightsome and agreeable.

18th.--Attended the monthly meeting at Edenderry:
the stream of Divine goodness was measurably extended to the
tendering of my heart in the fore part of the meeting,
but towards the conclusion it ceased, and exercise and dryness ensued,
and the meeting ended in silence.
It was a large meeting, and many I believe had their expectation outwards,
which often proves a hindering impediment to the poor servants.
In the meeting for business some Friends seemed desirous I
should give some little account of my journey,
which I had upon my mind to give in humbling fear,
and there seemed to be a reception for it,
in which comfort opened her gates and heavenly refreshment entered.

23rd.--Pretty quiet and still, at seasons looking inward for the arising of the Beloved;
taken up in writing, reading, etc, a portion of time.

24th.--Empty and lean,
yet desirous to be relieved with the opening of
invisible succour and strengthening goodness;
awful fear looked me full in the face,
which raised a desire that I might be what the Lord my God would have me to be.

29th.--First-day; our meeting was to me trying,
through the abounding and retiring of that which is our strength;
for I find it hard to keep pace with its circulating, awakening visitations,
and only to move in its pointings.
May the Lord of my life make me more wise,
that the powers and faculties of my soul may be devoted
to bring honour to his great and everlasting name!

Eleventh month 1st and 2nd.--Attended the half-year`'s meeting at Dublin;
the meeting for worship was low and exercising to some,
who had a diligent travail and exercise on their spirits for
the heritage and the appearance of its glory.
The meeting for business was more refreshing,
and the members more united in living enjoyment:
it was favoured on the 2nd with a degree of the presence of its holy Head,
and a quick zeal for the welfare of our Zion and the
prosperity of her children was felt amongst the gathered few.
In the evening was held the meeting of ministers and elders; on the 3rd,
we were much owned, thanks be to the mercy of our God,
and indeed I thought we were well rewarded for all our
concern and exercise in the foregoing meetings.
5th was the first-day of the week, I was at both meetings:
our worthy innocent friend Robert Hervey, from Old Meldrum, in Scotland, was there,
and had good service for his Lord and Master,
and quite agreeable to the state of the meeting, though his testimony was sharp.

10th.--Went to Robert Fayles`' burial, where I had good satisfaction,
but should have been easier if I had taken more time to deliver what was upon my mind;
but have often thought it better to feel pain of this sort myself,
than burden others with long dry declarations.
Went that evening to sit with the widow and fatherless,
in which visit had comfort extended.

16th.--Visited +++_______+++'`s family,
which nearly concludes our services in this quarter in visiting +++[+++with a committee]
the families of friends:
and though it took a considerable time to pass through the families,
and very close travail and exercise,
yet there was a gracious reward administered for our labour and trials;
for the states and conditions of the people are such in this day,
that close doctrine is indispensably necessary;
and the openings of Truth are such that nothing but cowardice and unfaithfulness
can evade the pointings of it in those who have it to distribute to the Society.
Those who were employed in the service increased in the living unity,
and peace was multiplied to them.

Twelfth month 26th and 27th.--Much taken up with my outward affairs,
and in preparing for the quarterly meeting,
yet in the midst thereof felt the solid stirrings of the
influence of preparation for worship and silent adoration,
and a longing after unfailing aid to live more
circumspectly and inward from external objects.

1759, First month 18th.--Our week-day meeting, where I was comforted in holy silence,
which as dwelt in (without a certain assurance
to move to duty in utterance) enriches the soul.

Second month 13th.--Sat down in my family in a religious frame of mind,
in which I witnessed holy Help to be near to open counsel and instruction,
which I dropped, to an increase of ease and peace, 14th.--In retirement.
Quietly composed, and taken up in reading and writing.

15th.--Our week-day meeting, whither I repaired and found a deep travail of spirit,
which towards the latter part measurably disappeared,
but strength in contentment increased.

20th.--Sat down with my little family in religious retirement, where,
after low waiting in silence, I felt nourishment and help to my spirit.

Third month 6th.--Went to visit a professor in his family,
which had for some time been upon me, but by not giving up to it had rather abated;
the accomplishment thereof yielded a good degree of satisfaction and instruction,
and I hope heightened a caution in future to observe
the motion of Truth in the immediate operation of it.

20th.--Being the third-day of the week, found drawings to sit down in my family,
and was favoured with a portion of a reconciling peace for the practice.

Fourth month 5th.--Our week-day meeting at Rathangan,
which was small and weak as to Divine favour,
but towards the conclusion the rays of light broke in upon us,
and opened the understanding, nourishing the spirit; no public appearance.

16th and 17th.--Was at the assizes and fair at Kildare,--hurrying places,
much attended by an inconsiderate people:
but as long as we are in this life we must have connections with the people
of the world,--may the God of my life keep me from the spots of it!

19th.--At our week-day meeting in which I felt a quiet travail of spirit,
comfortingly instructive.

Fifth month 26th.--I was at a tiresome fair, selling and buying,
and exposed to disagreeable company; in the evening came home,
and soon after received tidings of the decease of my friend Samuel Sharpley,
and his request that I would attend his funeral;
which brought heavy exercise over my mind and much anxious thoughtfulness,
having several things occurring to prevent my going.

27th.--Awoke early, and gave up the expectation of going,
and wrote a few lines to my dear friend`'s spouse in excuse;
but when I mounted my mare to go to our meeting, I felt so strong a draft,
and so sweet an unity with the spirit of the deceased, as to give up freely,
which caused every obstruction to vanish.
I got well to Dublin after a very hard ride,
went to see the widow with whom I had a very sweet opportunity,
and my spirit was deeply humbled under a sense of the goodness of God in mercifully
rewarding for cheerfully giving up to the pointings of His holy Word:
afterwards I attended the funeral,
and gracious Goodness was pleased to assist in the discharge of duty,
amidst numerous unsanctified spirits;
the testimony of Truth was exalted above their dark spirits, and mine got great ease,
and thankful I was that I was enabled to attend it.
Went in the evening to see the English Friends, viz: J. Haslam, and Joseph Milthrop, from.
Yorkshire, who landed last week in order to visit Friends of this nation,
28th.--Returned home in a peaceful quiet,
renewedly sensible of the extendings of the mercy of God through His Son, Christ Jesus,
to whom be glory and honour ascribed, both now and forever.
Amen!

Sixth month 12th and 13th.--Pretty much at home,
and taken up in reading the Scriptures and retirement;
a language was raised in my heart to cry for fresh anointing and consecration,
that I might stand more perfectly in my lot in this life,
and in the end have a portion in the next in a state of holiness and purity.

Seventh month 7th.--Not so much retired as I am well convinced would be profitable;
company hindered; may the Lord my God in mercy sanctify every disappointment to me,
and bring me more and more to that holy disposition to look to Him through all things,
whether disappointments or successes.

9th and 10th.--Pretty much engaged in outward affairs,
though sometimes I burst from them to look a little in stillness for sure help to
worship and adore the Author of universal and enduring goodness and grace!

11th.--This day in sweetness and quietude, for which I hope to be thankful,
and desires arose for my future advancement in grace,
and the revelation of the knowledge of our Lord and Saviour Jesus Christ.

26th.--Was at our monthly meeting, and after a season of deep travail and exercise,
the virtue of Truth sweetly arose to the refreshment of a remnant,
and the power of the Lord our God was in dominion.
Susanna Hatton had a favoured season in testimony and supplication,
and the spirits of a remnant worshipped in reverence.

Eighth month 8th.--Attended my outward affairs pretty closely, but at times stole +++[+++away]
to an inward inquiry to feel after support in retirement, reading, etc,
15th and 16th.--Was amongst my friends,
who suffered by the violence of the mob in their worldly rejoicings,
having their windows much broken, and the women frightened;
endeavoured to strengthen Friends in their dissent from this worldly conduct,
that tends rather to the dishonour than the glory of God.

25th.--About some outward affairs distant from me,
which I was considerably fatigued with; it was the attendance of the Assizes,
and had a cross judge to deal with.
26th.--Our first-day meeting at Rathangan,
which proved an open consolatory season after much exercise and travail;
for which praise was offered up to the Everlasting Support of integrity and innocency.

27th.--Was this day at a fair, where I was hurried,
but a good degree of quietude attended my mind; returned home easy in the evening.

Ninth month 8th.--Much in outward hurry,
but yet found inward aid to breathe for preservation.

9th.--First-day: went to Edenderry meeting,
where were the English Friends J. H. and J. M.;
the meeting was very large and very exercising,
though methought the good old Friend J. H.,
had a pertinent season to the state of the meeting through a strong wrestle to obtain it.

10th.--Low in spirit,
feeling a strong conflict of the motions of fleshly pursuits and gratifications.

11th and 12th.--In a degree of more quietude than for a few days past,
much drawn at seasons to retire and read;
found my passions at certain periods of time strong,
but retiring found a succession of coolness and ease to take place,
13th.--Our week-day meeting at Rathangan,
which was to me a season of deep and low travail,
scarcely feeling the stirring of the breath of life.
In the evening read in the experiences of other Friends,
and had a sweet union with some of them this night in my sleep;
arose in the morning united to them in spirit, though one of them deceased.

14th and 15th.--Pretty busy in the outward,
yet several times retired and profited by reading the Scriptures,
and indeed I find retirement the greatest safety we can enjoy in this world of probation,
it tends to inform respecting our duty in the outward,
and strengthens the faculties of our soul in pursuing unceasing felicity.

16th.--First-day, found a draft of mind to be at Edenderry, which I followed,
and felt renewed occasion humbly to bow in spirit to gracious Goodness for help;
several matters appeared to be my duty to drop, which I did in the ability afforded,
so as to feel ease, and the administration of peace.
And indeed it is to be deplored to feel so much rawness
and indifference amongst the professors of Truth,
and it is to be feared so little of a growth in it,
in this time of outward ease and tranquillity in this unworthy nation.

17th.--This day exercised and in conflict of spirit, very impatient about outward things,
be cause so much negligence appeared in those I believed ought to be more careful;
thought of the apostle`'s assertion, that they were of like passions with other men;
but it is our indispensable duty to have these passions
subjected to the operation of the Spirit and working of Truth.

Ninth month 26th.--Was at a meeting at Ballitore,
with my esteemed friend Catharine Payton.
Here the mysterious fountain of gospel communication was admirably opened,
and indeed the deeps were broken up in my heart,
and I was mercifully blessed with a sight of my own state;
which I trust will produce additional degrees of humiliation,
and beget greater devotedness of soul to the service of the bounteous Author of my being,
who alone has an absolute right to body, soul and spirit.
It is the prayer of my heart,
most Gracious Fountain of blessedness! that thou wilt break every inordinate affection,
and dash in pieces every conceived opinion or conjecture,
which does not tend to thy own honour,
and the enlargement of my experience in that path of liberty, into which, I am convinced,
thou hast called me;
that I may be happy here in time and enduringly happy I in an endless eternity.
Amen!

28th.--Was at Mountrath meeting:
the softening virtue of contrition attending in my journey,
begot fresh cries for preservation and caution in
stepping along through the narrow lane of life;
the meeting too was eminently humbling to my spirit,
and some parts of the testimony applicable to my condition,
which I hope I shall not forget.
One thing in particular,
the necessity of taking heed how we strive to build our own houses,
while the house of God lies waste; the consideration ought to be lasting,
for such an attempt may be accompanied with Divine displeasure;
even of Him who can in a moment destroy the most
stately structure of man`'s building or invention,
and turn proposed happiness into misery and disappointment.
May His holy hand of prevention be exalted for
the safety and preservation of His children,
and a disposition formed in the soul to follow the Lamb whatsoever way He leads;
that our journey towards Mount Zion may be prosperous,
and our inheritance in light enduring as the heavens.

30th.--Being first-day, was at a meeting at Mountmellick with Catharine Payton;
it was memorable for a loud and fervent call to the sinner in Zion:
it continued to me (as were several other opportunities) a baptizing and bowing season.
Afterwards my honoured friend had a meeting with the
ministers of that meeting and others who were there,
instructing as well as comforting.
I returned home in humbling peace, diffidence and fear,
lest in future I should not come up in that devotedness of soul,
that I conceive is my indispensable duty.

Tenth month 2nd and 3rd.--Pretty much retired,
read the Scriptures in a disposition to sweeten my spirit,
and edify and increase my experience in the blessing and advantage
that arises from those sacred books being preserved to us,
through all the dark generations and apostatized spirits that have appeared in the world,
and that have pretended to be interpreters of those sacred truths,
and to have them limited to themselves.

10th.--'`I left home to pay a visit to the county of Wexford.
My mind has been bowed and low of late;
renewed desires have been kindled to serve the Lord my God in more devotedness of heart:
may the preparation be by His own pure power and Spirit,
and beget in me an humble acquiescence to the turning and forming of His holy Hand;
that the dross may be purged away, and the temple be purified,
to the honour of His great and excellent name.

28th.--Returned home, after visiting most of the meetings in said county,
and also in the county of Carlow,
in which visit my dear companion Abraham Shackleton was often
favoured to communicate counsel in the openings of Divine Wisdom,
and we laboured according to our ability and with some success;
though we had to drop some close things at times respecting dress, address, etc.,
in the feeling of the reaches of the Divine Arm,
that would gather all home to its saving fear.

Eleventh month 23rd.--Went to Carlow to the quarterly meeting,
in which the arisings of Life were witnessed:--the beauty, glory,
and spreading of Truth were graciously extended,
and arose into dominion over all opposition,
and a sweet union I felt with my dear friend J. G.,
whose service and labour was much attended with Divine favour and fervour;
the spring of supplication was open,
and we had measurably to drink of that Rock that followed Israel:
and in the Friend`'s family where I lodged,
it was likewise experienced to the mellowing the hearts of several,
and we parted in peace.

26th.--Set forward to Ross, Waterford, Youghall, and Cork;
at the latter place I remained some days,
my principal object being to demand in marriage Sarah Beale,
daughter of Joshua Beale of the latter city:
this subject had weighed on my spirit for more than eighteen months,
and at last so strongly did it open before me and with such clearness,
that I gave up reasoning upon it;
and on the tenth of twelfth month I opened my mind to her father,
who took it into consideration;
in a few days he gave me liberty to lay the matter before her,
and I may say the evidence of Divine favour attended in our communion and conference;
and as it was the Lord`'s doing, I believe, to open it in my mind,
so L trust He will be graciously pleased so to work in it,
as to bring it about to His own honour and in His own time.
I visited several widows, the sick and infirm,
in which service Holy Goodness was graciously pleased
to favour with a renewal of strength and daily supply,
both in those services and in meetings for public worship, to my Own humbling admiration;
and thus was I engaged until the 28th of Twelfth month, when I left the city of Cork,
committing my cause to the Lord my God, and returning home on the second of first month,
1760, found my family well.

First month 11th and 12th.--These two days passed in the mixture,
sometimes sustaining Goodness was near,
and sometimes a sense of emptiness and nakedness was the covering of my spirit.

13th.--In our first-day meeting at Rathangan,
had several things opened upon my understanding, but which closed again;
part of the meeting was inwardly strengthening, and part exercising.
After a wrestling exercise a sweet serenity spread itself over the meeting,
and it ended in solemn silence; after which had the enjoyment of inward sweetness.

29th.--Went to Cork to visit my beloved friend Sarah Beale,
in whom I believe the Divine Arm worked to make way for my reception,
though to be distinguished only by close observation;
her becoming reserve and prudent conduct making it but very little obvious;
but the internal communion and union with her spirit which I felt,
gave hope that the Lord`'s guiding strengthening counsel was sought for by her,
disposing her to yield to the pointings of His will.

Second month 28th.--At meeting at Rathangan;
my spirit was much refreshed and united to the spirits of my friends;
an earnest supplication was formed in my heart for preservation in future,
and that nothing might wrest or take from the arms of
Divine protection,--neither heights nor depths,
prosperity nor adversity; and it is the humble petition of my heart at this time,
that the Lord my God may so open of His heavenly wisdom in my soul,
as to keep me steady in the pursuit of the,`" one thing needful;`"
and so to proportion His strength and power to my wants,
as to give ability to pass the narrow sea of life to His own honour and glory.

29th.--This day in a state of retirement,
sweetly retrospecting and commemorating the mercies and favours of the Lord.
May an holy acquiescence with His will be my delight.
And work thou, my God! passive obedience in my heart, where Thou art wont to work,
to bring forth those fruits with which Thou art well pleased;
it is only effected by the operation of Thy invisible Hand: work, therefore.
Lord! and who shall let it?
Fourth month 8th.--This day L was married to Sarah, the daughter of Joshua Beale;^
footnote:[Said to have been the granddaughter of Joseph Pike.]
and the gracious donor of every good gift and blessing was pleased to attend.
Our friend John Griffith was helped to declare of the goodness of the Lord,
and to set forth the excellency of seeking Him in all our undertakings;
especially in that of marriage.
It was a season of real profit and help: my soul seemed filled with Divine Goodness.
May an enduring remembrance of the greatness of the Lord`'s mercy,
influence my spirit to follow Him in greater degrees of devotedness.

Seventh month 6th.--First-day, was at Rathangan meeting,
and was helped to bear testimony to the excellency and power of the Prince of peace,
inviting all to enlist under Him, who is Prince, Bishop, Minister, Captain and Shepherd.

26th.--Accompanied the corpse of A. Barcroft to Dublin; it was a large funeral,
and at the grave a lowness of the life and virtue of gospel power attended,
in which state I durst not move to offer anything,
though some view of Scripture openings and passages appeared to me;
the people seemed uneasy that nothing was offered,
though the true qualification was wanting; I felt easy and resigned afterwards.

Eighth month 14th.--I was at our weekday meeting,
in which I had to speak of the apostle`'s comparison respecting
the branches that were broken off from the good olive tree,
and of those that were grafted in; towards the one, goodness, and towards the other,
severity;--setting forth the goodness to those who keep their places,
and His justice on them that keep not their places;
and the necessity of being not high-minded, but to stand in a state of fear,
by which we live in the true faith and continue to partake of the Lord`'s table.

26th.--This day attending +++[+++to outward matters]
with pain and poverty.
Went to see my sick cousin Jackson, with whom I had much sympathy; but +++[+++divine]
aid being withheld I was incapable to help her or afford her any instrumental comfort.

27th.--This day was at cousin J.`'s, about an hour after his wife`'s decease,
and it was a scene of exercise and trouble to behold him and
his four children deprived of their valuable friend and helper,
a woman that promised well to be of service in our Zion;
but all-wise Providence knows when and how to remove his creatures,--who to call away,
and who to reserve for a state of toil and trouble!
My spirit was much united to hers in the flowing of Life`'s circulation,
which was often her experience to feel,
and I seldom went to visit her but methought I felt an increase of spiritual strength,
a stronger knitting of the bond of fellowship,
a pleasure resulting from Christian friendship;
and I am persuaded she witnessed an increase and growth in
knowledge of the revealing virtue of Christ Jesus our Lord,
and I believe her spirit lives amongst the redeemed and ransomed,
to partake of eternal life!

29th.--Attended the funeral, which was large, my mind was calm and quiet,
and way was opened to bear testimony to the excellency of the Seed,
what it would do for us if attended to, the bruiser of the serpent,
the quickener of life,
the slayer of the evil seed:--came home afterwards with the sorrowful husband.

Ninth month 7th.--First-day of the week, was at our meeting.
It was a season of deep travail,
yet gradually I experienced the gentle arisings of the power and virtue of Truth,
and I had to speak to that saying recorded in Scripture, "`Watch in the watch-tower, eat,
drink, arise ye princes and anoint the shield:`" Truth arose to such a degree,
that it made way and entered the hearts of several there,
bowing them down and enabling them to offer the
sacrifices of a broken and contrited spirit.
It was a season of favour on account of the people,
for which the praise is to be ascribed to the invisible
operation of that unction that comes by Jesus Christ,
through the mercy of God the Father,
to whom let thanksgiving and renown be for ever dedicated!
