== Chapter VIII.

[.chapter-synopsis]
* Quarterly meeting at Waterford
* Attends the yearly meeting in London, 1765
* Also that of 1768, etc.

1764, Sixth month 18th.--Attended the quarterly meeting at Waterford:
in the meeting for worship the authority of Truth arose,
and dispelled heaviness and cloudiness; it was a season of favour.
The meeting for discipline was also attended with favour; counsel and advice were opened,
and ability unsealed to carry forward and transact the business.
In the afternoon I went to see some of my friends,
and felt a concern to visit some of the families of Friends in this city;
which others also feeling, we agreed to begin the next morning,
and so continued in that service with daily renewings of power from on high,
until the whole was accomplished, much to our satisfaction who were engaged therein;
and breaking of bread was witnessed from house to house,
to the praise of the excellent name of our God.
A meeting for worship was held the sixth-day (the 21st,) as usual,
which was a season to be remembered--the divine evidence replenishing,
the fountain opening, as an excellent oil, increasing the light of our candle,
abilitating to stand forth in the name and power of the Lord of Hosts.

Seventh month 11th and 12th.--Was pretty much taken up with temporals,
yet favoured with so much recollection as to look inward:
read a portion of the sacred writings,
which generally leaves a liveliness and relish on the mind to edification.

Eighth month 26th.--First-day; in the forenoon meeting I had some refreshing openings,
and it ended with a short testimony in a degree of living authority:
I was concerned to exhort against resorting; to theatrical amusements,
and entering into the congregation of the dead;
for the apostle declares that they who live in pleasure are
dead while they live:--mentioned the hurtful consequence,
and the tendency it has to poison the minds of the youth,
giving them a disrelish for things sacred and religious,
and throwing them into a state of lightness and
a love for things and books that do not profit.
In the evening I was concerned to exhort the youth to read the Scriptures,
that their minds may be impressed and furnished
with the happy experiences of the righteous;
exhorted parents to remember the wise man`'s advice,
to train up a child in the way he should walk;--and much depends upon judicious training.

Ninth month 3rd.--Our men`'s meeting; in which little life stirred:
some remarks were made in some degree of good will to the cause,
but the water was scarcely sufficient to bear up above its surface,
to breathe for succour and preservation in the Lord`'s cause and work,
and to stand stedfast in every dispensation.

8th.--This day in some conflict of mind in the forenoon:
went to the meeting of ministers and elders, which was dry and husky:
in answering the queries a degree of light and strength arose,
to exhort to diligence and inward attention to the Lord`'s work and service.
Had to speak a little of the sickly state of the Society,
and that it reached some of the members of that meeting.
Returned in some degree of quietness, and read a little of best instruction.

Tenth month 27th.--Went to Clonmel to our province meeting;
on the 28th and 29th meetings of worship were held:
my mind was bowed under a renewed sense of the Lord`'s mercy and loving-kindness extended;
the meeting of business was in degree satisfactory,
and the affairs of our province harmoniously conducted.

Eleventh month 1st.--Proceeded to Dublin to attend the National meeting.
3rd. Our National meeting of ministers and elders;
in which Friends were measurably favoured with the extendings of divine help,
to worship Him that lives for ever.

4th.--The meetings for worship were owned with the revealing of light and life;
the testimony of Truth went forth in authority,
and the Power was manifested to be in dominion.

5th, 6th and 7th.--Our business was conducted in brotherly affection and nearness,
a travail was witnessed for the good of the body, and some steps were gained, I hope,
conducive thereto.

Twelfth month 8th.--I got well home, for which,
through the continued help and assistance of a gracious God, for every favour, blessing,
and benefit administered, may thanksgiving and praise be ascribed now and for ever!

11th.--At our week-day meeting in Cork, in which I had some sweet openings,
but not for the people; a nourishing solemnity was over the meeting,
in which frame it ended.

1765, Third month 25th, 26th, and 27th.--At home endeavouring to forward my business,
in order to be the sooner able to leave home,
and single myself out for the work in which I apprehend myself measurably engaged:
though very poor and weak, yet the Lord is strong; to whom belongs dominion, power,
and praise!
He can strengthen the weakest of his creation in his own cause, and raise them up,
to their own admiration and that of others.

Fifth month 4th to the 9th.--Our National meeting at Dublin;
our friends Isaac Gray and John Townsend from England were there,
and their service was very acceptable; the virtue of life prevailed amongst us,
and the family were refreshed by its holy influence;
for which the Lord who works deliverance, was praised, magnified, and adored.

10th.--Myself and wife took shipping for England, and landing the 12th,
set forward for London.
It is to be noted that in this journey we lodged at Whitechurch,
and as I went up stairs to go to bed,
I felt my mind very much affected with a sense of fire;
which caused me to open the window twice before I lay down,
to look out and see what distance it was to the ground from the chamber where we lay,
in case of fire.
The reason of mentioning this is, that in a little time after,
we had it in the public papers that two parts of this town were burnt,
and some part of this very inn where we put up, according to intelligence received.
This circumstance manifests the favour extended to mortals by
those intimations given in the mind as a forewarning,
and encouraging to look for succour in that Power which can abate the force of fire,
being a refuge from storms and tempests,
and a security against the deepest and most powerful trials:
well is it for them who trust in this munition!

I attended the yearly meeting in London,
in which there was much unanimity amongst Friends;
the body was edified and the Great Lord of the harvest praised: after it was concluded,
I stayed in and round London,
visiting my friends and such meetings as I felt my mind drawn unto,
until the 21st of sixth month; when I set forward towards Chester,
and taking shipping the 27th, got well to Dublin the 29th.

Seventh month 2nd.--Attended the weekday meeting at Meath street,
where was brought the corpse of innocent honest Gharrett Van Hassen:
Elizabeth Hutchinson was there and had good service,
and I may say it was a season when divine refreshment was unsealed;
also at the burying ground,
testimony was borne to the innocent pious life of the deceased,
as well as to the necessity there is for the living to prepare for death.

Eighth month 5th.--Our men`'s meeting at Cork;
in which I had some close remarks on the indolence of parents,
in exampling their children in waiting before the Lord
for the incomes of his heavenly presence,
and reading the Scriptures on first-day evenings;
instead thereof they were little festival seasons,
when young people got together and were exercised in unprofitable conversation:
also exhorted some of the elders who were near the brink of immortality to
seek to that which quickens and enlivens to live to the Lord Almighty.

Eleventh month 22nd.--A satisfactory season at meeting,
feeling towards the conclusion a cry to arise in my soul for mercy and preservation,
and that it might be extended to others also.

23rd.--This day pretty busy outwardly, and in the evening reviewing some past steppings;
may my future ones be ordered by my great Master,
and may my attention be often turned towards his holy counsel,
which proceeds from the pure Spirit of Truth,
that leads and guides its faithful followers into all truth.

1766, First month 28th.--Our week-day meeting;
in which I felt a few sentences to impress my mind, which I dropped,
to my renewed consolation and peace of heart;
and indeed the savour of Truth rested so on my mind this day and the preceding,
that poverty and leanness, so much my portion of late, seemed as nothing,
and my spirit was taught to magnify that Power that
changes the wilderness into a fruitful field,
and causes the parched ground to become a pool of water.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Glanmire, 16th Second month, 1766.

[.salutation]
Dear Friend,

I received thy acceptable lines of the 31st instant.
I thought I should soon hear from thee by the pointing of my mind so frequently that way,
with some degree of brotherly nearness,
which I am thankful to feel spring in my mind to any of the brotherhood,
and particularly those I most intimately communed with
in spirit when under the early distillation,
in the spiritual journey, of that rain that moistens and softens,
and where it penetrates, makes all green and beautiful.
I sometimes look back with thankful admiration at the turning of that
holy Hand that was put forth to steady and balance our stepping,
to cause care to spread over our minds,
and to stain the beauty of terrestrials in our view,
and which at the same time attracted our minds upwards: we were then loosened,
shook from our dens of carnal ease, pleasures, and security, and went forward prevailing,
having the brook for our stay, and the bread for our staff.
This was a time of love, shower after shower, the ground was prepared, and the seed sown.
The query is to my own soul with my visited brethren, What is the fruit that has appeared?

Verily I have feared for myself and for them, many of them, we are like Ephraim,
an empty vine, bringing forth fruit unto ourselves, after such beginnings,
when the language was, "`If thou wilt be with me in the way which I go,
give me bread to eat and raiment to put on, thou shalt be my God and I will serve thee.`"
The deficient part is on our side,
for many of us are too much contented with serving ourselves,
and only giving a small part of our attention to
the service of Him that requires the whole heart;
and indeed if our hearts were but enough pursuing the one thing needful,
they would be so replenished with wisdom and understanding,
as to be awakened to greater degrees of vigilance in a life of righteousness.

I heartily and earnestly desire we may, dear friend, look about us,
see what is required of us, after looking to our own garments;
whether any stain appearing on them may prevent
our approaching the distempered of the flock,
who are very apt to evade the probe by an obvious stain
or scar appearing on the physician or his deputy.
I really fear we are a withering people in this land;
former experience is not to be depended on; literal rules and laws,
however exactly observed, will not carry on the work,
nor stand in the gaps that appear in so many places in the wall,
but in the aboundings of that life that has judgment, mercy and justice.
I am jealous that if we have not some raised up in the spirit of Phineas,
who was zealous for his God,
and by his zeal made an atonement for the people when the plague was begun in the camp,
we shall have many wrong things to break in amongst us,
and perhaps through some that may appear as princes amongst the people.
Many of the sins that crept in amongst Israel formerly,
were through the priests and the princes,
and whenever the distemper catches the first rank it soon spreads amongst the host.
May the Lord our God stir up the pure mind in each of his visited children,
that their chief and principal care may be in looking to the law and testimony;
for as we honour this, and prefer it before our chiefest joy,
a blessing accompanies the exercise and care, and we grow in heavenly riches.
And where the eye is turned to accumulate earthly riches,
it slides into a state of indifference as to the vitals of religion,
a superficial care seems visible; when convenience will admit, services are performed;
and so dimness, drowsiness, and death prevail.
This is very much the state of the churches in many places,
and sorrowfully so in this quarter:
may the Lord Almighty cause fight to break upon
us that we may be delivered from every death!

May the good Spirit work all our works in us, and for us,
that we lack nothing of that weight of glory,
which will entitle us to sing amongst the sons of God a song of salvation and victory.
My heart nearly and warmly salutes thee, etc., etc.,
which continues me thy affectionate and real friend,

[.signed-section-signature]
Samuel Neale

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Glanmire, 4th of fourth month, 1766.

[.salutation]
My Dear Friend,

Thine I received with affectionate nearness.
Let me write or speak to thee sometimes a little closely,
I have nothing in it but good-will.
I desire the same freedom may be used to me;
we ought to be as spurs one to the other to quicken our care and diligence,
when in our domestic lots we are ready to be tinctured with worldly cares,
that to this day choke the seed of the kingdom,
hindering our seeing in such a degree of clearness as if we waited more deeply and
attentively for the unsealing of that spring which is the believer`'s satisfaction.
Specious are the excuses always at hand, which the pilgrim is apt to join with,
to multiply a little more liberty to the carnal part, that deserves death by denial.
I speak my own experience, and perhaps it is also my friends, and is it not our duty,
and ought to be our principal care, to search after death upon self;
the more we abstain from it and save its head, the harder work we make in the end,
and the longer the glorious design of existence is baffled.
I often eye the path, by having the view opened to me,
in which the Christian ought to walk; it is strait and narrow, but purity may pass it;
the greater mixture we have, the more difficult I see it plainly,
and this makes this path so much avoided, and so destitute of travellers.
Some would willingly walk in it provided they could introduce such and such beloveds;
they are too cumbersome and cannot abide the glory of this path,
are in a dying condition whilst in it,
and this I believe is the cause why so many
leave it and turn again to the beggarly elements;
+++[+++who]
after beginning in the spirit, they think to be made perfect by the flesh.
Or alter know`'ing the day of the Lord to come upon those
things that were as pleasant pictures or fenced towers,
where they had fortified themselves,
think they may take greater liberties now as they grow m experience,
and so are for erecting a standard of their own,
assigning limits and bounds to themselves, forgetting the covenant,
"`If thou wilt be with me, give me food and raiment,`" etc.;
little served in the day of infancy, now it is multiplied beyond expectation,
and for the utility of the search a reason assigned.

My mind, on taking a view of the visited in this nation, has been distressed.
I include my own state with them; had we all been more honest to our feelings,
I am persuaded we should be more established;
and yet I know there are still several who love the Lord,
and delight in feeling after His presence when easily come at:
but by much watching they become weary and faint in their minds,
seek for relief in their earthly enjoyments;
and so slide by little from that dependence that craves bread from the Divine treasury.
The Lord is just and equal in all his ways; He rewards in due season the devoted,
honest and industrious; though He may seem to tarry long,
yet when He comes his reward is with Him, and He is glorious in his arising,
for He scatters every enemy.
There are that would be heirs of two kingdoms; but this cannot be,
we must relinquish one or the other;
and there is this encouragement for holding to the kingdom of righteousness,
that every necessary thing will be added.--Life seems less in dominion in our meetings,
the people less attentive I think to their duties, and lethargy prevails;
leprosy has appeared where light had its abode,
so that I am ready to fear we shall scarcely be a people to administer the law.
We have been visited by Ann Kenyon from Liverpool,
her service seemed to awaken and arouse,
and show she was much in the state of our meeting: according to my judgment,
she seems to carry a sharp weapon, and yet wins the people.
After her came dear William Reckitt, who stayed with us a week;
the authority and virtue of Truth accompanies him,
and an ornamental conduct sets home his doctrine.
Our united love is to you both, my dear friends, also to thy father, mother,
and others in thy freedom, which continues me in stedfast friendship thy near friend,

[.signed-section-signature]
Samuel Neale.

--

Seventh month 21st.--This day employed about my outward concerns;--my
mind was in a state of toil,--had but very little time in retirement,
felt inward poverty and a real want of bread.

22nd.--Engaged as yesterday,
the mind a little more free and less susceptible
of the strippings of that heavenly clothing,
which is its strength and beauty.

23rd and 24th.--Much employed about my outward affairs;
sometimes felt a desire spring up to be more sustained by grace,
which quickened prayer to intercede for it in a short ejaculation.

1768, Fifth month 11th.--After having attended the National meeting in Dublin,
I embarked for Holyhead, and landing safely,
attended many meetings prior to being at the yearly meeting in London:
visited divers meetings and Friends in that city;
returned through part of Scotland to the north of Ireland,
taking meetings in many places; and on the 16th of ninth month, got well home,
after a long absence: thanks to the mercy of an holy all gracious Providence,
who lives and reigns for ever!
Favour and mercy have been extended to me through this journey;
for which may a fresh dedication of soul and spirit to the
Lord`'s service attend me to the latest period of my life.

1769, Third month 15th.--Indisposed by a cold and rheumatic pain;
but by applying some simple things found relief,
which I look upon as a favour from heaven;
for any abatement of pain and misery cannot be obtained but by the mediation
and interposition of that which is superior to the disorders of nature;
and this is in the administration of the mercy of our God,
who has endued one part of the creation (plants, medicines,
etc.,) with virtue to counteract that which is suffered to distress mankind, as pain,
sickness, etc,: therefore the Lord our God is still merciful, long-suffering,
and abundant in goodness and truth.

16th, 17th, and 18th.--Still at home and rather better:
had several of my friends to call on me: read several experiences,
all I hope tending to profit.
Felt some painful conflict from the counteracting of a
spirit that has worked its own downfall by rebellion,
and has lain sore on me at times for discharging myself with honesty and integrity;
I have thought it was permitted in the wisdom and mercy of the Lord my God,
to bring me more and more to lean on him, the eternal Rock of strength;
that His presence and power may be my rock, refuge, and stay,
in every strait and difficulty.

19th.--I was at meeting, in which I felt quietude,
and in the conclusion some little matter was impressed on my mind as a caution to
drop with respect to associating with the spirit and temper of the world;
and I had to show how contrary it is to Christ`'s doctrine,
who said,--"`If ye were of the world, the world would love its own,
but because I have chosen you out of the world, therefore the world hateth you.`"
Those therefore that are joined to the spirit of the world, cannot be disciples of Jesus;
whose kingdom is not of this world.

Fourth month 2nd.-First-day, was at both meetings; the forenoon meeting was dull, large,
and heavy, on account of the inattention of many barren professors.
In the latter part I had a testimony to bear against double-mindedness,--the
iniquity of it in religious matters being very apparent to my mind;
even amongst men in civil affairs it was very deformed and mis-shapen.
Hypocrisy and deceit are inconsistent with the nature of religion and virtue;
no appearance of sanctity should shelter wrong actions,
as the nature of the crime was displayed in the
character of Ananias and his wife Sapphira,
who out of appearance and show sold their land,
but retained some of the price for sinister views, which was not unknown to the apostle,
nor to that glorious Power they thought in part to serve,
and for their double-mindedness they lost their lives;
as many now do their spiritual lives, who cloak themselves with hypocrisy and deceit.

30th.--First-day; both meetings very full, not much said by way of testimony:
the unsealing of the fountain is only in the will of Him, who is the Life,
Light and strength, and when He is pleased His servants should be silent;
may they ever be so!

Sixth month 6th.--Went to Kinsale to be at an appointed
meeting for Sarah Taylor and Alice Rigg,
from England, which was pretty large and the people sober,
considering the youth that were present,
who were unacquainted with the nature of the cross of Christ,
and very restless in their own places of worship.
On the whole things were well, and I trust the Great name was glorified.
In the afternoon I was at the funeral of A. F. with the above Friends;
where was a great concourse of people,
who behaved rudely and indecently in endeavouring to
get into the grave-yard before the proper time:
the testimony of Truth went forth in demonstration and power.
This man A. F., was well gifted, well-accoutred,
and a serviceable man in his younger days;
but by being made too much use of by Friends in the several offices of the church,
he took too much upon him, became rather exalted, and did not abide enough in the lowly,
self-denying life of Truth; by which his spirit became too sufficient of himself,
and his sufficiency was not enough of God and the Spirit of His Son.
The fall of man is by little and little, not all at once;
his departure is established as he forgets the rock from whence he was hewn,
and the hole of the pit from whence he was digged; wrong is substituted for right,
and error for truth; a lording spirit prevails,
and so the poor creature falls into delusion, even to believe a lie!
May the harms of others be the warning of us, as a people who profess godliness;
that we may by standing close and low, as in the bottom of Jordan,
be kept alive unto the Lord God and the Lamb,
bringing up stones of memorial to the praise and salvation of our God; Amen!

A+++.+++ F. was a man of good capacity, good-natured to a large degree,
and was very compliant and obliging,
which made him much beloved by those of others as well as our own Society.
An inclination to gratify a passion which has overthrown many, was his foible;
and though it began by a seeming temperance, yet habit confirmed a love for it,
and so by little and little the passion strengthened as it was gratified,
and became master of the man; which increased so powerfully,
as to weaken and enfeeble his love for God and man.
The good cause he once delighted in, and was an advocate for, he neglected,
and so was bound to his Delilah,
by which he became dim if not totally blind with
respect to spiritual sight and discerning;
thus he lost his place in the mystical body,
and became a fruitless branch in the Lord`'s vineyard!
May the sight and sense of such objects as this arouse us to vigilance and diligence,
that in the end we may be blessed with a mansion in the realms of light and immortality!

Seventh month 23rd.--This afternoon the prospect of a former opening affected my mind,
accompanied by these words: "`No man having put his hand to the plough, and looking back,
is fit for the kingdom.`"
My heart, I hope, is not haughty, nor mine eyes lofty;
I think I am willing to be anything or to do anything,
when I am truly sensible it is required, and that I feel strength for it.
May all fruit be fully ripe before it be plucked, or handed forth to others!
This prospect has often appeared to me within these ten years past,
and I hope I may be enabled to say,--"`Not my will, but thine be done!`"

Eighth month 16th.--This day, poor and low in spirit;
the view of distant labour and exercise is affecting, but I hope to be resigned,
even to death.

Ninth month 21st.--Went to Limerick, and was next day at a meeting for worship,
which preceded their meeting for business.
The queries were answered when men and women Friends were present;
and they were spoken to in the openings of Truth,
and the advantages and disadvantages pointed out
attending faithfulness and unfaithfulness,
consistency and inconsistency: on the whole it was to satisfaction.

23rd, 24th and 25th.--I attended the quarterly meeting there:
the meetings for worship were dull and heavy,
on account of the languid state of many in profession amongst us;--the carnal security,
the ease, the formality of some, were hurtful to the youth,
and destructive to the real religious advancement of the soul in righteousness and truth;
many close things were spoken in the tenderness of love,
and the meeting for discipline was I hope to edification.

Stayed in Limerick until the 3rd of the tenth month,
visiting the families of Friends by appointment of the quarterly meeting.
Afterwards I visited Friends of Ross meeting,
and though they are poor and lean every way, the visit was much to my satisfaction:
we were many times filled with the virtue of Truth,
in which we ministered to the states we visited; many were reached, and several roused,
which I trust will prove effectual to some to be what they should be:
we were deeply baptized on their account.
I am firmly of opinion it will stand against them in the great day of account,
if they turn not to an amendment of life and to Him who died for them and all mankind.
I had much peace in conforming to this secret impulse and inward draft of duty,
and this day`'s work crowned I thought the whole,--
blessed be the name of Israel`'s King forever,
who replenishes,
sustains and rewards all those who are faithful
to the law and commandment revealed in the heart.
Returned home with my dear wife, the 3rd and 4th of tenth month,
and found my family and affairs as much to my satisfaction as I could expect,
which I always do when abroad in the service of the Great
Master,--to whom be praise and adoration ascribed for ever.

Twelfth month 23rd.--Attended our meeting for ministers and elders:
things stirred in the life to our mutual comfort,
and testimony was borne to the mercy and goodness of a gracious God;
who sometimes by his love works on us, as on Aaron`'s rod, by making it bud,
blossom and bring forth ripe almonds in one night, though before in a state of dryness;
and it is the Divine Power still, that quickens and makes us alive in the church,
by which we live unto God.
As He has chosen us for His work,
let us not entangle ourselves with the inordinate cares of this life, that we may,
as good soldiers, please Him the holy Captain.

26th.--If we would but keep little and low enough, we should be a favoured people,
for the Lord delights in the humble and low in heart.
He does not reveal himself to the high, the wise, and the prudent of this world;
for the apostle says not many of these are called;
"`for God has chosen the weak things of the world to confound the wise,
and things that are not, to bring to naught things that are,
that no flesh may glory in His presence:`"--and the reason to me is very plain,
because the wise, the strong and the prudent,
depending much on their own parts and powers, are not willing to be chosen,
and so remain contentedly in a state of unrenewed nature,
without having it subdued and brought under by the power of grace.

29th.--The meeting at Cork was rather a dull one; though I had some openings,
and some little access in spirit to that holy table,
which is always richly furnished for all ranks and classes of the people,
of whatsoever constitutions they may be, if but real children,
born of the incorruptible Seed, and growing in it from stature to stature.

1770, Second month 5th.--This day about domestic affairs,
in which I had some intervals of reflection to look
towards an inheritance amongst the children of light;
some glimpses of a very important nature, in which I trust I stand resigned:
read some instructive experiences in the evening.

Third month 14th and 15th.--These two days engaged about my domestic concerns;
in which I was much taken up, preparing to leave home with ease and propriety.
Weight and depression are very much my attendants from a variety of considerations:
at times I am easy and thankful,
and sometimes I hope living closer to the Life that quickens and makes alive:
but harassing cares retard,
and yet again I am sometimes sensible that business within bounds,
is healthful both for body and mind.
May the strength of sacred aid and instruction be revealed,
to support and sustain through the ups and downs I am to pass through in this low world,
that at last I may centre in peace and safety in a glorious hereafter!

20th.--This day we appointed a meeting for our youth,
and had several minutes read to them,
in which service we felt strength and instruction renewed;
for which I trust we shall return the praise where due.
In the evening we began the family visit, and were favoured with a fresh seal,
that the Lord our God owns this service in His church and amongst His people.
We went forward in this laborious work till the 31st,
in which the mercy and sustaining help of a gracious Helper were witnessed,
to the mutual refreshment of those who were engaged in this work;
in several places manifest proofs were given that it had a good effect.
O! that it may not be like the morning cloud and early dew, that quickly pass away!
It was a time of renewing of light and strength; some were harnessed into this service,
though young in the work, which I trust will bind them to the law and testimony,
not to put it off I Fourth month 1st.--Attended our meetings today,
in which I was concerned in testimony:
the afternoon meeting was the most satisfactory both as to life and testimony;
the early beginners in the work of purification were encouraged,
even those whose warfare was but just beginning, and their fuel for the inward fire,
green and strong, the action of which frequently gives pain:
but as this day of trial is endured, it works the great work of humiliation,
and then sanctification,
which leads to such a state of subordination and
resignation as fits for the image and stamp of purity.
Returned home in the evening easy and thankful in spirit.

2nd.--I feel great sinking and depression of spirit,
under the exercise that daily attends me, in looking towards a distant land:
the season seems not far off, that I must move, in acquainting my friends thereof.
May saving help animate to give all up, and may it attend my progress,
that at last I may have the answer of "`Well done!`"
I often look at my weakness for so great a work,
but may obedience be willingly kept pace with,
that my great Lord may be followed in His leadings, even into suffering, into baptism,
yea, into death! that life and immortality may be attained in the end.

12th.--This day engaged about my domestic affairs, which I attended to with diligence,
in preparing to leave them;
as it is the indispensable duty of all to order their families
in such a manner as to be the better capable of leaving them,
when the word of command comes with force and authority.

15th.--At an adjournment of our men`'s meeting,
I informed Friends of the concern I had long felt,
to visit some of the meetings of Friends in North America;
which concern affected the minds of divers, and indeed very much tendered my own,
from the weight and importance of the engagement,
which has attended me for so long a time, both by day and by night,
in sickness and in health.
It was taken into consideration, and an appointment made to draw up a certificate.

23rd.--Our men`'s meeting was held this day,
where my certificate was signed for my visit to the continent of America;
in which meeting I had to mention my feelings respecting the same in much brokenness,
with an exhortation to my friends to endeavour each to
discharge themselves faithfully in the Lord`'s service,
and to endeavour to keep a conscience void of offence towards God and man;
that so a crown of life may be their portion at last!

Fifth month 5th.--At Dublin;
our meeting of ministers and elders was held as usual
previous to the National half-year`'s meeting:
the breaking of bread was mercifully known,
and the living a little enriched by Divine Goodness +++[+++and encouraged]
to hold on their way.
In this meeting I laid my concern before Friends
respecting my intention of visiting America,
in which sympathy seemed to circulate; an appointment was made to draw up a certificate.
My mind was much affected in feeling the weight
of this exercise and laying it before Friends;
however, I felt much ease in my friends having the concern laid before them.

6th, 7th, 8th, and 9th.--The meetings were held in course;
the weighty and helping sense of Truth was mercifully witnessed to circulate amongst us,
the living were comforted, and the forgetful reminded of their duty;
on the whole it was a blessed helping season to some of the feeble-minded,
whose faith was but low and their spring almost dried up.

Seventh month 14th.--This day had a most sweet and comfortable opportunity
in company with our dear English Friends Jane Crossfield and Jane Routh,
tending to great encouragement in my present prospect:
we were mercifully sustained and replenished with a shower of Divine love,
in which it may be truly said our affections were raised to things above,
which are enduring and exalted.
May every favour and blessing received establish our
faith in that Power which is stronger than death!

31st.--In much pain from a rheumatic disorder:--the beauties of creation,
prosperity and even social intercourse are shaded with
clouds of darkness in the dominion of pain of body;
a quickness of feeling remote from patience is apt to attend,
in which seasons we are always less amiable to
those we have heretofore been very dear to;
may every dispensation be blessed to us, that it may work for good,
and point to the path which leads to holiness;
that by pursuing it through every trial and besetment,
we may be established for ever in eternal life and light!

Eighth month 1st, 2nd, 3rd, and 4th.--These four days in a state of conflict, restless,
and uneasy; rather freer from pain than the week before:
a very little thing disorders this machine:
what poor beings mortals are when grieved by sickness and pain;
it eminently shows where our dependence ought to be,
and that nothing more distinguishingly relieves than
placing our trust on the Lord`'s arm of everlasting help,
with whom there is health for sickness, light for darkness,
and the breaking in of peaceful serenity for the most annoying affliction.

20th.--Preparing to go on board ship; felt tranquil in spirit,
and quite easy with respect to all things in nature; it is the work of grace;
nothing short of its virtue could reduce to submission and subjection;
and cause an entire relinquishing of things temporal,
to follow after things that are eternal.
The work is the Lord`'s and the praise and glory of all be ascribed to his great Name;
who is worthy to be renowned by every generation of man, for His mercies endure for ever!

[.embedded-content-document.letter]
--

[.letter-heading]
To Robert Dudley

[.signed-section-context-open]
Glanmire, 20th of Eighth month, 1770.

[.salutation]
Dear Friend,

I had thy letter in answer to mine,
which gave me pleasure in various respects;
thy commemoration of the favours and blessings
of heaven dispensed to thee in thy infant state,
when like Jacob thou went from thy Father`'s house, only with thy staff;
and now thou art become two bands, by the shedding of the blessings on thy head, which,
as lived under, will increase and multiply still to greater degrees of dominion.

Be attentive therefore, dear friend, to the motion of Light;
suffer thyself to be girded by the holy girdle,
and thy back will be strengthened for work,
thy standing will be pronounced sure by thy stability,
and thy head will be covered in the day of battle.
I am not insensible how men are attacked by the grand enemy:
if he fails when he have them in one position, he attempts to draw them from it,
to another, with a view to better success.
If the banner be over us,
in the limitation assigned by the Guardian Angel of preservation, let us keep under it,
and we shall be secure; the enemy will not be able to prevail against us,
when we have the glorious fence of the Lord`'s appointment.

There are seasons when the affectionate part is up in man,
and proposes things agreeable to nature in ourselves, that we are ready to comply with:
this sometimes makes the way intricate to ourselves;
for when we bring it to the standard to be tried, it is deficient in weight and purity,
and will not pass the trial before the Judge.
I have missed in this respect; therefore I drop the caution to my friend,
to beware of giving expectation,
before it is tried in the balance of the sanctuary,--
kings`' children should always preserve their dignity,
by taking heed how they mix among the people,
and their associations and alliance ought to be with the royal lineage;
in this the King of kings is honoured and our own dignity preserved.
I do not mean this with respect to thy present depending affair in England;
I mean with respect to others, whom we converse with and are sometimes amongst,
both male and female, though it may hold good in both.

There are many more talkers of the Truth, than walkers in it, whose mouth flatters,
and whose tongues are their own, and ought to be stopped:
though they appear to be something in word and show,
when they come into their ranks and appear among the disciplined army,
they are not noticed or sent forth against the Goliaths of the day;
it is only those who are anointed and appointed, armed and accoutred,
that can face the battle.

May we, dear friend, dwell with the consuming virtue of the Spirit;
that we may still be refined.
I would just say, with respect to the present depending affair,
do not be too hasty or precipitate; weigh it,--and ever remember, that he that believes,
makes not haste; there are many things to be looked at,--thy place, thy friend`'s place:
things with a fair face of prospect, may be shaded with a gloom;
sweet things in enjoyment, may change to bitter, like the book we read of,
that was in the mouth sweet (the palate) but was in the belly, bitter.

I would not cast anything before thee,
to embarrass or overwhelm,---but simply speak my feelings.
Relinquishing for the cause, in our affections, enriches often,
in a spiritual and temporal sense, and it is often tenfold restored.
It was said in the recapitulation of the many blessings dispensed to David,
after showing him what he was, "`and if this had not been enough,
I would have done much more.`"
This was done when he was taken off his watch,
and suffered his affections to sport with a beauteous object, which in the end,
made him flee before his enemy.
This thou may think not similar to thy present state,--yet it points to obedience,
the dedication and consecration that ought to attend a being +++[+++who is]
raised to eminence by the interposition of a Supreme Power,
in order to show forth His praise in him.

The satisfaction resulting from thy letter on this subject, was great, because,
with respect to a removal, in looking at it, I think thou tells me,
thou never saw light shine upon it; this,
satisfaction arises from my being of the same sentiment, and one in judgment,
when most capable of judging, and to feel for myself and my friends.
Let this affair therefore, be hewn and squared in the mount, before it is adopted;
and let there be no sound of an artificial tool in bringing it about,
that the substituting a member from one part of the body to another,
may be the Lord`'s work,
and then it will be useful and to the comfort and edification of the body, the church,
I sympathize with thee and thy friend: I love you both in the Truth; and my desire is,
that you may be conducted in wisdom in bringing it forward,
or in finally letting it drop; and for every sacrifice thus made,
it will be amply made up by the replacing of one in its stead,
in which your acceptance will stand, your faith be confirmed,
and your righteousness be proved, as was faithful Abraham`'s. I am now, dear friend,
on the eve of my departure.
I stole this little season from hurry to converse with thee,
and tell thee how I have felt: my things are all gone on board,
and on the morrow I expect to embark.
A letter from John Oxley informs me, his brother expected to get clear of the land,
about the 5th instant, by a letter received,
so that we may have some expectation to meet; if at all soon, in the western world.
A correspondence with thee will be agreeable,
as a little intelligence in a strange land is very pleasing to pilgrims.
I should have been pleased to hear what thou intends,
and how thou feels with respect to going over the water soon.
Keep thy integrity, and put thyself in seeking +++[+++keeping]
of a faithful Creator, that sleeps not by day, nor slumbers by night:
consider thyself at his disposal,--not man`'s, of any kind, neither R. Dudley,
nor any other man, that is but flesh, consequently frail.

Farewell!--may wisdom and knowledge be the stability of thy time whilst on earth;
and may the fear of the Lord prove thy glory,--in which desire,
I remain thy truly loving friend.

[.signed-section-signature]
Samuel Neale.

--
