== Chapter IX.

[.chapter-synopsis]
* He sails for America eighth month, 1770
* Landed tenth month near Philadelphia
* Accompanies Joseph Oxley
* Travels extensively amongst Friends in the Southern States
* Returns to Philadelphia
* Attends the yearly meeting there, 1771.

[.offset]
+++[+++Samuel Neale sailed from Cork about the 22nd of eighth month, 1770;
but his intended companion Joseph Oxley sailed from the
Thames towards the end of the seventh month,
and reached New York about the 22nd of ninth month,
about a month before Samuel Neale arrived near Philadelphia.--See Joseph Oxley`'s Journal,
[.book-title]#Friends`' Library#, vol. v.+++]+++

I felt the incomes of Divine love sweetly sustaining my mind;
my heart was humbled in a sense of the mercies and goodness of God daily renewed;
and I felt ability to beg for preservation and stability in
the arduous work I am preparing to enter upon.
The Lord grant that there may be an entire dedication of heart,
so as to be capable to stand in my place, and whatever may be cast up for me to do,
that I may do it to the honour of His great Name.
Composure and trust in the Lord`'s arm of power, are my attendants,
for which I bless his name.

+++[+++He again writes.]--Composed in mind, from a sense of inward peace,
and the unity of my brethren whom I have left behind;
this is a staff to lean upon in the midst of trials, and, next to Divine favour,
one of the greatest blessings.
+++[+++At another time:]--Was rather low from various considerations,--the
weight of the work and the inexperience of the instrument.
I trust I shall be preserved little and low.

[.offset]
+++[+++It appears that he passed much of his time, while on ship-board,
in reading the Scriptures, and the writings of valuable Friends,
to his comfort and edification.

Near the conclusion of the voyage,
he felt an inclination to have a religious meeting with the ship`'s company, but,
by giving way to discouraging thoughts, he let the opportunity slip:
which he had cause to regret, and remarked:
"`I hope experience will teach greater degrees of obedience.`"

When they had safely come near land, he wrote:]
I trust I am thankful for the Lord`'s mercies and favours daily dispensed,
and can say in humility, I have not murmured since my coming on board;
but have been mercifully preserved in a sense of His goodness.
I hope for this blessing to be continued, that according to ability,
I may labour in the vineyard,
and work the works of Him who has called me with his high and holy calling.

[.offset]
+++[+++He landed the 18th of tenth month, 1770, at Newcastle, near Philadelphia.]

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend.^
footnote:[Addressed probably to his friend Richard Shackleton.]

[.signed-section-context-open]
Philadelphia, 24th tenth month, 1770;

[.salutation]
Dear Friend,

Having opportunity to send a few
lines as a token of my remembrance of thee,
I embrace it.
After a passage of eight weeks, from my own house to making of land on this continent,
I safely arrived the 18th instant, and the 20th reached Philadelphia;
met my companion and several Friends on the road, amongst others Samuel Emlen;
it was a pleasing meeting,
after a confinement amongst the ship`'s crew and a number of servants and passengers.
The captain was remarkably kind, and made me a sort of commander in the vessel.
My mind was mercifully sustained,
and I seldom murmured at my lot or the alteration of weather,
though we had a few hard gales.
Sometimes as we ran to the southward it was extremely warm the like I had not before felt.

I have been at four meetings in this city, three on first-day and one week-day meeting,
besides some opportunities in families, the Divine Arm, that separated me from my family,
friends and country, was mercifully revealed to encourage and confirm;
so that my spirit said, good is the Lord,--He is worthy of being followed and obeyed,
for His promises are yea and amen forever!
My companion is bright and living, and has been united to me in the springings of life,
that disperses death and darkness.
I trust, if it be consistent with Divine disposal,
we may be permitted to go together and enjoy each other`'s company in the wilderness,
and amongst the various perils to be encountered in a visit to the churches at this day:
if not, may we be both capable of saying, "`Thy will be done.`"
Friends here are very numerous, seem solid and weighty, have an ear open to hear,
which is a great help to those who are at times concerned to speak.
When we have more experience of the state of things by baptisms,
we can be better qualified to judge.
My old friend and companion +++[+++William Brown]
seemed greatly pleased to see me, received me with much nearness and affection,
and I was pleased to see him look so well,
for to me he seemed to look as well as when he was in L`'eland, and almost as young.
John Churchman I hear is pretty well, and Susannah Lightfoot; Joseph White but poorly.
I lodge at John Pemberton`'s, who seems to me a very valuable Friend.
There sailed a Friend for Europe a few days before my arrival, his name Robert Willis,
on a religious visit; and two women propose to set forward next spring,
Sarah Morris of this city, and Elizabeth Smith, valuable,
serviceable members of Society;--such is that love, which draws hither and thither,
which is stronger than death.

My dear friends will not I hope forget me, when it is well with them,
I have felt some of them in much nearness, when on the mighty waters;
may nothing ever be able to burst the bond of
fellowship formed by the creating virtue of Truth;
that when nature fails, and all outward affinity is dissolved,
we may rest for ever in the mansions of light and rest.
I have often thought few,
very few in such weakness were ever sent on such an errand as myself;
but yet as those are filled with the life that brings immortality,
and they keep in their own proper spheres,
their reward will be proportioned to their faithfulness,
which will give quietness and assurance forever; this is what I earnestly aim at,
and hope to follow after; and thus,
whether I ever be united to my Friends in Ireland again, or lay down the body here,
it may be well.

Farewell, beloved friend; salute from me thy dear wife and father,
whom I much love in the Truth;
I trust you will remember the state of the Society in poor Ireland,
and move backwards and forwards where instrumental help is wanting.
Many have turned their back as in the day of battle,--many have
fallen short of what they essayed to pursue in the day of espousals,
and have fallen into the grave of the riches of this world,
and some into the corruptions and vices thereof;
and some again have fallen as upon Mount Gilboa, the destructive barren waste;
where even at this day the beauty of Israel is slain and destroyed!
Gird up thy loins, dear friend; break forth on the right hand and left;
and remember the crown is at the end of the race.

My love salutes thy children,
I ardently desire they may follow the footsteps of the flock;
and then they will be led beside the Shepherd`'s tent.

I remain in true nearness and cordial affection, thy loving friend in truth,

[.signed-section-signature]
Samuel Neale.

--

+++[+++It appears that he paid a very extensive and
acceptable visit to Friends in North America;
in which he was diligently engaged till the time of his departure,
the 10th of eighth month, 1772.
Many instructive remarks are contained in his account of this journey and visit;
and by the following extracts,
it is evident that he was favoured with best help in the course of his labours,
and felt the sweet incomes of peace on his return home.]

[.small-break]
'''

1770, Tenth month 21st.--Philadelphia, first-day, I was at three meetings:
the morning meeting was a season of much refreshment to my mind;
the afternoon meeting was solid;
and that in the evening was attended with impressions of Divine favour, which,
raised thankfulness in my heart: the Lord our God is gracious and merciful.

1771, First month 15th.--Set out for Bush River, +++[+++South Carolina]
accompanied by Samuel Millhouse, J. T., and W. L.; my companion, +++[+++Joseph Oxley]
did not go with us, being prevented by a kick from his horse, which bruised him very much.
It rained all day very hard; we stopped to eat a little food in the woods,
and took off our coats to cover our saddles while the horses were feeding,
we could not get a house to put them in.
We rode until night came on, and lost our way in the woods;
with some difficulty we got to a man`'s house,
who gave us lodging in the best manner he could.

He had a very large family, who did with little clothing.
We had our own provision, he let us have one bed,
and gave fodder for the rest to lie on the floor.
The 16th we set forward, swam our horses over two creeks,
and crossed one large ferry called Broad River, and so got well to the widow Sliddom`'s,
in all about eighty miles.
The 17th, to a meeting at Bush River,
in which was delivered very close home doctrine to several states present.
The 20th, being first-day, the meeting was very large,
the house not being capable to contain near all the people: we sat a long time silent,
my mind was clothed with poverty.
I was sensible of a strong desire in the people for words,
and this seemed to be denied them,
in which state the Lord was pleased to bring my mind into contentment.
When I gave up my will to His, and resigned my mind to travail on in silence.
He was pleased sweetly to compose my spirit, to replenish it with His love,
and gave ability to answer the service of the meeting.
Several were refreshed, some were encouraged, the negligent stirred up,
and I trust it was a season when impressions of
holy Goodness were felt on the minds of several.
O! that it may not be as water spilt upon a stone,
but as bread cast upon the waters to be found after many days!

On the 21st we set forward; it was a very wet day,
my horse fell under me and bruised my thigh badly, and indeed,
it was a mercy it was not broken: we got well over some bad waters;
all which I acknowledge as a great favour, and desire to be humbly thankful for,
with the many other mercies daily received.
The 23rd, I joined my companion, and had a good encouraging meeting,
which greatly refreshed my mind and the minds of
several honest travellers who were there,
for which favour the great Name was praised in the authority of Truth,
and through the help of the Holy Spirit: renowned for ever be the name of our God!
It is the Lord`'s mercy and goodness, who strengthens us for the labour of the day,
and sustains by His powerful Word of Life,
without whom there is neither bread nor clothing in a temporal or spiritual sense;
may He have the praise of all His works, who is enduringly good and glorious,
and whose dominion is from sea to sea, even unto the ends of the earth.
Amen for ever!

Second month 6th.--Was at Dunn`'s Creek meeting, in which, though small,
we were mercifully helped to worship, and to bear testimony to the goodness of God;
the state of the meeting, I believe, was opened in the spring of life,
and though some seemed snared one way and some another,
some in the cares of the world and the corruptions thereof;
yet encouragement was given to a state to follow the Lord closely,
to seek Him while He may be found, and to ask that they may receive:
it was a season of love and good-will to a remnant present.
We returned to T. H.`'s,
and I felt no freedom to propose a sitting in his family or have a meeting in the town,
I believe he and his family to be in imminent danger from his neglect of duty to his God,
and that his temporal affairs are the worse for his forgetfulness:
he is a good-natured man and behaved very friendly to us, and his wife also,
but I pitied them much on account of their situation.

Second month 11th.--I had a very tendering season iii a Friend`'s family,
in the love of our Lord Jesus Christ;
admittance was vouchsafed to the Lord`'s heavenly table in supplication,
wherein many of my friends and relations were brought very near in the spring of life;
it was a season of Divine favour to our souls, in which we rejoiced,
and praised the Lord`'s holy Name and Power, who is glorious in all His ways.
Afterwards set forward and went about sixteen miles, and lodged in the woods:
the fore part of the night was fair, but the latter part very wet,
it raining for about four hours, and then cleared: we had a good fire,
were very contented, dried ourselves, and set forward;
through the kindness and goodness of our Great Master, we did not suffer much by the wet,
though at last we could not get a place of covering to stretch ourselves,
but were forced to stand in the wet till it cleared; we then rode ten hours,
and some of the way very hard.

23rd.--We attended the quarterly meeting at Piney-woods, which was exceedingly large,
the house being scarcely able to hold Friends: we were both silent in this meeting,
which seemed a disappointment; the meeting for discipline was very weak,
in which I was led to make several remarks to my own ease;
but they seemed very weak in the discipline,
and not in all respects in such order as could be
desired with respect to their mode and manner.
In the evening we had an opportunity in the family, in which we travailed in silence.

24th.--First-day, we had a very large meeting, in which I had to travail in silence,
my companion expressed a little.
In this quarter there are many negroes, and their being so numerous amongst Friends, is,
I believe, a great loss to their families,
by the children`'s being trained up in pride and idleness, and a superiority over them;
this hinders a real growth in humility,
and obstructs the good work in the essence of true religion:
coldness aird lukewarmness in the performance of duties
important to the salvation of the soul seem very prevalent,
which,
that the professors of the blessed and spotless Truth may witness a being turned from,
is my very earnest and fervent petition.

+++[+++In a letter to his wife, dated 1st of Third month, 1771, he writes:]
I have rode already upwards of 1700 miles, being favoured with a fine young horse,
and lay out five nights in the woods.
I have breakfasted, dined,
and supped in the woods as contentedly as if I were in a palace,
and though I have had to partake of fare that in
Ireland would hardly go down with any servants,
yet the contentedness of the mind made it a feast.

+++[+++And in another letter about the same date, he writes:]
I find nature may be brought to submit to anything as to meanness and severity,
if in Divine direction, for there is a support adequate to the toil:
so that we may say with one formerly, "`by thee I will run through a troop,
and by thee I will leap over a wall.`"

Third month 3rd.--Had a pretty open meeting at Western Branch, +++[+++Virginia]
where the doctrine of Truth was set forth, and it ended well,
tenderness being felt by several minds, though things were very closely spoken to.
There is a deficiency amongst Friends in this country respecting the plain language;
calling the days of the week and months in the vulgar and common manner is too customary,
and to their loss, as unfaithfulness in small things begets barrenness and rust,
and insensibility creeps over the mind.

15th.--We were at Wainoak meeting, which seemed very low in the beginning,
but towards the latter end Truth favoured,
and the testimony thereof was exalted above transgressors,
for which my mind was thankful, feeling very low on going to this meeting;
but was raised above the fear of man by the operation and
spreading of the holy hidden Life of our Lord Jesus Christ,
to whom be dominion and praise ascribed both now and for evermore!
The 20th, had a large meeting at Cedar Creek,
where were five justices and a Baptist preacher lately enlarged from jail;
the strength +++[+++of the Divine Power]
displayed in this meeting was greatly to my relief and admiration,
finding that sufficient for the trials of the
day is the help communicated for such services,
even amongst those of small degree!

23rd.--Set forward for Stafford county, and the 24th were at a large meeting,
which was a season of close labour and exercise of spirit,
but it concluded to the relief of my mind; several close remarks were dropped,
both to Friends and other people,
respecting their duty to their great Lord and merciful Creator,
In the evening amongst Friends who came to our lodging, had a lively opportunity,
showing the advantage of zeal for the Lord in their day and generation,
and not to suffer emulation or strife to enter,
but to keep the unity of the Spirit in the bond of peace,
and to let nothing of worldly distinction be amongst them,
but to let the heavenly Life`'s operating in them be the distinction,
according to the proportions they feel,
and in this to move in their services in the church; then,
the great Name will be honoured, and the members increase in strength and stature,
by being replenished Math those sacred streams that make glad the heritage of our God.

Fourth month 15th.--Set forward for West Nottingham, a pretty large meeting,
in which we had close remarks to make,
and our spirits were pretty well filled with a testimony for Truth.
Dear John Churchman was at this meeting;
he seemed very tender and sympathizing and fatherly in his conduct.
We went home with this honourable elder and father in the church,
and next morning attended the meeting at East Nottingham, which was very large,
and a good open meeting it proved.
The demonstration and authority of gospel ministry attended,
and the openings of Divine virtue were mercifully imparted,
in which we felt the sacred cement of love and life;
this humbled my mind under a sense of the Lord`'s goodness,
which is near in the needful time, and present when help is wanting,
as we lean upon and look up to His throne of love and favour.

20th.--Set forward for Thomas Lightfoot`'s,
and met my dear friend Susannah +++[+++formerly Hatton]
at home, who received us in a near and affectionate manner.
Next day, which was first-day, were at their meeting,
where Divine help was administered beyond my expectation,
and a very sharp close testimony I was given to bear in this meeting,
which by accounts was as though the state of it were +++[+++outwardly]
known; for which may we reverence the great and glorious, Name of our God,
who sometimes strengthens His poor dependent children sufficiently unto the day!
The 22nd, set forward for Philadelphia, accompanied by Thomas Lightfoot and spouse,
and were kindly entertained at our worthy friend John Pemberton`'s.

Fifth month 6th.--At the quarterly meeting in Philadelphia;
the meeting for business was held after a sitting in silence,
to prepare the spirits of Friends to act in the discipline.
I had something to say in this meeting, but left it uneasy;
because (through a fear of prolonging the meeting beyond the
proper time,) I omitted part of the matter that was before me.
There is great need of care in this respect,
as well as not to exceed the bounds which Truth prescribes.
May Divine goodness open our understandings,
and more and more replenish our minds with that faith, which overcomes slavish fear,
and gives the victory.
9th.--Was at a marriage, where I was silent,
having nothing to offer, to which I hope I was resigned,
and thankful for this and every dispensation allotted in true wisdom.

My companion having a concern for New England,
and I towards the eastern shore of Maryland, we laid our views before some solid Friends,
who approved of our manner of proceeding,
and concurred in sentiment respecting our parting;
so we took leave in much nearness of love and affection, and he set off towards New York,
whilst I was accompanied by John Pemberton to Wilmington.
The 20th, we had a public meeting,
in which the beauty and glory of Truth were manifested for our consolation,
strength and relief; after which the meeting for discipline came on,
in which help was mercifully revealed to carry on the business,
many Friends being concerned to speak to edification and comfort, viz., Joseph White,
who was much favoured this day, Robert Valentine, David Bourn, etc.;
and my mind was much relieved by the little labour I had amongst my friends.
The 22nd, Friends met at nine o`'clock to finish the business,
which was gone through in love and harmony,
and several good remarks were dropped in the wisdom and openings of Truth:
the meeting held fresh and green mostly for six hours;
and Friends parted in the tenderings of the love of God.
Accompanied by my friend David Ferris,
we took boat and had a prosperous passage to Chester,
where we attended the week-day meeting, and were favoured in our little sitting together,
and helped to return the praise of all favours dispensed,
to that holy Hand which helps the weak and truly dependent children.

Sixth month 13th.--Was at Centre and Kennet monthly meeting,
where I was furnished with aid beyond my expectation,
having to point out that which made us qualified members of the church:--and
as we keep our sap and greenness we act to the honour of the Great Master;
when we lose that, we become lifeless and barren, and are cast forth as dry branches:
warned a state present to beware of lying and hypocrisy, in the words of the prophet,
"`Ephraim compasseth me about with lies,
and the house of Israel with deceit:`" I was favoured
with openness and strength to discharge myself,
as also in the meeting for discipline, for which I was humbly thankful.

17th.--Went to Pilesgrove meeting, which was a season of favour;
a state was spoken to who had known good things,
but were in danger of falling away:---the difficulty of
retrieving a lost state was hinted at;
likewise of sinning against the Holy Ghost,
not to be forgiven in this world nor in the world to come;--on
the light and power of conviction through Christ,
and on being made partakers of the powers of the world to come
by the enjoyment of a heavenly and powerful gift,
which it is most dangerous to sin against, or fall away from,
and very hard to be retrieved.
The apostle says,
it is impossible for such enlightened souls who have been thus favoured,
to be renewed again to repentance;
seeing they crucify to themselves the Son of God afresh, and put Him to open shame.
My mind was favoured afterwards with the renewings of peace and quietness.

28th.--Went to Squancum meeting,--a season of close exercise;
wherein I had to speak of that passage--that Christ Jesus is "`the
Author of eternal salvation to all them that believe;`"--and then to
point out who believe in Him;
even those that received Him,
to them gave He power to become the sons of God,--those that embraced His doctrines,
His Life and Spirit in their hearts, to them gave He power over their sins,
and brought them into a state of righteousness,
and into a belief in Him in the way of His coming;
for many reject Him in the way of His coming, because of the smallness of His appearance.
This was the state of the Jews, the doctors and rabbles formerly,
which made them despise Him, and say, "`Is not this the carpenter`'s son?`"
They expected Him in pomp and greatness, and became so corrupt and hardened,
that they thought not only to slay Jesus Christ,
but those that believed on Him,--as in the example of
Lazarus whom he had raised from the dead;
lest the people should believe, and they lose their name and authority amongst the Jews.
I was led on and helped in the ability that Truth gives,
and several of the people seemed reached; one high professing Baptist said,
she never heard the gospel preached so before amongst the Quakers.
The meeting ended in a good frame, and my spirit was humbled and grateful;
thanks be unto the Lord my God,
for all His favours and mercies dispensed unto me in this journey!

On the 30th, we were at their first-day meeting at Shrewsbury, which was very large;
many raw professors as well as those of other societies were present.
I was led to speak very closely to some states, and very encouragingly to others,
who were concerned to build the wall about the vineyard,
and to support the hedge of discipline against the discouragements of
the Sanballats and Tobiahs of this day and those of their spirit;
that it is necessary for such to descend into the valley,
and there take a view of the ruins, that they may be capable of seeing,
and building for the Lord, with the working utensil in one hand,
and spiritual weapon of defence in the other.
I had also to speak respecting the plain language, the too general departure therefrom,
and the insensibility that creeps upon individuals by such unfaithfulness.
I was helped beyond my expectation, and the meeting ended to satisfaction;
praised be the great name of the Lord my God, who is the strength of striplings,
and who qualifies for the services he requires from his children and people.
Came to our quarters at E. W.`'s,
and there had an evening sitting with his family
and Friends to our mutual renewing of strength,
and had to speak respecting family worship and family sittings,
the benefit I have heretofore found from such opportunities,
and the qualification that at times springs therefrom,
which enables to drop suitable instruction to our offspring and those under our care.

Seventh month 2nd.--We crossed the ferry at Amboy, and got to Joseph Shotwell`'s,
where the next day we had a meeting in his family, a good, open, living season;
this Friend has a hopeful and promising family, and knows the Truth himself,
which is a blessing to his family.

11th.--We attended the monthly meeting of Kingwood,
in which I had some very close exercising work, but was helped through,
to the relief of my own spirit, and to some comfort to the honest-hearted,
a few of which sort are preserved in most places,
though a large number who dwell too much in
indifference and in a name without the substance,
are scattered all over the Society.
I had to exhort the elders and overseers,
and so left them to their own application and industry in the best sense,
to that which would never fail if properly attended to.

On the 13th, a pretty large meeting at Stonybrook,
where several of the scholars from the college were present and two lawyers:
the authority of Truth was with us, in which we laboured;
priestcraft was closely touched, and the free gospel ministry pointed out.
This meeting ended under a comfortable sense of the help of heavenly ministration,
in which we rejoiced in fear!

14th.--First-day; at Trenton,
both the fore and afternoon meetings were pretty fully crowded;
my mind was very low and poor,
but the good Hand of Divine support aided and enabled us to
discharge our duty in such a manner as procured peace,
and staid my mind in that which is the refuge of the distressed and weary soul;
in which I rejoiced in God my Saviour, and was comforted.

15th.--We were at Bordentown meeting, and lodged at John Sykes`'s; he is in his 90th year,
and his wife in her 87th, and they have lived together sixty-six years;
they are both public Friends,--seem to live like innocent children,
and have their memory and faculties in such a degree of strength and clearness,
that I have not seen or read of the like: they seem full of love,
and are in spiritual greenness now in old age.

16th.--Had a large and laborious meeting at Crosswicks,
in which I had to arraign some of hidden crimes not yet
brought to light;--that I believed Achan was in the camp,
and it could not journey forward prosperously,
until judgment was placed upon transgression: exhorted Friends`' to keep their places,
and not to cover or conceal wrong things, but to support the law and testimony,
and seek the Lord, that they may live and be a living people.
Next day at a meeting at Freehold I had to speak of the two debtors,
one who owed five hundred pence and the other fifty; and as they were both forgiven,
he to whom most was forgiven, showed most love; and where much is forgiven,
there ought to be much love.
Sometimes there is a spirit prevalent,
which censures those to whom much has been forgiven by Him who has power to forgive,
and which thinks they are not fit for their society, saying, "`Stand by thyself,
I am holier than thou:`" this is the leaven of the Pharisees,
of which I warned Friends to beware: it was a good opportunity,
for which I was bowed and thankful in spirit.

18th.--At Upper Springfield.
This evening in a very poor low state, being exceedingly stripped in my mind.
In this solitary situation I walked out into the woods,
where I felt something of the spring of Divine kindness,
which raised a hope that help was near, though seemingly concealed from me.

19th.--Was at Mansfield; where was a very large meeting.
Friends from various quarters giving their company:
in this meeting I was helped beyond my expectation; the gospel spring.
rising and spreading more than for several meetings past,
and my spirit reverenced the Power that withdrew, and afterwards raised into life.

20th.--We were at the Neck meeting; many Friends coming, the house would not hold them,
so we had the meeting in the woods under the trees.
We laboured amongst them in a good degree of strength and authority; several were tender,
and it was a sweet visitation to several present.
I spoke to one or two young people after the meeting in private, who were very tender,
and did not resist the counsel that I had to give,
but seemed open to receive it: went home with Abner Woolman,
with whom and his family we had a sweet sitting
in the spreading of Divine and encouraging love.

22nd.--'`Was at a large meeting at Old Springfield,
where I had a laborious exercise to pass through in speaking to several states present,
and against the leaven of riches,--"`not to put confidence in it or make
gold our hope I for it is an iniquity to be punished by the Judge,`" etc.

23rd.--I was at Rancocus meeting; it was rather a low time,
but I laboured in it to some increase of ease and freedom of spirit.
Here I saw John Woolman for the first time; I take him to be a sweet,
clean-spirited Friend;
his unity with the true Seed may be felt by his
savoury conversation and pious self-denying life.

24th.--Went to Monthly meeting, where very many Friends assembled from different meetings.
I was very low going to this meeting, but ere I had sat long,
the Word of life quickened my mind, and a favourable season it proved;
in which the testimony +++[+++of Truth]
was exalted in the authority thereof, and I had to speak comfortably to several states,
to my ease and comfort.
I was much afraid of this meeting,
as they have had great privileges by favoured instruments.
Here lived Abraham Farrington,
and to this meeting belongs that worthy exemplary Friend John Woolman,
whose life and conversation shine in Christian purity.

His concern is to lead a life of self-denial; pomp and splendour he avoids,
does not choose to use silver or useless vessels that savour of the pomp of this world.
His house is very plain, his living so also;
and yet he enjoys plenty of the good things that
are necessary for Christian accommodation:
we dined with him, and were kindly entertained.
In the evening went to see a widow Friend in affliction,
with whom and many other Friends we had an opportunity of sitting together,
and witnessed a little of the unsealing of the
goodness that is hid in the invisible life.

26th.--I was at Chester meeting, it proved a low season,
in which I felt my mind much straitened whether to say anything or be silent,
the intelligence seemed so low, and the ability so small:
but as I was brought into resignation to the Divine will,
I felt the balance was for speaking a few sentences, which I did to more ease,
and with more authority, than I expected.
It was respecting the people of Samaria who said
they believed not for the saying of the woman,
but had now heard for themselves,
and believed that He was the Christ the Saviour of the world;
they were so reached and convinced by his preaching; which would be the case still,
if people were concerned to look for Him where He does appear and preach,
in their own hearts, and be drawn off from instrumental helps, looking to Him,
the glorious author and finisher of true and living faith.
This and more I had to drop,
which greatly eased my mind and redeemed my spirit from the state of
travail it was in and under for the slain of this people.
It happens when a stranger travels, the intelligence becomes so universal,
that the public assembles, and those who seldom attend any place of worship then come,
which adds to the weight and exercise of poor pilgrims;
but out of these straits the Lord our God delivers all that put their
trust in Him,--blessed be His great and glorious name for ever!

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Neale to Samuel Watson, Ireland.

[.signed-section-context-open]
Jersey, 27th seventh month, 1771

[.salutation]
Dear Cousin,

In my traversing the wilderness,
I have sometimes felt my mind drawn to converse with thee and thy dear wife,
in a nearness that prompts me to tell you so.
The great Orderer of nature and the God of all grace has visited you,
in order to make you His: as inward care and feeling are kept to, I trust it will be so;
and that you will more and more become serviceable in your day,
by yielding obedience to that which influences and disposes to
follow the Lord in His leadings and requirings.
The way to hear the language of the Spirit is to be within;
it is often slow of utterance unless we are willing and obedient;
the quicker we are to hear and active in obeying,
the readier and oftener it speaks to our instruction
and furtherance in grace and sanctification.
And as you have been made partakers of the power of the world to come,
live near its quickenings.
It leads into solitude and solitary places,
and out of the spirit of the world and its inordinate love of visibles,
and great anxiety for accumulating unstable riches;
and it girds up the loins of our minds to serve Him,
whose glory cannot be comprehended by mortals.
In this state at times we feel a joy and rejoicing, that encourages us to persevere;
in which we are ready to conclude that nothing shall be
able to separate us from serving the Lord,
in our day and generation.
And perhaps this lasts for a season,
when we seem to gain ground and to go on prosperously;
but this abates with the withdrawings of life, and the world and the things of it,
often gain strength in our affections, when we are apt to grow cool and easy,
and to delight in terrestrials,
with the plausible pretext of taking care for our families, etc., etc.
But it is beyond a doubt with me,
that a religious faithful discharge of our duty to God and his Church,
is the way to prosper inwardly and outwardly,
and to enjoy a kingdom on earth far superior in dignity
and glory to any emperor or king that fears not God.

I therefore, dear cousins,
fervently desire that you may mind Mary`'s choice--the one thing needful, which she chose,
and which should never be taken from her; and then all necessary things will be added.
The abounding disposition of this age,
and even of many of the professors of the spotless Truth,
is to join close as to the chariot of this world, by which they suffer loss greatly,
and become disqualified from hearing distinctly the language of the Spirit,
and what is required of them by Him, who called them with a high and holy call,
to go and work in the vineyard.

Arise therefore, and take a solemn look into your progress heavenward:
see whether the engagement is as powerful as it has heretofore been;
whether it is growing from strength to strength.
I shall not be surprised at your feeling coolness at times, or even affliction and death,
and abiding even in this baptism for a season.
But let us never be reconciled to it; but wrestle, as holy Jacob did,
by which the appellation of prince was conferred upon him,
for he prevailed with God and man.
And beloved cousins,
it is the wrestling seed that shall still prevail and be serviceable amongst men,
shall have influence and place with them in the Church,
and even by labour so convince them as to have them
reconciled who were in disorder and transgression,
and alien from the commonwealth of Israel.
I have felt a little openness of this sort towards you, and in it salute you,
and desire your prosperity and advancement in righteousness for ever.

My journey in this continent hitherto has been to my own relief and satisfaction,
feeling the evidence that I am here according to what I believed to be my duty;
in which daily renewings are mercifully extended.
I have been through North and South Carolina, Virginia, Maryland,
and am now finishing East and West Jersey.
There is a great body of Friends on this continent, beyond what I expected:
many of them deep and valuable in the Church,
and many of them too deeply settled in earth and earthly things;
and though they are not in much pomp as to worldly splendour,
the root and leaven of that spirit which dissipates and renders useless,
very much hurts and weakens as to coming forward in the brightness of Truth,
and in service in the Church.
J+++.+++ Churchman, William Brown, Joseph White, and several that visited Europe in our memory,
are well, and keep alive in the Truth, in the living unity and spiritual bond.
Thomas Lightfoot and Susannah I have been in company with several times, and at their house.
Susannah is highly and deservedly esteemed, and so is her husband:
I believe they would both be as well pleased to live there (I mean Ireland) as here;
It is not all gold that glistens; that is enough to be gathered +++[+++as to]
what I mean.
There is a low vulgar education amongst the professors here,
that if they do not feel and live to what they profess,
they are very low indeed in behaviour and conduct,
which by a spirit of obstinacy that prevails in them,
is very degrading to Truth and the Society, and especially in the European`'s opinion,
who are brought up otherwise.
But where Truth prevails it polishes, and makes all beautiful and lively,
and the members thereof are but one family all the world over.
When I consider how soon the veil will be rent,
and the spirit released from the confines of mortality,
I cannot but ardently desire for myself arid my kinsfolk according to the flesh,
that we may so run as to obtain a mansion amongst the blessed.
I am, therefore, in love that waxes not old, engaged to urge you,
as I know the heavenly visitation has been shed on you, for a glorious purpose,
to make you helpful to others, and happy in yourselves.

I have not yet had a prospect, when I may return with any degree of confidence.
I consider myself as bought and therefore not my own; and if it ever will be,
I trust it will be in the counsel of Heaven;
but it looks most likely that I shall reside on this continent this winter.
I am pleased to hear a good account of cousin Jenny;
nothing gives me greater joy than to hear (that) my kindred walk in the Truth.

[.signed-section-closing]
Your affectionate cousin,

[.signed-section-signature]
Samuel Neale.

--

28th.--Being first-day, I was at two public meetings at Haddonfield,
in which were many Friends from other meetings,
and the expectation was so great towards the poor servant,
that I had nothing to say by way of testimony,
(my companion had) and my mind was preserved in peace,
and in a humble dependence upon Him who lives forever,--who knows for
what end He thus seals up the spring of ministry amongst his poor
children who are endeavouring to fulfil his commands,
and to follow the pointings of His holy finger.
Went to visit the widow Hopkins, in whose family I had a sitting,
and felt a little of the crumbs that fall from the heavenly table distributed amongst us.

After a meeting at Upper Greenwich on the 29th,
my companion David Ferris returned homeward; we had travelled in great love and unity,
and his company was serviceable and satisfactory.

Eighth month 8th.--Came to Springfield meeting,
accompanied by my kind friend John Pemberton, etc.;
here we had a solid comfortable season together,--life prevailed in this meeting,
and we were refreshed one in another;
it ended under a weighty sense of the heavenly presence being near and overshadowing us.
Here lives my esteemed friend Mordecai Yarnall, with whom I staid all night.
Next day went to Providence meeting, accompanied by John Pemberton and Mordecai Yarnall:
in this meeting my mind was made easy by bearing a short testimony to the Truth,
after which I felt the +++[+++evidence]
of peace and joy in the Holy Ghost.
Afterwards went to visit my ancient friend Mary James, who though far advanced in years,
is alive in the root and spring of life,
with whom I had a relieving opportunity in the
fellowship of the gospel of peace and salvation.

10th, 11th, and 12th.--I was at the quarterly meeting of Concord,
in which my spirit was mercifully sustained to labour according to present ability,
and I felt the sweet incomes of peace as a shade to cover my mind,
under which I departed in thankfulness.

28th.--At Bucks quarterly meeting, held at the Falls;
the meeting of ministers and elders was a favoured season; I had to speak of faith,
and that it still gives the victory;
sometimes again when we think we are capable to do some little service, and begin it,
like Peter we fail,
and begin to sink and cry out "`Lord save me or I perish,`"--
his Master stretched forth His hand to help him,
and rebuked him with this little admonition, "`O! thou of little faith,
wherefore didst thou doubt.`"
I had to mention the service of keeping close to the Master,
and that as we look to Him in times of the greatest straits,
we should not fail of heavenly succour.
I went home after meeting with Joseph White.
On the 30th was at the youths`' meeting,
where I was exercised in a good degree of that help which Truth gives,
and departed in sweet peace.

Ninth month 11th.--I was at Maiden Creek meeting,
in which I felt a spring of love and life very pleasant and sustaining:
I was opened to speak something comforting to a sick state resembling that of Lazarus,
who was first sick, and afterwards died; the Lord Jesus loved the family,
and drew near unto it in order to raise him from this condition,--even He,
who is the resurrection and the life still; and those who believe in Him,
though they were dead, yet shall they live,
and whosoever liveth and believeth in Him shall never die.
As his power is believed in, it will cure the distempers of the soul,
and thus raise from death; it is He who is the resurrection and the life,
that does this great and solemn work, and therefore, +++[+++I exhorted]
to receive Him and believe in him; and though we may have, been in the grave,
and lain three days, yet would He raise from the dead.
I had also to encourage some states present to look to Him, who,
as we are faithful and fervent,
is graciously pleased at times to raise us into newness of life.
It was a good and strengthening season which I trust will be remembered.

19th and 20th.--Was at Haddonfield quarterly meeting,
where in the meeting for ministers and elders I was concerned to speak of Deborah,
who was raised up for the Lord`'s work and service,
when the high ways were left unoccupied, and the travellers walked through by-paths.
After her victory she had a song to sing,
and that the stars in their courses fought against Sisera and
the enemies of Israel--this I applied to these gospel days,
when the members, who draw their strength and influence from the Sun of Righteousness,
and keep their places,
may be counted as stars standing against the enemies of
Israel and making war against wrong things.
I was mercifully sustained and replenished this day; next day returned to Philadelphia,
in order to attend the yearly meeting.
