== Chapter XI.

[.chapter-synopsis]
* Remains at home for several years
* Religious visit to Friends in and about London, etc.
* Various services in his own country.

+++[+++After his return from America, he remained at home during the years from 1773 to 1777,
duly attending the six weeks, quarterly, and half years`' meetings,
as they came in course.
It appears that he was much occupied in attending to his business,
but whilst thus engaged to be diligent therein,
he was earnestly concerned to be also "`fervent in spirit,
serving the Lord:`" manifesting where his treasure and his heart were,
by keeping best things uppermost, as the following extracts from his diary set forth.]

[.small-break]
'''

1773,
Seventh month 14th and 15th.--Attended to my domestic
affairs;--read a little to stay and sweeten my mind;
for the perplexities of life are a great embarrassment to a
person rather anxiously exerting his power to +++[+++obtain]
ease therefrom.

Ninth month 7th, 8th, and 9th.--Hurried with worldly concerns,
which have a tendency to unfit the mind for spiritual contemplation;
but by the renewing of the heavenly virtue, the heart becomes mellowed,
our views changed and translated.
Grant, O! my God, this sustaining, warming influence,
by which I may become saved from delusion of every kind,
and delivered from the noise of the archers, whether natural or spiritual.

11th.--My outward affairs engaged my attention,
and I passed through them with more serenity than at some other seasons;
may every dispensation work together for good, and show the vanity of things terrestrial.

1774, Eighth month 10th, 11th, 12th,
and 13th.--Domestic occurrences took up a pretty deal of my attention,
I hope not to render me insensible of the duty I owe to Him,
in whom I live and move and have my being.

Ninth month 17th.--My domestic affairs took up
much time:--market-days prove days of hurry,
which manifest that in the world there is commotion and discomposure, but in Him,
who is the Source of life, there is peace and quietness for ever.

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend

[.signed-section-context-open]
Spring Mount, 13th Second month, 1775.

[.salutation]
Dear Friend,

As to the appointment that is unanswered on our books,
it gives a true representation of our state as a people; some have a will,
but how to perform they find not; they apprehend they see the state of the Church,
but how to restore and build up seems difficult, and involves in doubt.
While this is the state of the vessels, half aground,
it is best to wait the return of the rising tide, which comes in due season,
and bears up above doubting, puts them in rank and order,
and sometimes fills the sails with a prosperous
wind to waft them into the destined ports.
I would not be understood to throw the least discouragement on the service;
I believe it is useful when rightly performed,
and this can only be in the faith which gives strength.
This I apprehend was Gideon`'s, when he went on the work he was appointed to;
he was inexperienced, and yet because he had faith he succeeded,
first trying the fleece wet and dry.
But old warriors often exercised and inured to command and to war,
if they feel the motion, let them proceed; until then,
to wait is the wisest measure to be pursued in my judgment.
I believe I shall have an engagement in our own province.
Limerick and Cork meetings are to be visited.
I think I have some little draught that way,
notwithstanding it may be the province of elders;
and I would there were many spirited up and down into that service by the power of love.
Then neither schools, farms nor merchandize could prevent;
all would be burst and be broken +++[+++that is]
of an entangling nature,
and the highways would be occupied by the feet of the redeemed elders,
and indeed ministers,
and they would go forward in rank and dedication in the services of Zion.
I have thought sometimes of late that the day advances fast upon some of us;
it draws towards evening, and it is time to shift the labouring oar into younger hands,
to bear the burden and heat of the day of worldly toil,
which only yields a perishing reward; and if we have the | necessaries of life,
and a supply for the exigencies,
where is the need of amassing and accumulating a mountain,
that may one day fall upon the progeny of virtuous predecessors, and dash them to pieces;
and also to purchase fetters and slavery in the
evening of life for those virtuous parents,
when they might have been beautiful at the meridian,
and wear the polish brighter and brighter in the evening of life.
Let us arise, dear friend, from a slumber into which too many have fallen,
and shake ourselves.
Worldly fame and worldly riches bear no comparison with the riches of
immortality and the fame of serving the Lord in our generation;
let us join in the rank of dedication,
and aspire more and more to be unshackled from every concern
but this one concern of living to Him that has died for us;
and then we shall stand in a shining lot at the end of days!

[.signed-section-closing]
So wisheth, so prayeth him, who is t affectionately and sincerely thy true friend,

[.signed-section-signature]
Samuel Neale.

--

1776, Fourth month 10th.--In town,
and had some company to dinner about other people`'s affairs:
it is a drudgery I do not like,
nor is it compatible with the peace and quietude which it is my study to pursue,
when best wisdom covers my mind; but in this world we have a variety of engagements,
sometimes on our own and at other times on other people`'s account.
May the Director of virtuous pursuits enable me
to get through them with peace and reputation;
and that in my running the race,
I may feel an increase of spiritual strength to struggle on,
and experience at last victory in Him,
who is the strength of the battle and the pavilion of peace, safety and conquest!

[.offset]
+++[+++It may be well to remark that he was often kindly engaged for the help of the widow,
the fatherless and the needy, which labour of love,
though at times attended with much harass and fatigue to himself,
he often mentions in his diary as affording him much peace and comfort.
Indeed he seems to have been as a tender father to the whole flock,
over whom he had been by the Great Master appointed an overseer:
and he was faithfully concerned to pity and strengthen the weak,
to plead with the backslider, to warn the rebellious, to arouse the careless,
and to encourage and comfort the faithful and tender,
in private opportunities as well as in public ministry,
being truly a pattern of diligence in his Divine Master`'s business,
not seeking his own things,
but "`the things of Jesus Christ,`"--being clothed with humility, and fearful of himself,
but leaning only on the arm of All-sufficient strength.]

+++[+++He remarks on the 21st of eleventh month, 1776,
on returning home from the National half year`'s meeting:]
Found my wife and family in health, for which and every blessing,
I desire to be made truly thankful;
and as it is by living near the virtue of Truth that we are made and preserved so,
I ardently wish I may be more and more sustained to feel after this excellent virtue,
which preserves the mind in a fit state to meet every storm,
and to be able to bear every besetment suffered to assault poor mortals,
in their passage and pilgrimage through this vale of perplexity.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Spring Mount, 14th First month, 1777.

[.salutation]
Dear Friend,

Thy reply to mine respecting an
excursion to England in the service of the day,
I look upon as conclusive.
If thou hadst felt thyself harnessed for a trip there,
it would have been a strong inducement to me to look at it with more ease and fortitude;
for though my mind has often felt a draft that way,
yet not with sufficient force to venture without a good yoke-fellow,
and this was my reason for sounding thee distinctly without hinting my own feeling;
but if it had increased I believe I should have yielded in the simplicity to the impulse,
even in a single state--because that which has
heretofore drawn has never yet failed to succour,
so as at least to yield the penny of peace.
As to great things I never expect them:
the sphere I have moved in has been little and low, the measure has been small,
and yet in the discharge of that committed to my trust,
I have the evidence of that reward the world and its spirit cannot comprehend.

In the pursuit of this duty I desire to be preserved;
but the present state of the Church is very discouraging,
the living active members are but few, and some of these shackled with temporary cares.
I have felt my portion, I have been favoured to view the inconveniences,
and from ability received have got some of them taken off,
and hope soon even to feel more liberty from those
entanglements that have the delusive glitter of lawful things.
Our call is high and holy, the day calls for diligence,
the supineness of professors in their own individuals in the general,
makes it more absolutely necessary to cleave to that which multiplies our strength.
We have few examples of devotion and dedication, too, too many minding their own,
and not the things of Jesus Christ;
and is not this obvious in those even in the station of ministers and elders,
who have received gifts, have known the day-spring from on high,
have felt the arising of the nethersprings,
and have been made to rejoice as in the time of harvest?
It obstructs the pure running of the celestial stream of unity in our general meetings,
and prevents the dominion of that life,
that in former days was as a diadem of beauty and a crown of glory.
Thou hints to me,
"`some of you have been honoured with gifts which ye
are called to exercise to the edification of others;
I envy you not the honour, though I think it is great.`"
Why was it not "`us`" instead of "`ye?`" Dost thou
disclaim the favour when it is evident thou hast it,
and hast been called and sent into the work, yea, and hast worked?
Do not excuse thyself by any shelter of thy own creating, for it will not do;
my dear friend, thou hast the talents, make the proper improvement,
for all was to be left, house and land, wife and children, and even to hate the life,
comparatively, that we have in this world, to win a better,
to stand approved of Him who had not where to lay his head,
though the very foxes had holes, and the birds of the air nests, so single he stood,
and so glorious an example transmitted and diffused to his followers.
And there are amongst the people professing righteousness,
who may be compared to the foxes that have dens, that prey, and raven,
and live upon the prey unto themselves,
that are to be hunted by those the Lord has chosen for his own work;
and others like unto the fowls of the air,
that have built their nests on high in lofty imaginations,
that are to be brought down by skilful marksmen, such as thou.
But if the lawful things should interfere and interpose, and this work be neglected,
at whose hands will this be required?
why those whom the Lord of light has anointed and chosen for his work.
Look around poor Leinster, view the monthly and particular meetings,
in some places scarcely a man to stand in the gap where
the vulture that makes desolate is creeping in;
the same accounts from quarter to quarter, dead and deadening.
Remarks are sometimes made which are very pertinent,
but the disordered and distempered are not there to hear them,
they are in their holes and nests.
These remarks unexpectedly occurred, is there not something in them worthy of attention?

The monthly meeting is the place to execute the laws and statutes; the dispensers,
many of them are of weak hands and unclean lips,--in this state how
can Zion arise and come up to the help of the Lord against the mighty,
the world and the unsanctified spirit of man.
If the appointed and anointed, and fitted, bestir not themselves,
the deluge will increase, and,
the standard of formality and unrighteousness
will be substituted for righteousness and peace,
which were to kiss each other.
Farewell, dear friend,
may we be "`the preserved`" from the guilt of negligence in our day,
that by overcoming every enemy, we may obtain the white stone and the new name,
registered in the Lamb`'s book of Life,
which is the earnest wish of thy affectionate friend in sympathy,
and I hope true friendship.

[.signed-section-signature]
Samuel Neale.

--

+++[+++In the autumn of 1778,
he paid a visit in gospel love to Friends of Leinster and Ulster provinces,
previous to which his mind was deeply exercised, and he writes thus:]

[.small-break]
'''

Ninth month 5th.--I have felt my mind much buffeted of late,
some prospects at times arise, which are exercising;
how gracious Goodness may dispose of me, I am a stranger to:
but I trust I shall be enabled to bear the trials allotted me,
and to persevere in seeking Him who is gracious in all His ways,
and fully sufficient to save all that trust in Him.

7th.--I have for some time,
met with the buffetings of Satan;--had a view
opened of some particular things to be done,
and yet felt very little strength to do them;
but a willingness remained (which was a favour)
to endeavour to do what my hands find to do.
Another circumstance of trial seems to occur with respect to some of my family,
whom I believe are under a visitation from heaven.
The cross that is felt by them I seem to feel,
and a sympathy and connexion that is exercising;
but I trust the Lord of living mercy will stretch forth a hand of preservation,
strengthen with inward might and redeem with the joys of His salvation.

10th.--At meeting; it was exercising,
though I had through this exercise some consolations and discoveries,
which I trust humbled my mind,
and helped to bind my spirit more and more to the testimony of the great Lord and Master.

12th.--Went to Glanmire about my temporal concerns, returned in the evening,
I hope thankful and easy.
I have of late felt heavy buffetings,
but I trust the Great Master will deliver out of them all,
I have sometimes looked at them as +++[+++in]
the justice and mercy of God; at other times,
as if they were suffered to come upon me to
drive me home to more dedication and dependence,
as poor mortals are apt to forget themselves;
but I trust the great Lord will deliver from every opposition
which the grand enemy may raise up in my own house.

21st.--A meeting for worship preceded that for discipline,
+++[+++the quarterly meeting at Cork,]
in both of which Divine Goodness was manifested,
and our hearts were humbled under the evidence that Truth is strongest of all,
and when it is in dominion it is beautiful, beyond the setting forth of men or angels!

27th.--First-day, +++[+++after attending both meetings,
in which he was strengthened to bear testimony for the Truth, and visiting a sick Friend,
he remarks,]
I came home and felt a draft to sit down in my own family,
by which submission I felt my mind much enriched and replenished;
and a season we had of much consolation and brokenness of heart;
all present were touched with the holy virtue of Truth.
Intending away +++[+++to Leinster quarterly meeting]
in the morning, we had a sweet instructive parting in the love of our Lord Jesus Christ.
One in my family has been made very near and dear unto me,
whom I know is visited by the Power of the holy Jesus,
to redeem from all things here below.

[.offset]
+++[+++He was enabled by Divine Goodness and Power to prosecute the journey he had in prospect,
to the peace and relief of his mind; he remarks of the quarterly meeting of Lisburn,
that "`the meeting for ministers and elders was solid and instructive,
and the sweetness of gospel love and virtue attended,`"--and of the public meeting,
that "`Life gradually arose,
in which ability was given to speak to various states present,
and the meeting ended under a precious sense of Divine favour and virtue.`"
He was permitted to get home on the 26th of tenth month, thankful and easy.]

Twelfth month 6th.--First-day, at meeting, which was favoured with the living presence.
I then went to the funeral of my esteemed friend James Doyle, who,
after a long illness and much bodily pain, gave up his spirit to the Giver thereof.
He was a faithful labourer in the Churchy and had been deeply baptized:
whilst he lay on his sick-bed, his heart was like a spring well replenished,
living counsel flowed therefrom to many who went to visit him, and to his family:
their loss is great, and +++[+++that of]
the Church considerable; but the Great Shepherd and holy Feeder of His people,
can raise up many more to speak of His great name,
and as he is visiting the young generation,
I trust He will prepare their hearts and qualify them to serve Him in their day and time;
for He is gracious, long-suffering, and abundant in goodness and truth!
We had a large funeral, Thomas Carrington from Pennsylvania, and I were concerned;
the way seemed open, the people were very still and attentive,
and I trust the testimony was reaching to some states present,
the effects of which may return after many days to their remembrance.
Returned home to my house, where I felt an impression to sit down in my family;
it was a tender good opportunity in the shedding of Divine love and goodness,
which tendered our hearts and made us thankful in spirit.

22nd.--Our dear friends Samuel Spavold and Thomas Carrington were at our meeting;
we had a good season together, which was as a parting meeting,
for they set forward after this towards Carlow quarterly meeting.
Dear Samuel Spavold had spent nearly six weeks amongst us on the family visit;
he laboured fervently and earnestly, was much favoured,
and went through the families very particularly, those in unity, and those who were not,
to good satisfaction.

1779, First month 2nd,--Preparing for my intended journey +++[+++a visit to Friends in London,
and some meetings going and returning,]
which I find lies heavy upon me on various accounts;
discouragements attend on the one hand through the workings of an unwearied enemy,
who is ever busy to keep the mind in commotion,
when any work offers to strengthen and warn the
Lord`'s heritage and people against his devices.

3rd.--First-day at both meetings,
in which I was livingly helped to bear a testimony for
the great Lord and Lawgiver of the universe.
Li the evening we had a sweet tender sitting in my family,
after which read the Scriptures as usual before rest, and was comforted.

[.offset]
+++[+++It appears to have been his practice on a first-
day evening to have a sitting in his family,
for retirement and waiting on the Lord, to which the young people of his meeting,
as also his fellow-labourers, were at liberty to come;
many often availed of this privilege,
and they generally proved seasons of refreshment and renewal of strength,
through the tendering influences of the Heavenly Father`'s love;
so that he was greatly encouraged to persevere in this
wholesome exercise and fatherly concern for the flock.]

18th.--I feel my mind much exercised on account of my intended visit to London.
I believe it proceeds from the opening of best counsel,
and in it I have a trust of being sustained,
as my great Master never led me forth in His service that He
did not strengthen and qualifying my measure for it,
blessed be His name!

29th.--At meeting, the fore part was low, the latter part more lively;
and the opening of heavenly counsel was witnessed,
in which several things were unsealed tending to comfort, edification, and confirmation,
and I trust it may be as bread cast upon the waters.
Some of my own family are under a fine visitation;
may the great Preserver of men grant that it may be effectual, that it may be lived with,
and that the holy Shepherd of Israel may take them into His keeping,
and preserve them from harm on every side, that the enemy may not prevail over them,
and may He perfect their salvation to His own praise!

30th.--This day a message came that the vessel in which
I am to go to England is to go down to-morrow;
so having long expected to be called upon, and having put my affairs in order,
I commit myself and those I leave behind, into the hands of a faithful Creator,
who I know is sufficient for every trial that may be permitted:
may our trust be fixed in Him the eternal Rock of strength!

31st.--First-day, at meeting; our Lord`'s saying to his disciples, "`Lo!
I am with you alway, even to the end of the world,`" was much enlarged upon,
and we were comforted together;--blessed be the
name of the great Author of every blessing!
The afternoon meeting was less lively,
but I was favoured with the opening of best counsel,
which united my spirit to my friends;
after which was the adjournment of our men`'s meeting,
and in the evening several Friends coming up to sit with us,
we had a uniting season in the love of Truth,
which rejoiced my heart that our parting was in that which quickens, enlivens,
and knits together: this was a day of favours,
thanks be to the great Lord of his heritage!
Next day went on board.

[.offset]
+++[+++He mentions being kindly received in Bristol, at the house of Lydia Hawksworth,
and proceeded towards London on the 19th of second month, 1779,
taking meetings in the way.
He stayed in London till the 29th of fourth month, visiting meetings and Friends,
and was also at the quarterly meeting at Guildford: he returned home by way of Sheffield,
Manchester, Holyhead, and Dublin.
Of this journey he remarks:]

I was mercifully sustained to go through this exercise far beyond my expectation;
strength was proportioned according to the work; my companion +++[+++John Garrett]
and I went forward under the influence of Divine love,
and we were united to the living +++[+++in Israel],
for which may my soul reverence His sacred Name, who lives for ever and ever!
I got home the 21st of fifth month, easy and thankful in spirit,
and through mercy found my family and affairs in an agreeable state;
for which may the praise be ascribed to the Giver of every spiritual blessing,
and a fervent disposition cherished to press forward and do the work of the day,
that the answer of, "`Well done,
good and faithful servant,`" may at last be administered,
which is the fervent craving of my mind;
and suTe I am the Lord is good and greatly to be praised!

Twelfth month 5th.--First-day,
in the forenoon meeting Samuel Nottingham was engaged in a strong and
beautiful testimony suitable to the states of the people;
afterwards I felt the movings of the Word of
power to speak much in the same line of doctrine,
and on the benefits resulting from humility, as in the examples of David and Jehoshaphat,
and Hezekiah, who were blessed, and the people for their sakes;
and contrasted them with opposite characters in Rehoboam, Jeroboam, and Manasseh,
who sinned themselves, and the people also by following their wicked examples,
which brought down the curse upon them and upon the land.
I exhorted those present to fear the Lord,
that they might be a sure seed and honourable plants growing in Truth and righteousness.
Attended the adjournment of our meeting for business,
and after coming home had a sweet sitting in the family as usual on
this evening of the week,--it was a precious opportunity.

1780,
First month 28th.--+++[+++After speaking of being indisposed
and being obliged to keep the house a week,
he says:]
felt myself pretty quiet within,
but not without a sense of some of the fiery darts of a wicked enemy still unslain,
that will be putting up his head when opportunity and his strength will permit him!
May watchfulness and care prevent his ever
getting power to rule in my heart and affections;
but as he has been cast out, may he be kept out by the power of Divine grace,
which saves and preserves, keeps alive,
and animates to maintain a constant war with this enemy of all righteousness.

Second month 2nd,
3rd and 4th.--The pain in my side +++[+++with which he had been much tried of late]
was increased by a fresh cold, but through mercy I feel much better,
which is a favour indeed:--a little ailment stops our fervour after this world!
May Divine grace operate more and more upon me,
that I may show the reverence and obedience I owe to my gracious God,
who has done so much for me, taken me by the hand, and enabled me, I trust,
to be instrumental to the help of others.

Fourth month 12th and 13th.--Employed much, as for some days past,
in having an eye to the work-people at home.
Home seems very pleasant to me; when I can enjoy it in contentment and quietude,
no place so pleasant! but there is a duty I owe to the Great and all-wise Benefactor.
I trust in His influence which strengthens,
and hope by and through it to be animated to perform my duty,
to leave the nearest connexions to stand approved in His sight, who is holy,
merciful and abundant in goodness and truth!

Sixth month 18th.--First-day, in both meetings today the virtue of Truth sustained,
and the evidence accompanied, that our ministry is not by man nor of man;
I felt great peace and composure after this exercise.
In the evening sitting several young Friends attended,
and we had a solid nourishing season together, I hope in the life and virtue of Truth,
we being mutually comforted together.
Afterwards read the Scriptures before resting-time +++[+++as he remarks somewhat later]
to crown our day`'s work, which is a wholesome exercise fit for all Christians,
strengthening as well as delightful.

Tenth month 6th.--It was rather a heavy season at meeting today,
but ended in a degree of solemnity: we afterwards held our select meeting,
answered the queries,
and had a free and open conference about the state of things amongst us.
Went to see my dear friend James Gough, +++[+++who had come there to visit the families,
and had been taken very ill]; I found a swift advancement in the disorder,
his visible decline was very moving to behold,
and the same evening he quietly and sweetly departed this life to inherit a better!
He was a living minister, and well instructed in the mysteries of the kingdom;
he was adorned with the beautiful robes of love,
and he eminently felt peace on earth to abound in him, and goodwill towards men:
he was a devoted faithful labourer in the heavenly vineyard,
and he delighted to see the youth, under a heavenly visitation,
fitting and preparing for the Lord`'s vineyard.
May the good Spirit which influenced him, descend upon the young and rising generation,
that they may grow up serviceable men and women in the Lord`'s work,
that a succession may appear,
as the Lord`'s worthies are released from a militant to a triumphant state!

1781, Fourth month 22nd.--Our evening sitting was large and much favoured;
it was a sweet season of encouragement to many present, and a melting opportunity,
in which their minds were bowed and contrited.
It certainly is of great service to have such select opportunities,
they tend to the building up in the most holy faith in
Him in whom we have most surely believed,
and which gives victory over the world and its spirit.

Eleventh month 13th.--Third-day, at meeting, there was some favour felt to be extended,
in which I had a short testimony towards the close:
afterwards our men`'s meeting sat for business, in which several matters came before it,
some rather disagreeable; but I hope things ended profitably to some present.
The spirit of man bears too great sway in the conducting of our business,
which makes things dark and gloomy.
The mixture, the linsey-woolsey garment,
is too much the covering of some well-intentioned spirits;
but the true Spirit of judgment carries through our business with strength and clearness,
gives discernment, and crowns with charity and love,
covering weakness and restoring a weak brother in the spirit of meekness.

Twelfth month 19th and 20th.--Occupied in my
domestic engagements at home and at Glanmire,
in which there was little new but a constant attention
peculiar to a life of business and of care;
but in the midst of all had my eye turned at times to those things which make for peace,
and things that edify, in reading, meditation, etc.

1782,
First month 17th.--Heard the sorrowful account of the wreck of the Elizabeth packet,
and the loss of our dear friends Edith Lovell +++[+++who
had been in Ireland on a religious visit]
and Joseph Sparrow, and twenty-two other passengers,
including the captain and some of the sailors.
These sorrowful tidings could not but affect the friends of the lost, and many others.
Such tidings are new, but though new,
when we consider how unsearchable are the ways of Providence and past finding out,
we have cause to keep silence, put our mouths in the dust,
and learn instruction from the harms and trials of others;
for what is man in comprehension, or to be accounted of, here today and gone to-morrow!
One event happens to the righteous and wicked here in time,
but the righteous hath hope in his death, when the hope of the wicked is driven away,
in or by his wickedness, as chaff before the wind.

25th.--Attended our week-day meeting, it was low,
the travail of spirit that is to be witnessed in getting to a degree of good is deep,
and after all, unless Divine virtue moves,
we can do nothing towards the glory and honour of the Great Name,
so that to wait patiently for its arising is our true interest,
and that in the depth of nothingness.

Fourth month 28th.--First-day at Clonmel;
in the afternoon meeting I was particularly led to speak on
the expediency of preparation for going to our long home.
As the spirit is prepared and sanctified for the heavenly inheritance,
all will be well and end well; it was the principal part of my concern,
which I felt with weight upon my spirit, and as I uttered it,
it administered much relief, ease and satisfaction.
A Friend in that meeting +++[+++Joseph Grubb,]
was taken ill in about three days after, occasioned by a cold, and died that day week,
much regretted by those who survived him, for he was a valuable member of society,
both in a civil and religious capacity, and left a fine hopeful family behind,
who I believe all know the work of religion for themselves.

Fifth month 4th.--Attended the National half-year`'s meeting at Dublin,
for ministers and elders, and was exercised therein, as was Thomas Dobson, from England,
a very honest Friend, who, with John Foster his companion,
are both on a religious visit to this nation.

5th.--First-day, both meetings were mostly held in silence;
many Methodists were present who seemed to have their minds much out after words,
but were disappointed, as were many also amongst our own people who delight in words.
In the evening at my lodging there were about thirty youth present;
we had after some waiting, a very sweet opportunity, to the tendering many minds,
and I thought such a season was much to be preferred to
any temporal enjoyment here upon earth,
because it savoured of heaven and heavenly things.

6th.--Our National meeting met: we waited to feel the
arising of the savour of Truth to cement and quicken us;
we proceeded through our business in much brotherly love,
and though some things occurred which in prospect were painful,
yet by keeping in the simplicity and to the feeling virtue of Truth,
we stood measurably in that dominion which Truth gives, and in which there is victory.
The parting meeting and the meeting for ministers and elders were held on the 9th,
in both of which the prevalence, beauty and wisdom of Truth were manifested,
I hope to the praise of the Great Name!

1783, Fourth month 27th.--First-day, at our evening sitting at my own house,
we had a pretty many Friends, mostly young people,
and it was a solid beneficial opportunity in the leadings and
goings forth of the blessed testimony +++[+++of Truth];
the subject was respecting a good and honourable family--Truth is what makes
honourable +++[+++as the Spirit thereof is yielded un to]--neither titles,
learning, nor riches will do without it, because we see some of the worst,
possessed of these things; but Truth, where it is cherished,
beautifies and makes honourable;
those who are in a state of obscurity are made conspicuous in time,
and when they are removed out of time, it joins to the generations of the just,
and all the living, since the creation of the world, in a state of glory!

Seventh month 2nd, and 3rd.--About my outward affairs,
in which there wanted not a mixture of perplexity,
as is often the case in the affairs of this life, but certainly too much of temporals,
dulls and loads the spiritual life that is in pursuit of celestial enjoyments!

11th.--Felt a low heavy exercise at meeting,
but towards the close a serenity seemed in degree to spread over us,
which made us thankful for every degree of the Divine blessing, and the least +++[+++glimmer]
of light from the influence of the Sun of righteousness, when shed upon us,
ought to be prized and lived unto with humility and fear.

1784, First month 11th.--First-day, both our meetings were silent.
Great lowness and heaviness prevail in our assemblies;
the Divine life seems very much veiled from us; we seem as though we sat in darkness,
and the beauty and comeliness of Truth very much shaded from us.
May heavenly favour return, or we shall be a frozen people!
In our evening sitting several young people were present,
and I thought we were favoured with the lifting up of
the light of the heavenly countenance upon us.
