== Chapter XII.

[.chapter-synopsis]
* Attends the Yearly Meeting in London, in 1784
* Religious service in Ireland continued
* Death of Sarah R. Grubb at his house
* Conclusion of his journal
* Testimony concerning him from Cork monthly meeting.

+++[+++It appears he attended the yearly meeting in London in the year 1784, at which he states:]
there were no less than ten ministering Friends from America;
it proved a profitable time to many:
the sittings thereof continued to the 5th of sixth month.
It was moved both among the men and women, and Truth evidently owned it,
that a yearly meeting for women Friends be established.
The proposition was brought forward thirty-one years before,
when John Churchman and William Brown were present;
it was a time evidently owned by Truth, a variety of sentiments appeared,
many Friends spoke of the utility and expediency of the measure,
but opposition being made to it at that time, it was then postponed.
It was again revived some years after, when I happened to be at the yearly meeting,
and was again prevented from being carried into execution,
and I remember that I then hoped to live to see it.
On the 5th,
twelve women Friends came into the men's meeting
and made their proposition with great solemnity,
Elizabeth Robinson, Esther Tuke, Alice Rigg, Martha Routh, Mary Proud, Sarah Grubb,
and the American Friends.
The evidence of Truth strongly impressed the minds of
those present \nth a sense of their concern being right,
and Friends concurred so heartily with them,
that a minute was made to that purpose at the next sitting of the meeting;
and a copy of the said minute was handed to the women
Friends by a deputation from the men's meeting.
Robert Valentine, William Tuke and I were the deputies; we had a good time among them,
and left them in sweet peace: we returned to the men's meeting, and the Epistle was read,
and the meeting of business ended.
Great harmony prevailed this yearly meeting, which was comfortable and consolatory.
The American brethren had a good service at it,
and I hope impressions were made that will not readily be erased;
talkative men were kept down,
and I trust the Truth gained ground this day in our Society and amongst its professors.

7th of Sixth month.--Our concluding meeting of ministers and elders was held;
it was very solemn,
and many living testimonies were borne by various
Friends under the sweet influence of Truth,
which closed this yearly meeting.

On the 10th, I set forward for home, with Joseph Inman, John Gough, and James Leckey:
after attending several meetings in Liverpool, we embarked on the 15th for Dublin,
and were favoured to land on the 19th, thankful I hope for our getting safe,
under the protection of the Most High, who leads out, and brings home,
blessed be His holy righteous Name for ever.

Twelfth month 4th.--Our quarterly meeting for ministers and elders was held at Cork;
it was rather low in the beginning, but ended in a degree of strength and living virtue,
Mehetabel Jenkins from New England, was with us;
she is a sweet-spirited laborious Friend,
much in the innocency and simplicity of the Truth.

1785,
Twelfth month 7th.--I have of late been sensible
of declining health and debility of constitution;
what it may amount to the Lord only knows, and his mercies are over all his works;
He has all power in heaven and earth, and can control every malady,
and make hard things easy, and rough things smooth, if he sees meet:
but may every dispensation be sanctified, and then all will end well!

[.offset]
+++[+++After speaking of attending the quarterly meeting at Mountmellick, on the 10th,
11th and 12th of second month, 1786,
which he says was a very favoured season to the Church,
the merciful sheddings of Divine love being witnessed
both in the meetings of worship and discipline,
and they were made to rejoice together, he goes on:]

On the 14th we went forward to Tullamore and Moate:
on the 15th was at the week-day meeting at the latter place,
and the meeting for discipline; the life of religion seems very low here,
the world and worldly connexions have very much
impeded the Divine work from going forward,
and have tarnished the heavenly brightness that ought to be on the
countenances of those who make profession of the pure Truth.
The business that came before the meeting was harmoniously conducted,
and some of us who were present felt our minds united for a family visit,
which being agreed to, we stayed in that service some days,
and were enabled to complete it to our mutual satisfaction,
having also some private visits in making up a difference, which I hope we effected.

After staying some time, visiting my friends and attending meetings at Rathangan,
Edenderry, Mountmellick and Garryroan, I returned home on the 13th of third month,
and though I felt myself much weakened,
I was thankful to have got this little journey well over.

14th.---Was at our week-day meeting, and after all the favours extended whilst abroad,
when the Divine power withdraws we are as nothing,--poor empty creatures,
like empty pitchers!

+++[+++In the year 1786, he was visited with a severe illness, which continued several weeks:
after his recovery, he writes thus:]
The doctors attended from the 21st of the ninth month, for about eleven weeks,
in which time I went through abundance of bodily suffering.
The Lord was good and gracious, and replenished my mind in an extraordinary manner,
and opened the fountain of life in me to speak to divers states and conditions;
many of whom were deeply affected under the influence thereof.

The inward support I felt was very remarkable; the patience and resignation of my mind,
amidst the violent pain attending, were marvellous in my own eyes;
the sympathy of my friends, far and near, was very sustaining;
and I look upon it as one of the greatest blessings in this life, next to Divine favour,
to have the unity of our friends in the time of bodily affliction.

1786, Twelfth month 7th, etc.--I am still confined with my complaint:
I am sensible of the continuance of merciful regard,
and am desirous to be obedient to the manifestations of Divine goodness.
On first-day evenings +++[+++during this confinement to the house]
we had the company of some Friends, which was very pleasing and consolatory,
and some of these seasons were much to my edification and comfort.
The mercies of the Lord are as a great deep, flowing upward,
and replenishing the poor and needy.
We are under innumerable obligations: may a proper sense hereof remain on our minds,
impress our spirits, and live in our actions!

1788,
Twelfth month 11th.--We had the company of several Friends
appointed to sit with us in our meeting for discipline,
William Fennell, Benjamin Grubb, Robert Grubb, James Malone, and Thomas Taverner.
Their company was very acceptable, and I hope of service,
in the present low state of our meeting,
in which the authority of Truth seems much wanting,
and instead thereof the zeal and fire of man is too prevalent,
which will never do the Lord's work, or bring honour to His name and power;
for the wisdom and passions of man can never work the righteousness of God.

+++[+++After this time he seldom had good health,
though frequently engaged in religious services.
In the year 1788, he wrote thus:]
15th of twelfth month.
Not well of late;
my mind feels mercifully resigned to my great Lord and
Master:--I find my natural strength gradually declining,
and a great change in my constitution since the severe illness I had about two years ago.
My greatest consolation is,
that I have faithfully discharged my duty to the best of my knowledge,
and followed the pointings of the Heavenly Shepherd, who went before me,
and sustained in the performance of His own
requirings;--blessed be His holy name for ever,
saith my soul.
The consideration of these things is now a staff of support to
lean upon in my present declining state of health.
I may in reverence acknowledge,
that since my feet have been turned to follow the Lord my God,
he has blessed me in basket and in store, has hitherto helped me in a spiritual sense,
and made me to hope in His salvation,
which is a crown of rejoicing to me in my present confinement.

1789, First month 16th.--Bodily infirmity continues to be my lot,
and great inward stripping and poverty of spirit; which I resign myself unto,
because I think in the due and appointed time I may be delivered from it,
by the power of Him who can change a desert, and make it a fruitful field!

1790,
Second month 7th and 8th.--We had the company of our
beloved friends Martha Routh and Martha Haworth,
also of Robert and Mary Dudley, who came to attend our Province meeting:
the meetings were favoured and large.
Little was expressed in testimony; the expectations of the people were great,
which often is a considerable block in the way of ministry,
because they eye the servants instead of the Master,
and He is jealous of his honour and will not give His glory to another,
neither His praise to imagery;
it is impossible for the best instruments to do any good of themselves,
it would certainly be imagery, only a likeness, or a picture without life, power,
or edification!

Sixth month 9th.--Preparing for our quarterly meeting to be held at
Limerick;--it is a time of much exercise to me on account of the
debilitated state both I and my wife are in +++[+++for this journey];
the Lord our God is sufficient to uphold us, and to increase our faith and strength;
may His holy arm be our strength and refuge!

12th.--Our quarterly meeting for ministers and elders was held,
I thought it a savoury season, where much good counsel was imparted.
In the other meetings we had some good opportunities for the
strengthening each other in the way of Truth and righteousness.

24th.--We set forward for the Leinster quarterly meeting held at Moate,
which was a favoured season; the Great Master was pleased to bless with help,
to testify to His name and power.
We attended Mountmellick monthly meeting, and the week-day meeting at Rathangan,
and arrived in Dublin on the 10th of seventh month,
where we staid till the 22nd. I had divers relieving opportunities at
meeting and in private sittings with my friends;
one of which was a conference with J. D. respecting his great fortune,
and the danger his family are in who are likely to possess it,--setting before him
the utility and expediency of dividing it with those who may merit help,
etc.; he seemed to take it well,
and this little discharge of duty gave me great ease and made me thankful.
Taking Ballitore and Clonmel meetings in our way,
we returned home on the 3rd of eighth month, where we found all things well,
which is a renewed mercy,
and that we were so well supported in this long journey of eight weeks.

Eleventh month 27th.--Our meeting of ministers and elders was held;
it was a season of profit, some things were spoken to in the authority and life;
dear Sarah R. Grubb was with us,
and as usual was sweet in her remarks and opening of counsel,
and also in both meetings next day.

29th.--In the meeting for discipline Sarah Grubb gave some
account of her late journey +++[+++on the continent of Europe]
with diffidence; she gave in great humility some good advice before she left the meeting,
and though very poorly, was helped through her service wonderfully.

She returned to my house, and became so ill that she took to her bed,
and there continued until the 8th of twelfth month, when she quietly departed this life.
She was a worthy,
who dedicated her time and her talents to the service of her great Lord,
and few are more universally regretted by the Church in this quarter of the nation.
My mind was much exercised on account of our dear friend,
and I had hopes she would have recovered,
her days not being long in this life in comparison of many others,
she being between thirty-four and thirty-five years of age,
and had the appearance of a branch that conveyed a prospect of much fruit;
her loss is a great stroke to her surviving relatives and friends.

Our men's meeting was solemn,
and Friends were under a travail of spirit for the prosperity of the Church:
many Friends called on us after the meetings were over,
and we had several precious sittings in the evenings
during the illness of this beloved deceased Friend.

At the interment on the 12th, we had a very solemn opportunity;
the doctrine of the gospel flowed both in the meeting and at the ground.
In the evening, in a solemn sitting,
several Friends were concerned to speak to edification and comfort;
and thus closed this solemn scene.
I sympathize with the poor husband, who returned home the next day,
accompanied by many relations and friends, in a very humble frame of spirit.

1791, Ninth month 16th.--Left home in order to attend our Province meeting at Limerick,
and from thence to that at Moate,
and so to join the Friends (appointed by the National
meeting) on a visit to Leinster Province,
which meetings were favoured in a good degree with the
Divine presence and the opening of living counsel.
Elizabeth Gibson +++[+++from Essex]
and Ann Till Adams +++[+++from Bristol]
were at Moate.
We visited the schools at Mountmellick to good satisfaction,
and the members of the select meeting, as also at Ballitore, Enniscorthv, Cooladine,
etc., and were favoured with the opening of best counsel, which though close, was,
I think, in the spirit of love.
At Wicklow, the 28th of tenth month, none of us had anything to express,
all seemed closed up.
The 29th we reached Dublin, where we staid, attending the quarterly.
National, and other meetings to pretty good satisfaction;
in which Divine Goodness was pleased to reveal His ancient kindness to His Church,
and in the ability He was pleased to give, the business was carried on, I hope,
to the honour of His great Name.
Here we had the sorrowful tidings of the removal of our
dear friend John Gough from works to rewards;
a man very eminent for his extensive gifts and talents,
and his great humility made him beautiful in the
department he filled in the mystical body.
His loss seems to be great as a living member of the Church.
May the great Qualifier of faithful members raise up
others to fill the vacancies that appear so obvious,
that we may still have a Church and people capable to show forth His praise!

On the 11th of eleventh month, I set forward for Ballitore,
and concluded to stay over first-day there,
being in good company and feeling much united to them.
I was at two good meetings, and at one in the evening at dear Richard Shackleton's,
where were divers Friends, and it was indeed a tender season to several then present!

On the 15th, we got to Anner Mills to Sarah Grubb's, and stayed there tYie 16th,
and had a sweet opportunity in the family in the evening.

The 17th was at the monthly meeting at Clonmel, the meeting for worship was solemn,
but that for discipline was very exercising,
the wit and wisdom of the creature being too prevalent,
and the innocent Life not being enough kept to,
which is the crown of our meetings for discipline!
Lodged this night at Mary Dudley's, and next morning set forward for home,
where I arrived safely the 19th, and found my family mercifully enjoying health.

20th.--First-day, I attended both meetings,
in the forenoon I was strengthened to bear testimony to the goodness of a gracious God,
and the meeting concluded in supplication.

[.offset]
+++[+++This was nearly the last entry in his Journal.
It does not appear that any account has been
preserved among the relations and descendants,
of the last illness and close of the life of Samuel Neale,
beyond what is contained in the subjoined testimony from Cork monthly meeting,
which now only remains to be given to the reader.]

[.centered]
=== A Testimony from the men's meeting of Cork, concerning Samuel Neale, deceased.

As the Lord hath seen meet to deprive us of a living minister of the gospel, raised up,
qualified, and sustained by the influence of His Holy Spirit;
whose extensive labours of love, after a long residence amongst us,
are fresh in our remembrance; we find our minds engaged,
from the best information we have received, and from our own knowledge,
to testify concerning this our dear and honourable friend.

He was born in Dublin, in the year 1729: his mother died when he was about six years old;
and his father soon after went to reside in America.

It is worthy of remark, that,
although he was deprived of many of the advantages
which numbers of our youth are favoured with,
in a religious guarded education,
yet he was an object of the peculiar notice of the Great Preserver of men,
having at times,
felt the incomes of Divine love at so early a period as scarcely to
understand what it was that so visited his tender mind:
but as he grew up, he gave way to youthful follies and vain amusements,
for which he often felt the reproofs of instruction;
but slighted these gracious visitations.

About the age of eighteen, he was placed apprentice in Dublin, where he was much exposed,
and suffered great loss; associating with the gay and licentious,
and with them rushing into iniquity,
and indulging himself in most of the pernicious amusements of that city.
During this period he was not forsaken, being followed by conviction and remorse;
nor was he suffered long to run on in that path,
which with awful certainty leads down to the chambers of death,
but in the career of vanity and dissipation, he was met with in a memorable manner.

Soon after his apprenticeship he came to this city,
for the purpose of forming connexions in business: where, as well as on the journey,
he met some of his associates, and again gave way to irregularities; yet,
having in his worst state frequented meetings, and being at a meeting for worship here,
which our friends Mary Peisley and Catharine Payton, then on a religious visit, attended;
the latter was enabled to speak to his state with such clearness and authority,
that the witness in his heart was powerfully reached,
and the strongholds of sin and Satan broken in him.
Happily this gracious call was not rejected;
he submitted thereto with full purpose of heart,
and in the prime of life making an unreserved surrender of his will to the Divine will,
and turning his back on sensual, sinful gratifications,
he afforded a remarkable instance of the blessed
effects of an entire dedication of heart.
This precious, powerful visitation was in the twenty-second year of his age;
and being through infinite Mercy, preserved in and under it,
it was not many months until he came forth in the ministry,
evidently attended with the baptizing power of the Gospel;
which had so reaching an effect on many of the hearers,
divers of whom had been his former companions,
that it afforded abundant cause of humble admiration and thankfulness.

About this time, our friend William Brown arrived from America,
on a religious visit to these nations; and, not having a companion, he,
with the concurrence of his friends, joined and continued with him,
through most of his travels in this nation, parts of England, Holland and Germany,
we believe much to their mutual consolation, and to his own establishment.

In the year 1753, he removed to reside within the compass of Edenderry monthly meeting,
and continued in the exercise and improvement of his gift.

In 1757, he was joined in marriage to that dignified instrument Mary Peisley:
this connexion was dissolved within the short space of three days;
it having pleased the All-wise Disposer of events to
remove that valuable woman after a few hours' illness.
This heavy trial he bore with much resignation to the Divine will,
manifesting the inward support which was afforded him,
by the lively exercise of his gift at her interment.

In the year 1760, he was married to Sarah, the daughter of Joshua Beale,
a valuable elder of this meeting, and, in her,
experienced a tender faithful companion during the remainder of his life.
Soon after his marriage, he settled within the compass of this meeting, and, we believe,
that it was under the direction of best Wisdom; his Gospel labours,
through the Divine blessing upon them,
being very helpful and strengthening to this part of the vineyard.

Having for several years felt a weighty concern to pay a
religious visit to the meetings of Friends in North America,
with the full unity and concurrence of his brethren, he embarked in the eighth month,
1770; and was enabled to visit the churches generally on that continent,
to the consolation and strengthening of many, and to the peace of his own mind.
He returned in the eleventh month, 1772, and, at a suitable season,
with great brokenness of spirit, gave a diffident, tendering account of the said visit,
ascribing all praise to that Power which had qualified and sent forth,
and so marvellously to him,
conducted through the various probations attendant on such a service.

He was often engaged in visiting Friends in sundry parts of this nation;
was several times in England and Wales; and once in Scotland on the same account.

While favoured with health,
he was exemplary in the attendance of our particular and general meetings;
and divers times attended the yearly meeting in London.
Thus he continued occupying with his gift at home and abroad,
until increasing age and infirmities of body,
became some impediment to his labours in that line.

His last journey was on a visit to Friends in the province of Leinster,
in which he felt a concern, to join some that were appointed by the National meeting.
In this service he evidently appeared replenished with
the love and tenderness of the gospel;
steadily moving under the cover of it, and bringing forth the fruits of charity,
patience, and meekness of wisdom.

Having returned home, he found himself still more indisposed,
unable to attend meetings much afterwards; and, in some short time,
he was affected with a mortification in his foot,
which put a period to his existence here.
The means and medicines which were judged necessary to be used in his case,
tended in a great degree to stupify his mental faculties; which is much to be regretted:
but, while reason and recollection were continued,
his expressions bespoke a mind peaceful, calm and resigned.
In this trying illness, he was preserved meek, humble, and patient:
and quietly departed this life the 27th of second month, 1792, aged 62 years;
a minister 40 years; and we doubt not, is entered into the joy of his Lord,
and into his Master's rest.

His remains were interred in our burying ground the 2nd day of the month following,
after a meeting previously held at the meeting-house on the occasion,
which was graciously owned by Divine favour,
and several living testimonies were then borne.

His ministry amongst us at home was truly acceptable and edifying,
being renewedly under the precious influence of the gospel, and often,
in commemoration of the manifold blessings graciously extended by our bountiful Creator:
and having himself, as he was wont to express,
largely experienced Divine mercy and compassion,
he was much clothed with charity towards others.

He was generally and much beloved; benevolent, hospitable, and kind;
an affectionate husband, and a sincere sympathizing friend.

[.signed-section-closing]
Signed in and on behalf of our three weeks' men's meeting, held by adjournment in Cork,
15th of fourth month, 1792.

[.signed-section-signature]
Signed by many Friends.

[.signed-section-context-close]
--Read and approved in our quarterly meeting for Munster province, held at Clonmel,
23rd of fourth month, 1792, and in, by order, and on behalf thereof,
signed by Samuel Davis, Clerk.

[.signed-section-context-close]
--Read and approved in our National half-year's meeting, held in Dublin,
by adjournments from the 29th of the fourth month, to the 3rd of the fifth month, 1792,
inclusive, and in, and on behalf thereof, signed by Jacob Hancock, Jun., Clerk.

[.signed-section-context-close]
--The testimony was finally taken up to the yearly meeting in London, in the fifth month,
1792.
