== Preface

It is hoped that the extracts contained in this little volume,
taken from journals and other manuscripts of our late friend, may if seriously perused,
be found instructive.
Although written in great simplicity,
yet it is evident they proceeded from a mind under the influence of divine love,
so operating as to preserve in humble dependence upon its holy efficacy,
and producing the language of, "`Glory to God in the highest, and on earth peace,
good will towards men.`"

They are published with the view of preserving
and rendering useful such parts of his writings,
as were thought most likely to impress the reader with a sense of the
goodness of the Most High towards the workmanship of his hands;
and to draw into a consideration of the operation of His grace, "`that brings salvation,
and has appeared unto all men,`" which as co-operated with, is found to be a convincing,
converting, efficacious principle; of which the example before us is a striking instance.
This grace is the appointed means whereby all may be brought out of darkness,
into marvellous light; and unto the saving knowledge of "`the only true God,
and Jesus Christ whom he has sent.`"

Seeing the advantage of an early and entire surrender to heavenly visitation,
(whether it be more powerful, as in this instance,
or as a "`seed,`" "`the least of all seeds,`" which if allowed to grow,
would gradually produce a change equally happy) let a wise choice be made;
and the danger of protracting the essentially
necessary work of the soul's salvation averted;
that whether in youth, mature age, or advanced life,
the affecting language may not impress the mind, "`the harvest is past,
the summer is ended, and I am not saved.`"

"`The memory of the just is blessed,`" and the relation of
their experiences may encourage the Christian traveller
steadily to persevere in faith and patience to the end;
that so his termination here may be peaceful, and his change glorious.

[.asterism]
'''

It was the intention of our late valued friend, John Barclay,
that the lives of Samuel and Mary Neale,
should form a part of the "`Select Series`" of Friends' writings,
which he commenced and carried through several volumes.
But he did not live to accomplish it; and his brother, the late A. Rawlinson Barclay,
being desirous of carrying out his views,
undertook the task of procuring such additional materials as were accessible,
and preparing the volume for the press.
Considerable additions to Samuel Neale's Journal have been introduced
from his original manuscripts and his unpublished letters,
and many valuable letters of Mary Peisley, have also been inserted in her life.
The value and interest of both journals have thus been materially enhanced,
and they will be found to convey much solid religious
instruction to the serious and attentive reader.

