== Chapter II.

[.chapter-synopsis]
* Joins William Brown from America, in a visit to some parts of England, Holland, and Germany
* Visits the West of England
* Attends the yearly meeting in London.

+++[+++Twelfth month, 1751.]--About this time dear William Brown arrived from America,
a faithful minister and an experienced elder, who needed a companion.
I was spoken to on the subject; and after receiving the advice of my friends,
and feeling my way open, I agreed to go with him; this I hope proved a blessing to me.

[.offset]
+++[+++During his stay in Dublin, preparing for his journey,
he laboured faithfully in the vineyard.
He remarks:]

There seemed an open door; the change in me awakened the minds of several of the youth,
who were greatly struck with it; and indeed it was a day of visitation to many.

We left Dublin in the first month, 1752,
and visited the several meetings of Friends through this nation,
both in the particular and province meetings, as they occurred in our way;
holding meetings also in several places, where there were none of our Society resident.
We had to experience that the God of our forefathers manifests himself to be near those,
whom he commissions and sends forth as sheep, among wolves;
and that it is not the wise of this world by whom he speaks,
but those who are anointed with the holy unction.
The divine power was over the spirits of many of the people,
which confirmed me in the belief, that the Lord will send his servants,
to invite those that are as in the highways and hedges to the supper of the Lamb.
At the last meeting we attended in this journey we were made partakers of the healing,
sweetening virtue of Truth; and we were mercifully sustained throughout,
by the invisible omnipotent Arm, that never fails those who trust in it.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Neale to a Friend

[.signed-section-context-open]
Widelow, 13th of Third month, 1752.

[.salutation]
My Dear Friend,

Though I am at times borne up by the renewings of divine assistance,
yet am I at seasons as empty and as mere a nothing, as though I never knew any good;
and it is rare that I meet such refreshing showers of celestial sweets,
as I did when in your company;
which makes me ready to conclude it was only an earnest for me to enter into service,
and that I must now work for my bread.
Well, I verily believe,
but for a little faith that I find as a stay to my mind in these moments,
I should almost faint;
and then the words of the prophet sometimes animate me when in this situation, which are,
"`Though the youth may faint and be weary, and the young men utterly fall,
yet they that wait upon the Lord shall renew their strength.`"
These words are often repeated in our solemn assemblies,
but how little is the sense of them understood by many of our professors;
the god of this world does blind their eyes,
and delusion chains them with many infatuations.
Well, I have to say, let us wait for divine refreshment,
as humbly craving at the footstool of our God; let others do what they will,
we will by divine aid serve our God; who is strength in weakness,
and a present help in every needful time,--binding up the brokenhearted,
and proclaiming liberty to the captives.
I have to magnify his holy name,
and with adoration acknowledge his manifold mercies to my soul,
who by such an undeserved condescension plucked me as a brand out of the fire.
O! how worthy is He to be waited upon!

I know not, my dear friend, how it is with you; but I would have you to be resigned,
and be patient in tribulation, having hope as an anchor to the soul;
and when you are as the desert, springs will be opened,
the blossoms shall appear in bloom, and sadness will be removed.
But, indeed, we cannot expect to be free from suffering here,
for it is by suffering we are to reign with Christ,
who was made perfect through sufferings.
Therefore I commend to you what I do to my own soul, which is patience in tribulation;
that when we glory let it be only in the cross of Christ.

[.signed-section-closing]
Your real friend in the ever blessed Truth,

[.signed-section-signature]
Samuel Neale.

--

Returning to Dublin, we attended the national meeting in the fifth month; after which,
having obtained the concurrence of my friends, we embarked for England;
arrived at Liverpool on the 10th, and on the 15th of the month we reached London.

We had several precious opportunities during our stay there,
though my spirit was deeply baptized, under a sense of my own unworthiness;
also on account of the liberties taken by many, who make a high and holy profession.
In this yearly meeting my spirit was much humbled within me--
the heart-tendering power and virtue of Truth broke in upon me;
and I thought if I spent such a season every
year of my life it would be truly profitable.
The meetings for discipline, as well as those for worship, were very consolatory;
my spirit was much broken and contrited before the Most High, and I walked in great fear.

[.offset]
+++[+++In a letter to his friend, Richard Shackleton, dated about this time from London,
he writes:]

[.embedded-content-document.letter]
--

As for my part, my dear friend, I find nothing else is like to do for me,
but the most solemn attention, and the deepest looking after that I am capable of,
to know how to act for my own peace of mind and the honour of Him,
who has called me out of darkness into a measure of his marvellous light;
to give me a sense and relish of the enjoyments of supreme love,
and his gracious condescension in visiting my soul when I was captivated
with the delusions which would inevitably have terminated in eternal misery.
May a sense of this matchless mercy and lovingkindness rivet my affections,
and fix my desires after the continuation of this love; which, indeed,
has warmed my heart with strong desires for Jerusalem`'s cause,
and showed me the beauty that there is in a life given up to the service of our God;
who has done more for me than I am capable, by the thousandth part,
to give the least idea of.
Well, what can I do?
nothing I am sure that is good, or in any ways contributing to the good cause,
only as I am actuated by the motions of the Spirit of Truth; which, when enabled,
I have to beg it may be my greatest care and diligent concern to adhere to;
lest I be deceived by the insinuations of my unwearied adversary,
or an inherent disposition in the nature of poor fallen man,
to be in action for the applause of his fellow creatures.
I honestly confess, for my part,
that except I am in the most attentive manner watching over the rovings of my mind,
I find I am surrounded with dangers, which, when in Truth`'s arising,
I obviously see to be destructive to my own good or happiness;
and this danger that so besets me is,
a desire of being what my good Master does not think proper to have me to be, which is,
in being ambitious to be great in the cause I am engaged in,
which I see has its rise in self, a monster that is an enemy to many souls,
and a destructive one too.
Oh! when we come to experience a will entirely
resigned to be what our God would have us to be,
it is then we are made vessels, or instruments of honour, fitted to act as He,
the Lord of the harvest may see fit to employ us, whether it be to reap, to sow,
to thresh, or oversee that the work is going on to his glory.

Many worthies there are here from all quarters.
The meeting of ministers was an instructive season to all present,
especially to the little ones.
In the meetings of discipline, in my apprehension,
there does not seem that unanimity and concord
as might be wished for in such a solemn assembly;
there being men of great capacity, who,
instead of waiting for the forming power to give ability, speak with precipitancy,
as if jealous lest some other should take up the time.
However, the Master and God of order has many that are watchful on Zion`'s walls,
lest the adversary should make an inroad, who, like the good prophet of old,
will sit on their tower,
and be instant in season to speak against any invasions the enemy would be making,
to disturb or render fruitless the labour that is bestowed.

--

[.offset]
+++[+++He proceeds to give an account of his journey, in company with William Brown,
through some parts of England, Holland and Germany,
from which the following extracts are taken.]

On the 29th of fifth month, we got well to dear John Griffith`'s, at Chelmsford,
and next day being first-day, we were at two favoured meetings there.
On the 31st, we reached John Kendall`'s, at Colchester, and stayed their yearly meeting,
where the presence of the good Shepherd was witnessed; the meeting lasted three days,
and ended with heavenly sweetness.

On the 6th of sixth month, we set out for the yearly meeting at Woodbridge,
and during the time thereof,
we were frequently overshadowed by the goodness and glory of our God,
and the testimony of Truth went forth in good authority and power.

On the 3rd of seventh month, we went on board a sloop at Yarmouth,
and through the goodness of a gracious God, landed on the 5th at Rotterdam.
On the 8th, we got to Amsterdam: were at meeting there;
and blessed be the name of the Lord our God, we were owned by His living presence.
In this city we stayed for some time, visiting the families of Friends; exhorting them,
as Truth opened our way, and gave us tongue and utterance.
I was very thankful in feeling what I did among them.
My spirit was much united to some states there,
and though I could not converse with them,
yet there was a union and fellowship in spirit,
that had a language unknown to mere worldly-minded men.
From hence we proceeded to Osnaburgh, etc., and on the 23rd of eighth month,
we went on board the packet-boat at Helvoetsluys,
and through the continued condescension of the invisible Arm of power,
arrived safe at Harwich on the 24th.

[.offset]
+++[+++From Amsterdam he wrote to his friend Richard Shackleton,
under date of 17th of seventh month, from which the following is extracted:]--

[.embedded-content-document.letter]
--

The hand and judgments of the Lord are to be laid upon
every of his vessels and instruments in his house,
for their being fitted and formed according to the will and wisdom of Him,
who must have polished stones in his building,
shaped by judgment to bring forth righteousness, and to live a righteous life.
It is my sense, that the more crooked grained and stubborn by nature we are,
and exalted by our own pride of heart, the more chipping and planing we lack,
and the harder are we to be brought to that nothingness which initiates us into the body,
and makes us members of Christ.
He, whose eye is over the workmanship of His hands,
and who knows the secrets of the hearts,
the most hidden thoughts being manifest unto Him, sees what will humble,
and fit us best for His use.
I believe this was the cause of His hiding from
me His presence so much in that great city,
London, and left me so insensible of good;
in order that I might see how little man`'s knowledge or wisdom is,
when there is a veil drawn between him and true wisdom:--This was then my error,
dear friend--the natural man arose, self grew great and was exalted,
being clothed with a disguise that indeed deluded,
by exciting suggestions injurious to peace, and far from true humility; it set itself up,
and gloried as it were in its own shame,
by whispering with a mixture of serpentine venom,
how I had been plucked out of the mire and dirt,
and set among the foremost in the househould of faith;
and if all this was done in so short time, how much more would I experience.
And here cursed self would exalt itself above the pure seed,
that was then oppressed with this strong man armed,
and strengthened by the whispers of the infernal leader of his host,
who is always engaged to lead the mind captive.
But as the all-merciful Judge sees fit to forgive and blot out our iniquities,
when we turn to Him with unfeigned repentance, so I have witnessed;
glory forever be attributed to Him.
If we watch with a single eye, there is a shining of that light within,
which discovers every speck and spot of uncleanness,
and judges and mortifies it:--and thus looking to Him,
who was the guide of his people of old by a cloud and a pillar of fire,
which is figurative of our spiritual travels in this
our day they were to move as the cloud moved,
and stand as it rested on the tabernacle; here was the eye to be fixed on the sure Guide.
It is just so with us in the spiritual travel; as the eye is fixed on the gift within,
and waits for instruction, it is to be found; but while we are unsteady and impatient,
the enemy works and draws the mind aside.
Thus does the mystery of iniquity work,
till it is made to flee with the brightness and coming
of Him who slays with the Spirit of His mouth.

After I left London, I felt the animating love of my God re-kindle in my bosom, which,
with the company of many worthy Friends, was more than I was deserving of.
I looked on myself with shame,
for having been so long a neglecter of the mercies offered to me,
and a trampler on that precious blood spilt for my redemption.
When my companion had a view of this country,
I had some small hopes that I might return home, and was in a strait for some time,
not knowing what I should have to do or could do
in a country where they spoke by an interpreter;
and besides, there was a young man under a concern to go,
which when I mentioned to my companion seemed to affect him more than I could think.
I continued waiting to know my duty, till I found every arising scruple give way.
Accordingly I set off from Norwich,
in company with about thirty valuable religious Friends,
who came about twenty-two miles to Yarmouth; where we had a heavenly meeting,
as a confirmation of the notice and regard of that Power, who is superior to every power,
in whom is fulness and glory forever.
We took shipping and arrived at Rotterdam, the 5th of this month,
came to this city the 8th, and here have continued;
have had several meetings and visited all the families.
There is not that conformity of dress in the professors here,
which is peculiar to the simplicity of the gospel; I hope the labour bestowed upon them,
as it comes from the fountain of all good, will so operate with the gift in them,
as to bring them to a sense of their error.
They say it is a stiffness among them, that is peculiar to the Dutch;
but Truth is the same here as in England,
has the same efficacy and force to break every hard heart,
and bring into subjection everything that would resist against its motions;
and it is my companion`'s and my belief, if they do not in this conform,
Truth will not flourish here;
for disobedience thereto fits them for the conversation and love of the world,
which is at enmity with God, hinders them from bearing the cross,
and becoming truly circumcised.
But all we can do is, to discharge ourselves, and leave the effects.

We intend by divine assistance to go to Osnaburgh next week,
about four days`' journey from hence,
near which city there has lately appeared a convincement of our principles;
and from there go to North Holland, which when accomplished,
we hope to be free of this country, and return to England.
Hoping these lines may be taken as a token of my friendship and unforgetfulness of you,
being written in the aboundings of that love which
fills a heart that wishes you prosperity in every sense;
I am, your very affectionate friend,

[.signed-section-signature]
Samuel Neale.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Richard Shackleton

[.signed-section-context-open]
London, 17th Ninth month, 1762.

[.salutation]
Dear Friend,

Your very acceptable letter of the 5th of this month, I duly received,
and I can truly say it was satisfactory as well as consolatory to me,
being in a low dejected moment of my pilgrimage.
But the goodness of that merciful Lord,
who in his wisdom sees fit to leave us at times in a stripped state,
to show us our weakness, poverty and infirmities,
will not tarry longer than He gives faith and patience to bear us up,
from sinking below the proper depth, in the sands of uncertainty and unbelief.
I know my spirit in a particular manner has to magnify his everlasting lovingkindness;
and to say, good is the Lord, in manifesting his mercy to the most rebellious.
Indeed, He is long-suffering, great in mercy, and wonderful in power.
Oh! may His glittering sword be unsheathed,
and seen by those that are in the unrepenting paths of idolatry and iniquity;
that by its brightness and the just and awful
threats thereof when in the hand of judgment,
they may flee to mercy, and be pruned from all their branches of error and folly.
Indeed, dear friend, I sometimes think,
when I cast an eye on the iniquity that seems spreading
its power and dominion in the most obvious manner,
on these nations professing Christianity,
that our great and merciful God will send some of his righteous judgments,
as in days of old, when rebellion reigned in the camp of Israel,
to destroy those tramplers on the precious blood,
spilt for the redemption of the children of men.
A certain truth it is,--He will not always strive with men;
for if the judgment of the Most High was poured on the unrepenting and iniquitous,
in a time that only pointed out the gospel dispensation,
how much more guilty are those who with the tongue
confess and profess to believe the sacred truths,
left on record, of the sufferings of our holy Pattern and High Priest;
and act in direct opposition and contradiction thereto, and indeed,
bear in reality the very same hearts and dispositions
of those who judged Him to the cruel death of the cross.

What but love alone would strive with them! therefore when I
reflect on the unrighteousness of priests and people,
and the growth thereof, I am ready to conclude,
some trying calamity will be the consequence of their rebellion and infidelity,
and to believe the man and child is born that will see it.
My spirit in fervency craves that our Society may be aroused from their beds of ease,
and remember the church of old that was neither cold nor hot,
and had a name of being rich and full, and knew not that she was naked, and poor,
and blind, and miserable, etc.
The Lord our God, I am sure, is not lacking on his part;
but is putting his word in the heart and in the mouth, of his poor vessels,
causing them to give it forth in fear and trembling;
so that our Society is without excuse.

But to return to that part wherein I mentioned my lowness:--
this great city and the state of its inhabitants,
cause me pain and anxiety of mind;
and an ardent desire in the right time to be relieved from such exercising seasons,
is my portion now, and was when here at the yearly meeting;
and now both body and mind are affected.
My companion often blames me, with many others,
and even Samuel Fothergill cautioned me against appearing low and dejected.
I cannot come to that strength or experience, when oppression reigns,
to have a cheerful countenance, and a veiled heart, when clothed with sorrow.

My dear friend, this letter, though not worth perusing,
is the best I could send my heart indited it indeed, and not my head; and believe me,
that I truly love you and yours, and many others in my own land.
The Lord`'s will be done;
he can help his little Davids and animate them in the field of battle,
to go even against the whole Philistine host.
Be faithful, my dear friend, and watch for his commands.
When I can, I pray for you, and all my young brethren and sisters.
May the spirit of prayer and supplication cover us as a helmet, and shield us as armour.

[.signed-section-signature]
Samuel Neale

--

After returning from Holland,
we proceeded on our journey through the southern and western counties of England.
On the 9th of eleventh month, we came to Samuel Bownas`'s at Bridport;
where my heart was made sensible of the necessity we have,
while day and capacity are afforded, to work in the vineyard into which we are called,
by seeing this labourer in a decaying, drooping way,
by a failure of those faculties that were once so bright, fertile and fruitful.
But still he maintains that innocency and sweetness which Truth gives,
and leaves the savour of, to all who are faithful to its manifestations;
which remark may my soul treasure up, that so I may make right use of my day and time,
and ardently pursue the one thing needful, that leads to eternal repose,
where the wicked cease from troubling, and the weary are at rest.

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend

[.signed-section-context-open]
Devonshire, 16th Eleventh month, 1752.

[.salutation]
My Dear Friend,

I have of late received counsel instrumentally,
so applicable and befitting my condition,
as binds my soul more and more to the testimony,
and has begotten cries at the very bottom of my soul,
that the thread of my life may be cut,
before I make the professors of the ever blessed Truth,
either to be ashamed or to mourn for my behaviour;
and have been reanimated to covenant afresh,
in remembrance of the horrible pit I have been plucked out of,
and to say--Lord I am yours, and all I have is yours; lead me and guide me,
and give me wisdom if it be your holy will,
to conduct myself so as to be no reproach to your blessed Truth,
or the true members of it; may I and all I have be consecrated,
so as to "`act only in your requirings, and for your cause.`"
And I think, I hear in the secret closet of my heart,
a whisper,--if you will be faithful, I will never leave you nor forsake you.
May your prayers be put up for my faithful discharge of duty;
that I may run not as uncertainly, and fight not as one that beats the air;
but that my body may be brought into subjection, and all the affections of it,
to the law of the Spirit of life; that I may daily die to the natural man,
and live to Christ my Saviour, by the revelation of his holy Spirit,
to strengthen and renew that new life I have received from him,
by the enlightening beams of his eternal love, which is unlimited, universal,
and brings redemption and salvation to its faithful votaries.

Your letter to me, comes with so much brotherly kindness,
that if it were filled with the most penetrating faithful admonition,
it could not be more welcome.
It truly manifests your generous heart`'s regard,
and I believe it was from the motions of that righteous spirit sown there,
that dictated it.
I am sure you desire my growth in the best things, and sometimes are afraid of my erring;
all which I take to be from the pure love which you have to our Zion,
and that the inhabitants thereof may be as stakes immovable.
And now let me tell you,
I am at seasons afraid myself that I shall never be able to hold out;
and many are my supplications that I may be preserved alive,
from the corruptions of the world, or joining in the least with the enemies of Truth,
either in company or sentiment; but that I may be taken away while alive in religion,
and not cut off as a fruitless branch.

Beloved friend,
it makes my heart ache when I consider the degeneracy from that true begotten zeal,
which was about fifty years ago,
when the ancients lived that endured the heat of the day:
it is not now as in the days of Israel of old in one sense,
though too much in another,--while the ancients lived they
served the Lord;--in this sense it may be observed with us now.
But blessed forever be the Son of righteousness, he has ascended up on high,
and given us a law that is of eternal duration, written in the heart, not on stones,
but on fleshly tables; he tasted death for every man,
has given them a manifestation of his Spirit, which, if truly hearkened unto,
would lead us out of all error into all truth,
and give us the same noble virtuous principle of our forefathers,
to keep to the law and the testimony.
Neither riches nor honour would bribe them to come into slavish mean compliances,
nor the fears of what man could do by his empty power, when only in the flesh,
or aided by fleshly powers, carnal weapons, human reasoning, etc.
But now how is the defence or wall of our profession broken down,
I mean the discipline of the church,--what a mixture is there in the seat of judgment,
speaking in their own time, wit, and wisdom, offering false fire as some did of old,
for which judgment was immediately executed.
For as the law was then given outwardly, so was the punishment outward;
but now there is a day coming in which the world is to be judged in righteousness,
by that Man ordained before the foundation of the world;
when reward is to be given as the works merit or deserve.
May your soul be fervent, with all those unto whom Truth is precious,
that the work for which each is preparing, may be faithfully done;
and let me say with one of old, May the God of Israel grant you your petition,
and as you also ask in faith it will be so; for, beloved,
the wrestling seed are to have the blessing, and to them it will not be said,
seek you my face in vain.
Let us keep to the feeling, let us travail with the seed,
that we may know its arising in dominion; and then let us do what is shown us,
according to the present manifestation either in meetings of discipline or worship,
Gideon was but the least in his father`'s house, David was the least in his,
but as they had faith, how did the Lord work in these instruments;
and though the manifestation be but small, let us be honest;
we know not the effect it may have.

My dear friend, let us be resigned and willing, to be anything or nothing;
for my part I am at many meetings and have nothing to say, and yet I am resigned,
knowing of myself I can do nothing.
And let me tell you more, of myself the poorest of instruments,
I think I have not so much to say as when in Ireland often, so that I grow but slowly,
if at all, except it be in the lesson of contentment;
which I find will be learnt if I seek not my will or honour,
but the will of Him who sent me; for as I am His, "`do with me, O Lord,
(I often say) as you please.`"

[.signed-section-signature]
Samuel Neale

--

On the 22nd of twelfth month, we came to Oakhampton, and having a day to spare,
myself and companion visited three young women, sisters,
who had been members of our Society, but were unhappily led away by the Ranters;
whose self-righteousness and delusions cause much uneasiness to the truly concerned,
showing how dangerous that spirit is, when given way to.
Satan, the accuser of the brethren,
tries all ways to disunite from the body and cause a separation,--
rents and divisions being the strength of his kingdom.
And as his insinuations are adapted to all people in their different states,
finding out the weak side, there he plants his battery,
trying one temptation after another; sometimes as an angel of light,
and sometimes (as he really is) an angel of darkness.

But let a faithful examination be entered into,
and a query raised,--Am I influenced by that
Spirit which governs by love in the believers?
Is there no root of self-love or self-sufficiency?
Is there no zeal kindled by the accuser of the brethren,
that would introduce contention and discord, pride and high-mindedness?
This cannot be from that Spirit that baptizes into the
one body and makes us one in Christ;--no,
there would be bearing and forbearing, a forgetting and forgiving,
a persuading and travailing in soul to be of one heart, to love as brethren.
This will manifest whose disciples we are, and who is our Master.
We visited those young women in love, and they took it well;
my companion showed them what true discipline was, and their errors,
when they acted contrary thereto.
On the whole it was a satisfactory conference, and if they are dealt with in love,
I believe they will again join with Friends.

The 4th of first month, 1753, my companion resting a few days, I was at Spiceland,
in Devonshire; where were Mercy Bell and her companion Phebe Cartwright.
Here I was made acquainted with these Friends`' concern,
to go to the market-place and street adjacent in Exeter, which bowed my spirit.
I was baptized with them, and encouraged them to faithfulness.
We spent the evening in a solid frame of mind,
under the consideration of this weighty exercise.
It appeared to me in such a manner,
as made me apprehend that it was my duty to accompany them,
and my companion assenting thereto, I freely gave up, not without first weighing it well,
fearing by being too forward, I might rather hinder the service,
and knowing that the Almighty was as sufficient to work by one
(if it were his will to work instrumentally) as by a thousand.
Thus, secretly desiring to be directed aright, a feeling sense opened to go,
which I believe was strengthening to them.

On the 5th of first month, in the morning, accompanied by William and Thomas Byrd,
we set out, and got to the throng of the market between twelve and one o`'clock;
after a time of silence,
Mercy Bell was concerned in fervent supplication for aid and
strength to fulfill what she thought to be her duty.
We then walked up to the market-place, where she delivered what was on her mind.
Her companion was likewise concerned to warn the people to repent,
for the day of the Lord came as a thief in the night.
They proceeded through the street and often stopped;
the people flocked about us in great numbers, and many were reached;
and although there were several hardened and stiff`'-necked, yet, in general,
they listened with attention and soberness.
Thus these Friends continued about three hours,
regardless of the contempt and mocking of the profane, seeking nothing but peace of mind,
which was administered.
The word being in my heart, was put into my mouth,
and I exhorted them to turn to the Lord, and he would have mercy;
but if they forsook Him and lived a life of unrighteousness, they would,
with the nations of all those that forget God, be turned into misery; and,
for thus bearing my testimony for the truth of my God, I had the reward of sweet peace.

We appointed a meeting for the inhabitants to begin at five o`'clock,
which was very large; and, as ability was given, we declared the Truth.
Mercy Bell had a very open time among them,
to the satisfaction of most if not all present;
and the meeting concluded with supplication and praise to Him,
who fits and qualifies for every work and service.
In this city, there are some professing the blessed Truth,
who are like the rulers of old, who believed, but did not confess,
because they loved the praise of men more than the praise of God.

Next morning I joined my former dear companion, and on the 23rd of first month,
we came to Bristol, where his indisposition rendered it necessary for him to rest again;
and I finding my way open homewards, acquainted him therewith.
It was no small exercise to me to leave him,
who was made as a father to me in counsel and advice.
May it incite to a faithful perseverance,
and cause my soul to be active in every point of duty; as I believe his was.

I stayed in Bristol until the 1st of the second month, was at several meetings,
and can say, the Lord was pleased to be with me and to strengthen me;
forever magnified be His eternal name, for all his mercies to my soul.
On taking leave of my dear companion, we had a religious sitting,
wherein we were mutually comforted; and had to believe,
that as the Lord our God joined us together, so in his wisdom he separated us,
and in his love we parted.

I proceeded to Gloucester and Worcester;
at the latter place I met my endeared friend and sister Catherine Payton.
I stayed both meetings on first-day, which were remarkably satisfactory to me;
the pure life succoured, and I was helped to discharge myself beyond my expectation.
In the evening, we had the company of several Friends in a religious sitting,
which was very refreshing and comforting;
and though the apprehension of being singly at that meeting had been trying,
and fearfulness had covered my mind; yet my good Master made it easy and joyful to me,
additionally so, by casting his servant`'s lot there at the same time,
who had been so great an instrument in His gracious
hand towards my convincement and conversion;
for which continual mercies may I be favoured to hear with humility and attention,
the words that He condescends to speak to my soul; that so I may obey,
and witness true peace to flow in my bosom; for, at this time I can say,
all that I crave is ability to worship the infinite
All-wise Being aright in spirit and in truth.

I arrived in Dublin the 21st of second month,
and attended the meetings as they fell in course, until after our National meeting; when,
with the concurrence of my Friends, I set out for the yearly meeting in London;
where were many Friends of great weight.
Here I was renewedly convinced of the excellency of our principles,
and of the blessed union of the faithful,
and that no weapon formed against them should prosper;
but that the Lord of all power would be a sun
and a shield to those who put their trust in him.
This was a memorable meeting; many living testimonies were borne to the pure Truth,
and our covering was a crown of glory and a diadem of beauty.
In this yearly meeting a proposition came from the women`'s meeting,
for the establishment of a yearly meeting upon the same foundation as the men`'s,
to send representatives from the quarterly meetings annually to attend it.
It was brought in by six women, namely: Susannah Morris, Sophia Hume, Mary Weston,
Mary Peisley, Catherine Payton, and another.
I well remember the salutation of S. Morris, when they entered the meetinghouse;
and she concluded with a short moving and living testimony,
which had a great reach over the meeting.
The proposition, I had no doubt, was from the motion of Truth,
but after a considerable debate it was deferred,
and a recommendation sent down to the different monthly meetings,
to establish women`'s meetings where there were none;
and thus the matter closed this year.
