== Chapter III.

[.chapter-synopsis]
* Returns to Dublin
* Residence near Rathangan meeting
* Attends London yearly meeting 1756
* From there travels into Scotland
* Returns home.

Soon after my return to Dublin, I took a place in the country, intending to reside there;
it was an agreeable solitude, free from noise and hurry,
and relieving to me in a season of baptism and refinement.
This place was within the compass of Edenderry monthly meeting,
and of Rathangan particular meeting; which, about this time,
had a fresh visitation extended from the Most High.
We often sat under the descendings of Divine Love,
in which we felt much tenderness and brokenness of spirit,
and therein grew in virtue and greenness,
tending to make fruitful in every good word and work;
and there was an increase in spiritual riches.

After I was settled in my new habitation, I was very careful to attend Quarterly,
Province and National meetings, as they fell in course, with other religious services.

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend

[.signed-section-context-open]
Clonivoe, 7th of Second month, 1755.

[.salutation]
Dear Friend,

I cannot help admiring the goodness, mercy,
and continued long-suffering of a gracious God,
who is indeed abundant in goodness and in eternal truth; who has pruned, dug,
and cultivated on his part, his heritage, family, and people;
and behold he looks for fruits.
What then are ready to be produced?

Why, I fear by some, pride and haughtiness, arrogance and stubbornness,
conceitedness and self-sufficiency; and very deplorable are these productions;
how nigh are these unto the territories of death, and under the power of judgment,
whom darkness and pain will unavoidably surround, if these vices are not fled from.
Ah! how nigh are these poor souls unto the state of that fig-
tree on which our Lord and Saviour went to seek fruit,
and behold there was none;
and the sentence was passed,--"`let no fruit grow on you
henceforth forever;`" and immediately it withered away.
What can be done, that has not been done for this people?
What can be said, that has not been said,
to bring them home to their forsaken Father`'s house?

While I write, my spirit intercedes thus,--Oh! adorable, forgiving Goodness,
let them stand yet a little longer; bear with them a little longer;
and arm your servants with fresh supplies of ability and wisdom, to woo them to love,
duty, and obedience; and raise up others, who may be more prevailing, more powerful,
and more successful.

This, dear friend, is the language of my spirit at this time;
and do you stand ready for His message; stand open to His counsel,
and be willing to bear the ark, though you stand in Jordan.
I am persuaded my God has designs for you to bring glory to His name,
though you may think He deals hardly with you at times, and may reason thus,
"`are there any so poor, so weak and feeble as I am?--perplexed,
buffeted and set at naught, the butt of the elder rank to shoot at,
if I am concerned to speak but a little for my Master`'s cause,
and the ridicule of the libertine!`"
Ah! nearly united fellow-sufferer;--so was our Pattern and Captain before us;
He was censured by the high professing scribes and pharisees,
ridiculed by the libertines and by those unsubjected to his laws;
and so were his servants that immediately followed him.
Well, then, let us not murmur at our probations or tribulations, but rather count it joy,
that we are worthy to suffer for His name;
for it is such that are to be partakers with Him in a glorious immortality.

[.signed-section-signature]
Samuel Neale.

--

[.offset]
+++[+++It appears that Samuel Neale was in the practice, from about this period,
of recording his religious experiences and daily engagements in a diary,
which he kept up to the year before his death.
Respecting this practice he observes.]

The remarks thus penned in passing along are, and have been, instructive to my own state.
The impressions made under Divine influence are certainly highly beneficial and lasting,
if we keep as we ought, in humility and fear.

1755, Third month 2nd.--First-day, at our meeting;
where I had a close travail and exercise to keep that watch
and guard which is truly incumbent on real worshippers;
and as this was my concern,
I experienced a degree of holy help and succour in the midst of barrenness and dryness.
Oh! how trying it is to a soul that loves, to feel the pain of absence,
to be left as in the desert or wilderness,--to a soul that has
tasted of the enjoyment and incomes of immortal food,
no pain so great as this; the tongues of men cannot set it forth:
and yet persuaded I am it is good for us; it points out our own insufficiency,
and the sufficiency of faith in Christ, which removes mountains, waters the desert,
and supplies the thirsty soul!
May my soul centre here,--may this be my refuge in the day of proving,
--may this be my covert in the day of desolation and calamity,
which shall come upon all souls to try them here on earth!

8th.--Attended our province six weeks`' meeting, at Mountrath,
in which there was a degree of quickened ability to wait and worship,
and to speak for the Lord my God.
10th, Returned home, and retired from outward concerns,
to have my mind freed from every thing that might
hinder from being prepared to follow my Lord and Master.
11th, Retired this day with some of my family, to wait upon our God;
in which state of retirement there was a renewal of inward love,
and a revival of spirit to adore that Hand which
furnishes us with His mercies and blessings.
26th, A portion of this day dedicated to retirement and reading; I felt inward poverty,
and a sense of my inability to approach the place of rest in my own time and will;
and that, notwithstanding past favours extended,
I must come down and lie low to receive whatever divine Goodness is pleased to appoint.

Fourth month 19th and 20th.--Attended the quarterly meeting at Mountmellick.
The meetings were conducted, I hope, in a good degree in the wisdom of Truth;
many testimonies were borne tending to incite and encourage
all to dwell under the government of the Prince of Peace,
which is to be manifested by keeping His laws and statutes,
and doing whatsoever He commands.
It was a satisfactory strengthening meeting.
I returned home in the evening in peace, thankful for being there,
especially in being favoured with my holy Master`'s regard.

I set forward for Dublin to our National meeting,
which was held the 30th of fourth month, and continued till the 4th of fifth month;
wherein was felt a good degree of the Spirit and aid of our holy Leader.
The affairs that came before us were calmly treated on, and some things agreed to,
still more strengthening, in order to build up in the most holy faith.
O! that all the watchmen on the walls of Zion may yet be more humble and attentive;
that every device and encroachment of the enemy may be distinguished and detected,
that her inhabitants may learn that holy warfare,
which centres the soul in the kingdom of rest and peace.

On the 17th of seventh month, I set off from home to visit Ulster Province,
and accompany John Storer from Nottingham,
on his religious visit to Friends of this nation.
After having visited the meetings in the Province of Ulster,
I returned home and found my family and affairs well,
for which I have renewed cause to be thankful;
and though it was a proving low season to me in my journey,
yet I may say I witnessed the evidence of peace to my soul many times,
and on my return home in particular.

The 3rd of tenth month attended our quarterly meeting at Mountmellick,
which was held in religious awe, and Truth was exalted over all;
forever blessed be the name of our God, who is gracious to his humble,
bowed-down children who fear Him with a holy fear,
and wait upon and worship Him in awfulness of soul; for He is surely the strength, power,
stability, and ability of all ages;--forever blessed be His government.
Amen.

17th.--Was at sixth-day`'s meeting at Dublin,
where was solemnized the marriage of my dear friends
Richard Shackleton and Elizabeth Carleton.
My mind was comforted under a sense that the love of God was towards them and their union.
I spent the evening with them in religious retirement,
wherein we had diffused amongst us of the sap and virtue of the tree of life,
which humbled our spirits and created fervent supplication,
that our affections might be quickened to serve our God with renewed devotion of heart;
that we might wear the helmet of faith and love,
and have for a breastplate the sure hope of salvation;
it was indeed a season of heavenly regard!

Eleventh month 2nd.--Was at Dublin to attend our National half-year`'s meeting.
On the first day Truth triumphed over all opposition,
and a testimony went freely forth in the authority of its working,
which created thankfulness in my soul,
to the Lord my God for his excellent condescension,
in thus favouring his little handful in their waiting and coming together;
which caused a secret assent in my heart to the Psalmist`'s words,
"`How excellent is your loving-kindness, O! Lord,
therefore the children of men (as they come to know it,)
will put their trust under the shadow of your wings.`"

3rd and 4th.--The affairs that came before the
meeting were comfortably and wisely spoken to,
and living counsel imparted therein.
It is my earnest desire that the many exhortations given forth,
may have the desired effect, and tend to build us up in the most holy faith.
At our parting meeting, we had to acknowledge that the Lord,
who was pleased in his excellent wisdom to cause these meetings to be established,
had condescended to favour them with His heavenly presence,
and to diffuse of His holy anointing,
whereby the hearts of a remnant were made to rejoice,
and ascribe the glory of all to Him through the eternal Spirit of his dear Son our Lord;
worthy is He of dominion and praise, world without end.
Amen.

1756, First month 29th.--At our week-day meeting,
I felt the quickening influence of love and goodness,
and was shown somewhat of the beauty of the new creation in the soul,
and the difference between the new and old;
the latter as we live in it being under the curse,
but the new quickens and gives life to the soul,
which is enjoyed in and through faith in Christ Jesus our Lord;
this enables us to fulfil His requirings, feel His presence,
and walk in humility before Him.

Second month 19th.--Fifth-day; had a good comfortable meeting,
wherein was opened the necessity we had to read much, and study hard,
which was an inward reading of ourselves; and in doing so,
that we should first come to witness an emptiness in our minds,
and the heart to be cleansed,
in order that we may discern the handwriting in characters
fully manifesting they were written by the finger of the Lord;
for says the holy apostle, "`that which may be known of God is made manifest within.`"
Here is a reading truly profitable, and of the highest advantage to the soul.

25th.--I was at our week-day meeting at Rathangan,
and there witnessed a measure of brokenness of spirit,
which is always matter of comfort to my mind.
I had to see the difference between a true and living faith,
and a faith brought forth by our own conceptions,
that would flatter us with hopes of happiness,
and yet not lead the right road to obtain it; being a pleader for liberty of the flesh,
a counsellor for indulgence and ease,
it is also ready to give absolution for a conduct not squared by gospel authority.
But the true and living faith purifies the heart by love,
is the substance of things hoped for, and the evidence of things not seen;
it produces works as well as fruits,
and gives us the victory over the flesh and fleshly infirmities.
I had to express my desire for growth herein,
and that by it we might overcome and have the victory.
The meeting ended in earnest supplication,
that the Lord our God would be pleased to preserve his heritage the world over,
and sustain them by the influences of his excellent Spirit,
raise up of the young and rising generation, who may be zealous for His name;
and give wisdom to the king and council to administer justice and judgment,
that so they may not be found promoters but preventers
of every thing leading to unrighteousness.

Tenth month 7th.--At our week-day meeting at Rathangan.
Had to see what a near connection there is between Christ and his church,
by the influences of his own power and Spirit,
which unseals discoveries tending to perfect His church and people.
He is the head of his church, as says the holy apostle,
and I had to see that He is the heart of it also;
from which issues the blood of life that circulates and
keeps alive the members who witness this circulation;
but where there is a stoppage,
it hinders and cramps the activity and service which the
lively members have in their own stations or spheres.

Wherefore I exhorted to diligence and watchfulness,
that there might be a joint union and fellowship by the circulation of the blood of life;
for this is the blood of sprinkling that purges the conscience, and cleanses the heart,
and speaks better things than that of Abel.
I spoke comparatively respecting the members of a natural body;
when the blood circulates in each particular member and part,
it is a token of soundness and healthiness;
but when any part is attacked with numbness or insensibility,
it creates pain to the sound part;
as when a person is seized with a shock of the palsy in one side,
it is a great incumbrance to the well and sound part;
so likewise respecting the members of the church of Christ,
who are benumbed and insensible, they are as stoppages and lets, as well as burdens,
to the living.
Therefore I entreated all to be diligent and careful to know Christ our Lord,
not only to be the head, but heart also,
and to feel the circulation of his heavenly life
which sprinkles and purifies the conscience.

Having felt a draught, for some time, to attend the ensuing yearly meeting in London,
and also to visit Scotland, I took shipping for Parkgate, the 26th of fifth month,
and landed on the 28th. The next day went to Warrington,
and lodged at Samuel Fothergill`'s. From there proceeded to London.
After attending the yearly meeting,
I stayed in and about London till the 23rd of seventh month, visiting the meetings:
on which day, being at Gracechurch-street meeting,
I experienced the renewings of inward life and peace,
as a reward for my labours and exercises in that city;
and I had cause to be humbled in mind,
and to return thanksgiving and praise to the Author of every blessing,--indeed,
worthy is He forever and evermore.
Amen.

[.embedded-content-document.letter]
--

[.letter-heading]
To Richard and Elizabeth Shackleton

[.signed-section-context-open]
Kendal, 11th of Eighth month, 1756.

[.salutation]
Dear friends,

As I was travelling up towards London,
I found a weighty thoughtfulness to rest on my mind respecting that city,
and an apprehension I should not get directly from it after the meetings were over;
which settled upon me, and engaged my stay there for many weeks,
travailing and labouring in the ability received, which produced reconciling peace;
though at times I was introduced into much distress and pain
of mind on account of some that were in high places,
who were actuated by a wrong spirit,
which the apostle terms "`spiritual wickedness in high places.`"
But with reverence I ought to speak it and bear it in remembrance,
I was enabled to discharge myself,
and lay at the doors of the people what was given me for them.
I was at many of their meetings for discipline,
and beheld with anxiety the order of the London churches,
and what Diotrephesian spirits ruled therein; which when removed,
I hope Truth will more gloriously shine there;
for there are many under the forming hand for places in the house, even there,
with whom I was nearly united, and which in due season will be made manifest,
I left that city in much peace and gratitude of mind for my deliverance therefrom,
and that I was preserved so as to have the unity and
approbation of the solid and rightly concerned,
and the enjoyment of comfort and peace in my own soul.

I came from London pretty direct by way of Northampton, Leicester, Nottingham, Mansfield,
Doncaster, and York, and left the latter place this day week,
after staying several meetings there, for Skipton; from there to Settle,
and so to Lancaster, where I was last first-day much to my refreshment and satisfaction,
and came here on second-day accompanied by many Friends, William Dilworth,
Jonathan Bradford, and wife and daughter; there was also Lydia Lancaster,
that worthy mother in Israel, and one of the Rawlinsons, William Birkbeck and sister,
who came from Settle, and several more.
We were at a large meeting here yesterday, which was a general meeting,
and proved to our mutual comfort;
and indeed I have daily cause to bow in mind under a sense of the goodness of my God,
who, though He tries,
does not forsake those who feelingly rely and trust in His ever-gracious hand of help.
And though I have no settled outward companion, He is pleased to attend,
and to make up all deficiencies of that sort, forever magnified be His name;
He is worthy of all praise through the utterance of his own Spirit and power,
both now and forever, world without end!

I intend now, through Divine aid, to go from this place pretty direct into Scotland.

Give my dear love to Mary Peisley,
and inform her I rejoiced at her and the Friends`' safe arrival,
and that they were preserved to taste of that victory which
true faith gives over the worst and greatest enemies,
whether by sea or land, amongst countrymen or false brethren,
and which completely overcomes the united force and terror of death, hell, and the grave,
and centres the soul immortal in immortal life.

[.signed-section-signature]
Samuel Neale.

--

I had many meetings on my way to Edinburgh,
which place I reached the 22nd of eighth month, and was at two meetings there,
it being first-day; many of other religious persuasions came in,
who though light in their behaviour at first, became very solid.
The meeting ended to more contentment than I expected,
considering the wide and distant walking of some from the principles they profess.
On the 25th, we went forward to Robert Barclay`'s at Urie, grandson of the Apologist,
an instrument memorable in his day, and who being dead, yet speaks.
On the 26th of eighth month, I had a meeting at Urie,
and though it was my lot to suffer much,
yet the Lord my God was pleased to favour me with his divine and heavenly aid,
and to bear up my head, and to support my spirit,
so as to clear myself of what seemed to be my place to deliver,
which was very close and sharp;--for the apostacy is glaring in this part of the world;
there is so much of a joining with the spirit of it,
and cleaving to it both in speech and apparel,
which species of adultery the Almighty is displeased with,
and He furnishes his servants with a testimony against it.
That evening we proceeded to Aberdeen, and from there to Kingswells,
where Gilbert Jaffray lives.
On the 29th, we came to Inverary, being a general six weeks meeting,
where was the largest body of Friends we saw in Scotland;
and a solid good meeting we had, both at noon and afternoon,
which occasioned great satisfaction to us.
Went in the evening to Old Meldrum, and lodged at John Emslie`'s,
and had a meeting there next day, being the 30th, which was open and comfortable;
this was the furthest meeting north,
and there seems to be belonging to it a sensible body of those
concerned at heart for the growth and increase of the Truth.

We returned to Aberdeen,
and were at their week-day meetings both fourth-day and seventh-day,
likewise had two large meetings there on first-day, fifth of ninth month,
much to my satisfaction.
I had to press those of our profession to be circumspect,
and to remember our high and holy calling, to live a self-denying life,
and be as lights to others.
We parted in much love and tenderness, and came that evening to Stonehaven,
and had a meeting there next morning, after which we set forward for Montrose, Perth,
and Glasgow, where we had two meetings.

At Glasgow, my companion Thomas Crewdson, and I parted;
he returned home by way of Carlisle.
On the 13th of ninth month, I set forward for Port-patrick, where I arrived the 15th;
and next day landed at Donaghadee.
The 19th, was at the quarterly meeting held near Ballinderry;
here I met my dear friends S. H. and S. W.,
with whom I partook in gospel fellowship of the fruit of the tree of life,
and was refreshed in a holy and sweet communion.
We were favoured together,
and the meeting ended in thanksgiving and praises to Him who lives forever,
who prepares them Himself,
and teaches how and when to offer them up to His holy and glorious name.

The 28th of ninth month, 1756, after having visited several meetings in Ulster province,
I returned home, and found my family and affairs well; for which,
and all other blessings and mercies,
may living praises and adoration be ascribed to the inexhaustible Source of all good.
Amen.
