== Chapter VII.

[.chapter-synopsis]
* Visits parts of England and Wales.

+++[+++Soon after his second marriage, Samuel Neale settled in Cork;
and having for some time had a prospect of visiting some parts of England and Wales,
he previously obtained the concurrence of his friends, and left home in the ninth month,
1760.
He visited the meetings of Friends generally, in South Wales, the city of Bristol,
and the West of England, and returned home in the second month, 1761.
Of which journey he writes thus:]

[.small-break]
'''

"`In this visit the Lord was pleased notably to bless with his presence,
support with his power, and refresh with his heavenly goodness;
for which he is worthy to have the praise of all ascribed to him,
who lives Omnipotent and Omnipresent, forever and ever.
Amen.`"

1761, Fourth month 4th.--This day was at the quarterly meeting of ministers at Cork,
in which I had something close to offer to ministers and elders,
and to inform them of the necessity there was to keep our
vineyards clean before we took the oversight of others.

5th.--First-day of the week, the meeting was very large,
several Friends attended from other meetings.
I felt a pretty strong testimony to rest on my mind,
which through the ability received I dropped, and it seemed to have a place.
Several encouraging hints were uttered to excite
to a steady perseverance and keeping covenant,
as the Lord keeps his covenant with his people; it was to me a satisfactory season.
In the afternoon I was likewise concerned, which seemed to have a place,
and to be in a degree of the authority of Truth,
without which I find I cannot get forward; no art or skill of the creature will do,
except aided by the ability that the Lord is pleased to give.

Twelfth month 6th.--This night was awakened out of my sleep in so remarkable a manner,
as to make me apprehend that something trying was to succeed.
On the 7th, as I sat in meeting, I had some prospects, though at a distance,
that dipped me exceedingly, and bowed my spirit.

1762, Second month 20th.--My mind for some time back has been poor, barren, and empty,
our assemblies mostly appearing as a field of exercising conflict,
which increases apprehension of danger and a swerving from a
proper attention to the operation of the good Spirit within;
but at times a desire arises for preservation and protection in this day of conflict,
and that everything shooting from the tree of nature and of self may be cut off,
burnt up, and the garden of the heart kept clean.

Sixth month 5th.--This day about temporal affairs; had some friends at dinner,
and in the evening was low in mind,
but mercifully felt that which turns the eye to look towards sure Help,
and makes the ear attentive to listen to the utterance of the voice of instruction.

Seventh month 12th.--Our province meeting at Youghall,
in which divine favour was extended,
and both the meeting for worship and that for discipline ended satisfactorily.
There was a visit appointed to be performed to the families of Friends,
in which my name was entered; and to forward the work I was unwilling to refuse;
the same evening we proceeded on it, joined by Joseph Oxley from England.
We laboured according to ability received,
and returned home in a degree of sustaining peace.

20th.--Our week-day meeting, in which J. Oxley was pertinently concerned;
I dined with him,
and felt an attracting draft of uniting love to draw me to accompany him to Limerick,
which I gave up to, and we set out accordingly the next day;
after attending their week-day and first-day meetings there,
I took an affectionate leave of my worthy friend J. Oxley,
who seems an agreeable sweet-spirited Friend, and returned home on the 26th.

Eighth month 3rd.--Some instructive openings at
meeting respecting working while it is day,
and being the Lord`'s workmen, moving in his service.
After meeting heard of a proposition of Samuel
Fothergill`'s respecting a visit to this nation,
to the quarterly and monthly meetings, to move in it the beginning of next month.
I felt some exercise about it and unity with it, with some searching of heart.

9th.--Our men`'s meeting, which was poor and inwardly low;
the business went on in a dry barren way,
barren conversation and prudential striving to evade what
might be profitable though more expensive to the meeting,
in getting a schoolmaster for the instruction and education of the youth;
who seem growing fast into rawness and insensibility
with respect to the life and virtue of religion.
It is a day of trial; formality seems to thicken,
and a resting in a profession to be the religion of too, too, many!

10th.--Our week-day meeting,
where Ann Summerland had a sweet season in testimony and also supplication;
the current of life seemed to run during her ministry,
but when that ceased there was a stoppage, which affected the spirits of the travailers,
through a sluggish idle habit prevailing in meetings of worship, of depending on,
and looking too much at others.

Ninth month 22nd.--Went to Youghall,
to meet some Friends from England appointed by their yearly meeting,
on a visit to the monthly and province meetings in this nation,
and was at a meeting there the next day, which was satisfactory and reaching;
but that for discipline was searching;
the state of that meeting being much spoken to in
answering the queries of the yearly meeting in London,
of 1755.

26th.--First-day at Cork,--a day to be remembered for
the excellency and dignity that was over the meeting,
both in worship and discipline; few states but what were spoken to,
and evident it was that a heavenly visitation spread
over the assembly;--may it be humbly received!

27th.--This morning we set out for Limerick, and had a meeting at Mallow,
in the assembly room,
which tended to the information and enlightening of the judgments of the people,
and to the propagation and spreading of the knowledge of the principle of Truth,
I hope to the honour of the great Master; the people were solid and attentive.

Tenth month 26th.--We concluded the visits to the meetings,
in which the heavenly Hand was eminently made bare,
and the divine voice evidently and intelligibly extended,
to help and instruct all classes in the church and family of our God;
and I trust the sacred instruction that issued from the Fountain,
through the sanctified channels the Lord of
mercy prepared and directed towards this nation,
will be blessed;
and the impression stamped in legible characters that it was the Lord`'s work,
so as to be read of many.
And O! that it may become marvellous in our eyes; that we may arise in vigilance,
strength, and devotedness to the Lord`'s work, and live and die in his favour.
The above visit to the monthly meetings was
performed with great expedition and no time lost;
neither did a preventing hurry obstruct seemingly the service the Friends were on;
nor was a stone left unturned that might open the judgment and
inform the understandings of the people with respect to the
eight queries answered by the several monthly meetings.
We also attended the National meeting at Dublin, in the eleventh month,
which was a memorable season; the beauty, comeliness,
and excellency of Truth were evident, and over all opposite spirits, and the honour,
praise and glory of all was ascribed to the Lord God and the Lamb, that lives and reigns,
and rules forever and evermore.

Eleventh month 8th.--I left Dublin and set forward to our quarterly meeting at Waterford,
where an ample reward was administered from the Heavenly presence,
for all I had passed through in this journey,
as to bodily and spiritual trials and hardships, much to my refreshment and rejoicing;
magnified be that Hand, which helps in the day of trial!
I returned home on the 24th, where I found my dear wife and family well,
an additional bond to future faithfulness, in which I desire to be strengthened!

25th.--Pretty easy and quiet, looking back at past steppings;
feel poverty near at the door, in which state and condition,
if it is administered as my portion, I desire to be humbly resigned,
and in it to be kept awake, vigilant and watchful.

Twelfth month 3rd.--Sixth-day, our meeting-day; was easy and quiet in spirit,
in a constant travail in the meeting; towards the latter part there was light, and peace,
and the spirit of prayer and supplication overspread my mind,
and formed itself into language, though unuttered.

17th.--Our meeting-day; it was a season of coldness and exercise;
towards the latter end the sweetness of Truth operated in our minds,
and a remnant was consoled in the comfortable influence of divine love.

24th.--This day was at a comfortable good opportunity in our meeting;
the opening was respecting communing with the Great Master,
renewing our intimacy with him, wrestling for this communion,
and giving it place before every other consideration,--not losing the benefit of
this communion by holding a conversation with other intimates in a natural sense,
which as they rob the Great Master of his proper regard, become idols,
and then we are left; our Beloved withdraws himself, and retires from our inquiry.
But as we prefer Him and live to Him, He becomes our friend in storms and tempests,
and a covert from rains.

26th.--First-day; was assisted to worship in brokenness of spirit,
and to bear testimony for the Great Master, both in the fore and afternoon.

1763, First month 18th.--Was at the weekday meeting at Ross, and at their men`'s meeting;
in both of which favour flowed,
and a good degree of utterance was granted to speak with clearness;
I laboured faithfully with them and departed in peace.
It was the first time of some present sitting in meetings for discipline,
the design of instituting such meetings was spoken to,
and the authority of them was pointed out,
I hope it may rest with weight upon some there.

20th.--Returned home, found my mind pretty easy.
I pondered the wise king`'s saying,
that "`all is vanity;`" that after we have gratified
ourselves with every rational and religious enjoyment,
it is only worth living for to stand in our lot at the end of days,--
a glorious one will be the reward of our obedience and duty;
for which may the grace of our Lord Jesus acquit and strengthen us,
that our abode at last may be with the blessed and redeemed,
that death may be swallowed up of victory!

28th.--Our week-day meeting,
in which I was refreshed by the prevalence of a concern for the youth,
which I had to express;
it was respecting the parable of the merchant seeking goodly pearls, who,
when he had found one of great price, went and sold all, that he might purchase it.
Felt a desire that our youth might become young merchants,
and might seek early that which will abide with them, the kingdom of heaven first;
and then everything necessary will be added.

Second month 2nd and 3rd.--At intervals easy and
quiet in spirit;--read some fruitful experiences,
which softened my mind and brought a solemnity over it.
Eyed at times a concern that for some length of time has rested with me,
respecting a visit to the province of Ulster, which I purpose to proceed in before long,
if strength is added to my strength.
I am in some degree sensible of the weight of this concern in this low degenerate day;
but all-sufficient is that Power which I humbly hope to look to and lean on.

9th.--Left home on my visit to the province of Ulster, and on the 13th came to Ballitore;
set off from there on the 14th, accompanied by my dear friend Abraham Shackleton,
and got to +++_______+++'`s,
where the well of refreshment was felt to overflow and stream forth to much consolation;
the season to me was very encouraging and reviving, strengthening for the journey,
which I looked upon as a forerunner of exercise and probation, and so it proved,
though the cup was graciously mingled with the blessing
of spiritual support in the hour of deepest proving.
Magnified be the arm of everlasting strength, that is underneath to help,
when humblingly felt after.

21st.--Was at Ballyhagan meeting, where I laboured among them a considerable time;
methought it had no great entrance, yet my mind was in great peace and quietness.
Dined at a Friend`'s house, where we had a sweet refreshing season,
to the reaching and tendering of the youth; my companion was sweetly concerned,
which opened the door of heavenly succour among us,
to magnify and adore the Arm of eternal power,
that does all things in wisdom unfathomable.

Third month 13th.--Was at both meetings in Dublin.
In the forenoon had, from much weakness,
an increase of strength to utter what my mind was exercised with.
Warned the brethren to take heed lest there was in any of them
an evil heart of unbelief in departing from the living God;
and to beware how they put opinion for faith,
or substituted it as a standard to live under, as the flesh loved liberty.
In the evening had another opportunity,
in encouraging some of the lower classes to feel
for strength to live faithful to the Lord,
by minding the day of small discoveries.

20th.--Went to the meeting at Ballynakill,
where I had a clear strong testimony to provoke to diligence
and industry in attending meetings on week-days as well as
first-days--"`I will not give my glory to another,
nor my praise to graven images,`" was the subject.
I had to put them in mind of the disappointment to be met with by a divided affection;
for when Israel`'s heart was divided, they were found faulty,
and what they brought home was blown upon, their blessings were cursed, etc.
The meeting concluded in solemn supplication, and seemed in a weighty frame.

22nd.--Got well home, where I found my family in health,
and my dear wife well pleased to see me return.
I hope to be helped, to be thankful for being united to her,
and desire we may grow more and more one another`'s joy in the Lord.

23rd.--This day retrospecting my journey in a state of quietness, found my mind composed,
and in degree thankful for favours received;
read the Scriptures with a sweetness nourishing to the mind.

27th.--First-day;
in both meetings I felt strength to bear testimony to
the excellent principle of Truth:--"`I have meat to eat,
that you know not of; my meat is to do the will of Him that sent me,
and to finish His work,`" was the subject Many things
gradually opened in some degree of life and authority,
which gave my mind much ease.
In the evening encouraged in a fervent travail and exercise of spirit in waiting;
though barrenness and emptiness may seem to attend,
yet the patient waiter has a blessing, as says the prophet,
"`Blessed are those who wait upon Him.`"
The danger and reproach is, in allowing the mind to be carried away;
in this is the condemnation, as we consent to it.
Therefore it is our duty as well as interest to live near the stream of life,
that our souls may be replenished and made glad.

29th.--At a meeting felt the revival of an impression long since made,
with the pointings of sweet affection to a distant people.

31st.--The forenoon pretty busy, and went to Glanmire,
where I amused myself in an innocent manner in the garden.
In the evening I felt an opening, as I sat by the fire,
which at first struck me with some degree of surprise;
but it was to me very intelligible, having often looked that way;
and it was conveyed with a certainty that has never failed to carry its evidence,
I desire to be helped to try it in the right balance, and to act in the right counsel,
as peace and prosperity are the attendants; for if I know my own heart,
I would willingly rest and remain in the lot
appointed by that Wisdom which works all things;
but where a remove is pointed out, I hope to be faithful,
though it be against outward interest, and to a more laborious station;
believing that way will be made to bring it about in due season,
as a fixed trust is in that Power which makes hard things easy.

Fourth month 1st.--Our week-day meeting;
in which I felt comfort in the glimpse repeated of last evening`'s prospect;
afterwards a season of labour and exercise attended,
though vanishing towards the latter part of the meeting,
which ended in a participation of that which is life, strength and sanctification,
namely: the operation of the good Word of life.

13th.--This day in a sort of hurry and commotion of mind,
in which I endeavoured after stillness and quiet:--was at a relation`'s,
where I afterwards felt a sweet and serene quiet, with the attendance of Heavenly virtue.

17th.--Had another opening of the same prospect, with a feeling of love and light,
which dipped my mind under various considerations.
The weight of it greatly humbled and depressed my spirit,
not so much from opposition to it,
as from a dread of not being fit and qualified for such an undertaking,
if it should be required.
In the Light is safety; may my steps be so ordered as to walk therein,
that in the end I may have the crown!
May the guardian angel of preservation attend my spirit
and guard my steps through the intricacies of life,
in obedience to the Heavenly manifestations; and if this be a quickening of fruit,
may it perfectly ripen before it falls as from the tree;
that it may have a proper relish and flavour among
the sensible-palated children of the spiritual house!

Sixth month 5th.--First-day, I was at a meeting at Ballydarton,
where I had good opportunity to clear myself among Friends there; the subject was,
to keep close to the spiritual warfare, to give to the fire that which is for the fire,
to the famine that which is for the famine,
and to the sword that which is for the sword;--
touched upon the glorious gospel dispensation,
and the inward burning of the Holy Spirit to
destroy whatever opposes its rule and dominion;
"`every battle of the warrior is with confused noise, etc.,
but this shall be with burning and fuel of fire:`"--it destroys animosity, passion, etc.,
brings into the love and meekness, and teaches brethren to love in wisdom and discretion.
I had to speak on Abraham`'s disposition to Lot,
when strife happened among their domestics;--"`Let
there be no difference between me and you,
for we are brethren; do you go to the right, and I will go to the left,
or do you go to the left, and I will take the right.`"
This cordiality between them was beautiful, I therefore recommended it.
Also on Balaam`'s forwardness to go against the Lord`'s command,
by being too hasty,--the dumb ass reproved him by her duty and fidelity to him,
though of the brute creation; and even was helped to query of him,
"`did she ever offend him before, since she was his?`"--a close and clear reproof to him,
an offender, who was blinded by his infidelity and disobedience,
so as not to see the sword that was near to cut him off.
Indeed sin hardens and blinds men, sinking them below the level of the brute creation,
intoxicates them madly to trample on and forget the
laws and precepts of the Lord of the creation;
which often brings them as upon the point of the sword of destruction.
Several other things I had to speak to, which opened with sweetness,
strength and satisfaction to my own mind.

13th.--This day quiet and easy, read the Scriptures in the forepart and evening,
though I was disturbed by some disagreeable cross occurrences in the way of trade;
but I find that fleeing to the Centre gives life and
strength to stand in calmness over disappointment.

Seventh month 29th.--Our week-day meeting;
it proved a constant low travail through the whole,
and indeed most of our meetings are so; heaviness and death seem to overshadow,
from which may the Lord in His time deliver us.
We had a neighbouring family to dine us, which occasioned some hurry with us,
but I hope no loss was sustained through any lack of
circumspection and attention to the sure Guide.
I have often observed such visits turn to little profit,
therefore I am in a state of fear when we have such.
It is a fine thing to live with the Light, and so reflect it on others;
may a holy growth in this concern be witnessed!

Eighth month 1st.--Our men`'s meeting was held this day; it was low in life and virtue,
things went forward in a formal dry channel, little or no contention or opposition;
but the spring being dammed up,
the water of life had but a very weak and shallow current,--very hard
therefore for business to go forward in the right line and authority!

7th.--First-day, at Limerick meeting; I had a season of deep exercise and labour,
a low travail accompanied my mind a great part of the meeting;
at last I felt the operation of the Word of life,
which strengthened me to stand upon my feet; and as things opened, I dropped them,
and life and strength increased by little and little,
until my mind was filled with authority in the Power.
"`Be careful for nothing, but in everything by prayer and supplication,
with thanksgiving,
let your requests be made known unto God,`" "`that the abundant grace may,
through the thanksgiving of many,
redound to the glory of God:`"--exhorting to a humble waiting for the Power,
to be made capable to pray, and to pray as the Spirit directs and intercedes;
for we know not how to pray as we ought,
but as the spirit directs and makes intercession.
In this state of waiting is true worship performed,
and the more we practise it the more we delight in it;
the less we practise it the more indifferent we become, our minds become darkened,
clouded, and uneasy, the meeting is tiresome,
we become negligent about attending to the hour
appointed and long for it being broken up.
Hence profession and opinion are substituted instead of religion and faith,
and the outside show is kept up by some on a first-day,
who think it a shame to stay at home, at least on first-day forenoon;
taking hold as on the skirt of profession,
saying we will eat our own bread and wear our own apparel,
only let us be called by the name, to take away reproach.
Thus formality and profession stand in the place where
reality and substance ought to live and preside.

Ninth month 27th.--At a meeting felt the sacred virtue
of the holy Jesus to stir and bedew the mind;
in which several renewed gospel intimations were opened to the view,
and reverence and worship formed in the heart; to the praise of Him that lives forever.
In the afternoon read a portion of the Scriptures and some
profitable experiences in John Fothergill`'s journal.

Tenth month 4th.--Our week-day meeting;
in which something weighty attended my mind respecting inquisition being made for blood,
and as if blood would be required at the hand of some, who were deficient in their duty.
That language uttered of old, sounded in my heart,
"`The voice of your brother`'s blood cries unto me from the
ground:`"--there was something awful in the consideration,
but it was not to be uttered; and the meeting ended in a degree of solemn quietude,
in which was a bowing of the mind before Him who lives forever.
Afterwards I was at the adjournment of our meeting for business;
in the afternoon had a select sitting with our elders,
where freedom was used one with another,
in imparting counsel and exciting to diligence in being exemplary,
and to lead the family under our care in coming forward in their respective
particulars in a religious inquiry and attention to their Christian duty.

16th.--First-day, felt my mind engaged under a sense of the prevalence of gospel virtue,
to bear testimony to the Spirit of Truth,
that had mercifully operated on my mind to turn it from the evil of my ways,
when in folly and vanity, and the pernicious courses of unbridled youth.
I felt my mind supported by faith that works by love,
bearing me over opposition of spirit; and I had to put all in mind of their covenants,
and that as the Lord kept covenant with His people, He would expect it from them.
My mind was sweetly sustained and refreshed;
and the meeting ended in supplication to the Lord of mercy for preservation, deliverance,
and support.

18th.--Our week-day meeting; through the whole, almost, intelligence seemed unsealed,
but not in such a proportion of strength as gave ability to utter it;
it was a profitable season to my own state,
and ended in quietness and stillness of spirit.
Afterwards I was busy about temporal occasions; dined abroad,
and found an approach to a liberty of spirit that I fear dwells near danger.
In the evening preparing for my journey to Leinster quarterly meeting.

22nd.--At Mountrath; the quarterly meeting for worship preceded that for discipline,
in both of which the revelation of hidden treasure in Christ Jesus our Lord,
was made manifest.
Truth supported our minds,
and a remnant bowed in awe before that Holy Throne of strength,
which ministers strength to the humble seekers,
who are weak and have no might of their own.

Eleventh month 13th.--First-day, at Dublin,
where I had gone to attend our National meeting.
We had a meeting to be commemorated; plain gospel truths were revived in authority,
which being manifest, the spirits of some topping folks were, I believe,
brought down and humbled.
Ancient Goodness was pleased to extend one call more,
which I humbly hope will be attended to, and received in mercy.
A meeting of conference succeeded that of worship;
when the negligent and forgetful were pressed home to
their duties in the moving language of love.
In the afternoon meeting we had another renewal of the same goodness and favour extended.
It lived in my mind to put them in remembrance
of the goodness of God extended to this day,
to us as a people;-- that we have been pruned, watered,
and dug about from one year to another, waiting for fruit to appear;
and if we remain still fruitless, I feared the language would be uttered, "`Cut it down,
why does it cumber the ground?`"
I heard it intelligibly in this meeting;
and though some may think their lofty branches may have much fruit on them,
and towering up as to heaven; yet if it be the fruit of exaltation, imagination,
and speculation, the Watcher and Holy One may be sent to cut it down.
I had to encourage the lower order of the people
to stand fast in that which had visited them,
and they would be brought up as plants of the Lord`'s right-hand
planting,--they would be brought up in succession as useful,
serviceable members in the Society and Church.

Twelfth month 2nd.--Our week-day meeting was a quiet refreshing season;
towards the latter part, life opened strong in my mind,
and quickened ability to drop a few words by way of encouragement, diligently,
distinctly, and intently to feel for the resurrection of life,
which enables us to believe in the spiritual
appearance of our Lord and Saviour Jesus Christ,
who testified that "`Whosoever lives and believes in me shall never die!`"
