== Chapter X.

[.chapter-synopsis]
* Attends yearly meeting at Philadelphia 1771
* Meetings in Nantucket
* New England
* New York
* Returns to Philadelphia 1772
* Sails for Ireland
* Arrives at Waterford.

The yearly meeting of Philadelphia commenced the 21st of the
ninth month with the meeting of ministers and elders,
in which Truth was felt to sweeten our spirits,
under the influence whereof we were enabled to worship.
My mind got a little ease in reviving the language,
"`Look to the rock from which you were hewn,`" etc.,
and had to show the insensibility we were in,
before we were visited by the Power of Truth; and the necessity we are under,
of being renewedly quickened and raised from the deadness of the letter,
to live in the Spirit unto the Lord our God;
We were favoured during the various sittings of this
yearly meeting with the renewings of heavenly help,
for the carrying on the affairs of the Church in unity, concord,
and sweetness of gospel labour.
They proved satisfactory informing seasons,
in which Friends were opened to unfold much instruction during
deliberations upon the various matters that came before us,
the seasoning of Truth being kept to,
wherein instruction is communicated to comfort and edification;
I hope it will operate like leaven among the members.
The last day, (the 26th) was especially a season of heavenly favour;
so that some of us could say in truth, our meeting for business was a meeting of worship.
The solid power and life of Truth was sweetly felt in the closing meeting;
and we came away thankful and humble under a sense of Divine favor,
and that the Lord our God was revealed unto us;
for which my soul adored His great and glorious Name;
and I could say through living experience,
that salvation and strength belong unto the Lord and to his Christ, forever and ever.
Amen.

Tenth month 6th.--We had a large meeting at Peach-pond, where were many Presbyterians.
The people were well-behaved,
and the way of life and salvation was freely preached to them;
when the meeting was over they seemed even reluctant to depart.
We may say, the Lord`'s blessed power was over all, and His great name was praised.

11th.--Set forward for Oswego meeting; it was mostly held in silence,
except towards the latter part,
where I had some close hints to drop to those who minister to the
people,--to remember not to sacrifice before the prophet came,
because it was foolishness, and would not go unpunished as in the case of Saul,
who did it out of pity to the people.

19th.--In passing through Worcester we had conversation
with a physician and a man of note in trade;
they were both very civil,
and seemed convinced in their judgments of the
spiritual religion established by our blessed Saviour;
they kindly invited us to stay and dine.
Several seemed to importune us to have a meeting in this town;
but not feeling that draft which sustains in such services, I declined,
being fearful to dishonour the Master`'s cause,
or to bring reproach upon the reputation of the blessed Truth;
being convinced it is more profitable to be drawn by the cords of Divine love,
than to run hastily into services which we are not
authorized to engage in by the leadings of that love,
which desires the prosperity of mankind,
and as it is obeyed gives us the enjoyment of Divine peace,
and leads to quietness and assurance forever.

Eleventh month 6th.--Had an afternoon meeting at Ippin; several Friends were present,
and many other people also assembled, it was a good open opportunity;
afterwards we had an evening meeting in a Friend`'s family,
which was like a parting meeting to some who were with us for many days.
The sweet influences of the love of our God were with us, in which I had to say,
Who is like unto our Rock?
and that as we have our settlement in Him, though distantly scattered,
we shall be all preserved and enabled to sing unto Him; this Rock follows us,
as it did Israel of old, in order that we may eat of it and drink of it,
and be sheltered by it from storms and from rains.
This was the same Rock that was seen to be hewn as out of the mountain without hands,
which grew and filled the earth--breaking to pieces the gold, the silver, the brass,
the iron and clay--the clay figures out the miry things of this world,
which seem to hinder our minds from going forward in the Lord`'s work,--and the gold,
silver, brass and iron, the world`'s glory and honour,
which so much captivate and fill the minds of men.
But as we know the power of this Rock to break and destroy those things,
and way is given thereto, it grows in us, and then we become inhabitants thereof,
and sing to the praise of His great name!

14th.--Attended the monthly meeting at Salem, +++[+++Massachusetts]
where I was favoured with a relieving though
close testimony to the Friends belonging to it,
who appeared to me to be much at ease and leavened into the spirit of liberty and vanity,
with which this age of professors of the pure Truth too much abounds.
The meeting of business was low and flat, we had many remarks to make,
which they accepted in love, and we departed in peace.
We lodged at Samuel Collins`'s,
at whose father`'s or grandfather`'s John Richardson and
George Keith formerly had a close argument,
when the latter was much confused and confounded.

15th.--I was at a large meeting of plain looking Friends,
in which I had very close work to get into my service in the life and opening of counsel.
I had to mention the sea-monsters that drew out their breast to their young;
but now when the children asked for bread, no man breaks it unto them,
and the tongue of the sucking child cleaves to the roof of its mouth for thirst;
the daughter of my people (says the Lord`'s servant,) is
become cruel like the ostrich in the wilderness,
to which I had to compare this people.
I was helped forward in a good degree of authority and strength,
and found my mind opened and relieved by the prevalence of Divine virtue.

26th and 28th.--I was at two large meetings for worship on the island of Nantucket.
There are on this island 300 families of professing Friends
many of whom are sailors employed in the whale-fishery.
I felt my mind sustained by the unction that qualifies for every service in the church,
and had many states to speak to;
afterwards I was at the men`'s meetings in which I laboured a pretty
deal with respect to several things that appeared on their books.
I was enabled to be helpful to the concerned Friends,
by joining in their service for the support of the discipline;
the distempers appeared to be great, which had crept in among the professors,
by much indulgence,--cases with respect to offenders in marrying, and other things,
which a remnant were labouring to have reformed;
there seemed to be some gaining of strength in the latter,
which in time I trust will so far increase, as to make them firm stakes in Zion,
bearing their spiritual armour under the glorious banner of Christ Jesus,
who is the Captain of the armies of the living God.
In the evening I had a sitting with pretty many Friends at our lodgings to my
relief and the encouragement of several present in the way they should walk,
even by being faithful to the manifestation of Truth;
and then the Lord would delight in them and fight their battles for them,
and bring them into the peaceable possession of Divine enjoyment in the spiritual Canaan.
I had a concern to see those who were sea-faring men,
and on the 29th they came together pretty fully, and there was a large gathering,
in which I laboured to the best of my ability.
The result must be left to Him who blesses and sends
home all such services to the witness within.

Twelfth month 21st.--First-day, I was at a very large meeting,
said to be the largest at Friends`' meeting-house, supposed to contain 2000 people;
in the forepart I felt in a very low travail of spirit, and resigned to be like a fool;
with which I seemed to settle; when I felt the gradual springing up of Divine strength,
in which I stood, and was sustained beyond my expectation.
The openings of counsel flowed greatly to my own relief and enlargement,
as I felt very poor and weak on going to this meeting.
Supplication was offered at the close in the power and spirit of our Lord Jesus,
and it ended greatly to my inward enjoyment of peace and consolation.

5th.--Finding our minds easy, +++[+++David Ferris was his companion,]
we set sail for the main land.
When I came on this island,
I felt the love of our Lord Jesus Christ to operate in my heart towards this people,
even before I left the wharf, which deeply affected my mind; and while with them,
I was sustained in a gospel labour beyond my expectation; and now on leaving them,
I found my mind sustained with the same love,
in which I desire their growth in the Truth and increase in righteousness,
and that the Lord our God may have a valiant people raised up for His name,
whose works through them may praise Him, who lives forever and ever!

11th.--This day I had a tender sitting with a Friend.
I had to speak of those chosen separated vessels for the Lord`'s use,
which as they are passive and resigned, a blessing awaits them and theirs;
they are as channels through which counsel flows,
and it is a favour and honour to be counted worthy to act in the Lord`'s cause.
Thus as the ark when with Obededom, was the cause of his being blessed,
so as we keep our places, a blessing will rest upon us and our families,
when employed in the Lord`'s service.

16th.--Was at the monthly meeting at Ponyganset,
in which I was favoured with some degree of ability to labour.
The meeting for business was attended by several solid concerned Friends,
who seemed engaged for the law and testimony of our holy Head and High Priest.
We laboured together with them,--spoke to several affairs that
came before the meeting according to present strength,
and came away relieved in our minds.
The decay of a right concern, or rather the lack thereof, has greatly retarded,
in these parts, the prosperity and growth of the Truth among the people,
by which wrong things have got into the camp, wrong habits have been indulged in,
and the children`'s teeth seemed set on edge by the parents eating sour grapes.
Heads of families being destitute of the right knowledge,
are incapable to instruct their children,
and so all seemed too much in the way of forgetfulness
by the indulging in present perishing gratifications.
May the Lord arise and scatter his enemies and the people`'s, is my earnest desire,
and then the Church will be qualified to come out of her
present wilderness state in this quarter of the country;
where the gates of Zion mourn,
because so few come forward in a noble concern for Truth and righteousness.

[.offset]
+++[+++After visiting the meetings in the New England States and in New York,
he returned to Philadelphia the 13th of second month, 1772,
to the house of his kind friend John Pemberton.]

1772, Second month 14th.--Took leave of my companion David Ferris,
who went home to his family; he was with me in this journey oftentimes in cold weather,
close exercise, and hard travelling; and his company was helpful as well as agreeable,
he being a lover of Truth and its testimony.

20th.--At Radnor meeting, which was in a good degree lively,
being favoured with the running of the heavenly oil,
which was truly comforting to my mind.
Having been much stripped as to spiritual enjoyment, and under baptism for many days,
though resigned.
The evening of the 21st, some Friends were at my lodging,
with whom I had a silent sitting, in a communion truly delightful,
which I thought a reward for what I had passed through this week.

23rd.--I was at Pine-street meeting +++[+++Philadelphia]
in the morning,
in which I felt a concern on my mind to labour in doctrine according to present ability;
the words that impressed my mind were,--that we must
become followers before we are feeders of the flock;
and I had to point out how we are prepared for the service of
the Church,--the tribulation that is to be passed through,
which works patience, experience and hope; thus preparing us for the spiritual work,
and breaking us off from the spirit of the world, through the baptism of the Holy Spirit,
which removes the dross, the tin and the reprobate silver.
It was a season of favour, and the testimony reached several states present,
and brought us near in the heavenly communion.
Went afterwards to Burlington,
and in the evening had a sitting at Benjamin Swett`'s to profit and enlargement of heart.

24th.--Attended the meeting for worship and discipline there;
in the former I was exercised but did not express all that was before me,
which lessened the reward of sweetness and peace which would have attended,
but I got some ease of mind.
My concern was to the elders and other members,
who were concerned and active in the Lord`'s work,
that they might feel their qualifications in the
moving of the Holy Spirit upon their minds.
As prophecy came not in old time by the will of man,
but holy men spoke as they were moved of the Holy Spirit;
so this remains still to be the true qualification for service in the Church,
among all the concerned members of different ranks and orders.

Third month 1st.--I went to Frankford meeting in the forenoon,
and returned to the evening meeting in the city.
I was exercised in a low travail in this meeting,
but a spring of living comfort sustained me to labour to the ease and peace of my mind;
the evening meeting was large, and through the seasoning virtue of Truth we were helped.
I sat under a living sense of Divine enjoyment,
as it were under my own vine and fig-tree, where none can deprive of a living feeding,
when it is the Heavenly Master`'s will to honour with his presence and goodness.

3rd.--I went with many Friends to Chester, to see my endeared companion, Joseph Oxley,
embark for England, with Sarah and Deborah Morris;
we had a sitting there before they went on board;
and at our lodging in the morning before we set off,
there was an effusion of love and goodness prevailed,
which united us to each other in much nearness and brokenness of spirit,
which is a mystery to the world and its spirit.
In this frame of mind we parted, the ship got under sail, and we returned to Philadelphia.

22nd.--Was at the Bank meeting in the morning,
and at the great meeting-house in the evening; in the latter I was silent,
I had an impulse to duty but waived it on account of
the smallness of the opening and the singularity of it,
which was David`'s words respecting himself,
"`As the Lord lives there is but a step between
me and death;`"--this occasioned me distress,
as I believe it was best for me to have dropped it, though I had said no more,
but the largeness of the meeting and my own diffidence made me fearful and backward,
which increased uneasiness and multiplied my burden.

Third month 23rd.--In the meeting for ministers and elders I had a sharp close testimony.
I rather kept it too long in my vessel, which disqualified from getting that relief,
and with that clearness, which was desirable.
It was respecting those who were in their chambers of imagery,
and some who turned their backs on the temple,
and were worshipping the sun towards the east.
Like Demas, they were preferring this world and its glory,
before the discharge of their duty;
and thus they had too much neglected the work unto
which they had been called in the Lord`'s vineyard, etc.

25th.--This day I was among my friends,
and visited my worthy friend Mordecai Yarnall at his son-in-law`'s, where with his family,
we had a sweet refreshing opportunity under a sense of the overshadowing of Divine love.
Spent the rest of the evening with William Brown and John Churchman.

Fourth month 4th.--Continued in Philadelphia until the 19th;
visiting the meetings and families of Friends, as Truth opened my way;
during which time I had some dipping seasons, and trying exercising moments, but,
amidst all, was mercifully sustained,
and supported to get through in a good degree of the unity of the Spirit,
which remains to be the bond that links and draws the Lord`'s
people and family together in uprightness and simplicity.
I had the company of dear Susannah Lightfoot in
many of those families in which I laboured,
whose service was acceptable and enlivening to me and many more.

19th.--Went to Chester meeting, where I had a low season in travail;
but towards the conclusion Truth seemed to be in dominion,
and the meeting ended in supplication and thanksgiving to the Lord of power and praise,
who is worthy forever!
In the evening went to John Smith`'s, where we had a sitting with many Friends,
to our mutual help and comfort.

Something close was dropped for a state present, which, like David,
was for justifying itself and yet was guilty;
the prophet having to tell him "`You are the man,`" notwithstanding his zeal in saying,
"`the man that has done this shall surely die;`" he sat as a judge,
was for punishing the iniquity of another, but was guilty himself.
I warned such a state to get to the washing pool,
for unless we are washed we have no part in Christ Jesus;
and if we die in guilt and rebellion, we shall be excluded from the territories of light,
and can have no entrance; whereas if we become washed,
we shall be able to stand in the obedience, be faithful unto death,
and so enjoy a crown of life!

22nd.--In Philadelphia, preparing for my journey to Oblong,
having felt drawings for some weeks past to be at their ensuing quarterly meeting.
It has been a sifting time;
but my mind is brought into a disposition to be what the Lord my God would have me to be,
and to follow the leadings of his blessed and unerring Spirit; for,
though human frailty is great, yet weak things are sometimes made strong,
even to confound the wise and prudent of this world.

Sixth month 6th.--Went on board a vessel bound to Cork, to feel if I could go in her,
but found a stop, which brought me into close exercise;
but as I know my motive is to be clear of this people, and to discharge my duty,
I am easy; and have resigned myself to Divine disposal.

Seventh month 31st.--At the monthly meeting in Philadelphia.
In the men`'s meeting we felt living uniting virtue;
and the business was conducted in true desire for an
increase of harmony and spiritual strength,
Many instructive hints were dropped in answering the queries.

Eighth month 1st.--The quarterly meeting for ministers and elders was held this day;
which meeting was owned with the vital power and virtue of Truth, and the body,
I believe, was edified in love.
2nd, Attended three meetings,
in all which I was helped to bear testimony for the truth of our God,
and to labour in the ability revealed;
living praise be ascribed to Him who lives forever, and who, through grace,
enables dust and ashes to stand in dominion over the opposing spirits of carnal men.

3rd.--The quarterly meeting assembled at Fourth street, and was very large;
I was exercised, much to my own ease,
both in the meeting for worship and that for discipline;
and strength was granted to drop several remarks, which much relieved my mind.
The youths`' meeting was held the next day; it was large,
and I laboured in the authority Truth gave.
It ended in praises and thanksgiving to the Lord our God.

5th.--Preparing for my return home, and visiting and taking leave of my friends.

6th.--Was at Market street meeting; it was large,
and though I went into the meeting very poor and empty,
yet possessing faith in the sufficiency of that Power, which is not of man but of God,
I was enabled to deal very closely with some there, who had chosen their own ways;
also to hand encouragement to the young and rising generation,
in a sweet stream of gospel love.
The meeting ended under a solemn sense of the Lord`'s goodness and mercy; for which,
and for every favour extended, may the humble in heart say,
"`Good is the Lord;--His works are wonderful, and His ways past finding out.`"

9th.--Was at three very large meetings, which were favoured with the Divine presence;
tongue and utterance were mercifully administered;
the blessed Lord of life strengthened my mind by the revelation of power from on high.
It was a day of favour to my soul,
and in all those meetings I was supplied and replenished far beyond my expectation;
and I had to praise the Lord for his mercies and blessings to his creature man.
Reverence and awe deeply impressed my mind,
under a sense of the Lord`'s gracious dealings to such a poor weak being as I am.

I went on board a good vessel bound for Cork, but could not see my way in her,
though in appearance, much better and more complete than another bound for Waterford,
and not likely to sail so soon.
But as my intention was to move in that which brought me from my native land,
I committed myself into the keeping of a faithful Creator,
and cast not my dependence upon outward observation, but on His eternal arm of strength,
which led me into this service,
has graciously sustained and succoured in the needful time,
and has been a present help when all outward help was
invisible;--for which favours and mercies,
may my soul bless His great and adorable name, for He is worthy to be followed, served,
feared and obeyed, world without end.

10th.--Took leave of many Friends in the tender love of God,
in a manner suited to the solemnity;
a multiplicity of words did not attend our separation,
but a living sense of the enjoyment of that life and virtue which goes beyond the grave.
I went on board the Charlotte, Richard Curtis, bound to Waterford; and,
as the time was come to part, I rejoiced in the power of an endless life,
and was quiet and composed.
I was accompanied as far as Chester by several Friends; we came to anchor in the evening.

11th.--Weighed anchor, had a pleasant day, read the Scriptures,
and was sweet and well in my mind; and thankful in soul,
for the feeling of great nearness to my well-beloved friends on this continent.

The consciousness of having endeavoured to discharge my duty,
sits exceedingly pleasant on my mind;
thanks be ascribed to Him who is the Author of ability, wisdom and strength; for to man,
as man, belongs nothing that is good; but to the Lord, only wise, dominion,
honour and praise, forever.

20th.--Sat alone, and was desirous that a heart might be given and continued,
to remember the kind dealings of a gracious God,
who wonderfully sustained me in this journey, furnished for the labour of the day,
gave me a place among the living in his family; and, at my departure,
favoured me with an incontestible evidence that I was in my place,
and had stayed the proper time and no longer; this is what I desired fervently;
also that He would be graciously pleased to restore me to my friends,
and unite us in the bond of spiritual fellowship.

21st and 22nd.--A pleasant breeze continued in our favour.
Read the Scriptures, and was pleasantly composed,
under a thankful sense of the many mercies and favours communicated to this hour.
May ability be further vouchsafed,
to be more and more sensible of the innumerable obligations I am under,
to the bounteous and inexhaustible Treasury of goodness, infinite and immense.

24th.--Spent the time very pleasantly and sweetly on my voyage, having an easy mind,
free from anxiety and gloom.

28th.--My time much taken up in reading the Scriptures and other profitable works,
which sweetened my mind; I felt myself secretly sustained,
and kept in the harbour of resignation and patience,
which I esteemed a great blessing and favour.
May the sweet influence of Divine love so operate,
as to make me more and more sensible of the benefit of
keeping under the government of our Lord Jesus,
who is King of kings, and Lord of lords,
and who crowns with immortality and eternal life.

Ninth month 5th.--A pleasant breeze in our favour.
My mind composed, under a sense of the enjoyment of that peace,
which is given to those who endeavour to perform their Master`'s will.

13th.--First-day.
It blew a fresh breeze at south-east, which brought us near Cork harbour;
but as the sea ran too high to attempt going on shore in a boat,
I contented myself with going to the designed harbour, which was Waterford;
and arrived there safely in the afternoon, after a passage of thirty-days,
from land to soundings, and thirty-four from Philadelphia to Waterford.

Very merciful were the dealings of heavenly Goodness to me in this voyage!
One thing worthy of notice is, that the vessel bound for Cork,
in which I was not easy to embark, sailed ten days sooner than we did,
and put into Waterford about three hours before us.
This instructed my mind to trust in the arm of Divine help and sufficiency,
which is revealed for all those who humbly confide therein.
Some of my friends urged the age of the Charlotte as an objection to my going in her;
but believing her to be the right vessel,
and the monthly and quarterly meetings for Philadelphia coming on, I stayed,
and resigned myself to Divine disposal, which yielded peace, and made my heart rejoice;
for, by the detention, I was able to attend those meetings, which were much favoured,
and it seemed to be a crown to my labours on that continent.
Had I gone in the other I should have missed them, been ten day longer at sea,
and should have come with only part of my reward; so that I can say,
the Lord is worthy of adoration and praise.

After attending the week-day meeting in Waterford on the 15th,
in which I felt afresh the spring of life and consolation to unite and refresh,
I came to Clonmel; and on the 16th, of ninth month I got well home,
and found my dear wife and family in health; for which, and all other mercies,
I desire to bow in grateful prostration and dedication of soul.

On the 18th, attended our week-day meeting in Cork;
through the mercy and goodness of the great Lord God,
I felt my mind prepared to unite with the spirits of my friends present,
and to reverence and worship His great Name, who lives forever.

Ninth month 22nd.--When I consider the mercy extended
to me in my distant travel in different climates,
over dangerous rivers and swamps, the spiritual support I daily experienced,
the unity of the living with my labours, and my safe return in peace to my native land;
language will not admit of my commemorating the obligation I am under.
Therefore may circumspect living express His praise; and may I, in holy awe and silence,
contemplate His matchless mercy,
for He is abundant in goodness and truth to His servants, from generation to generation,
forever and ever.
Amen.

In allusion to his labours in America,
he thus writes about this time in a letter to a friend.

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend

[.signed-section-context-open]
Glanmire, 23rd Twelfth month, 1772.

[.salutation]
Dear Friend,

I know and feel, that often for the sake of others we are favoured,
not for anything of us or in us at our command,
and therefore it is not of him that wills, or of him that runs,
but God that shows mercy; and this, beloved friend, is what sustained, supported,
and gave me a place among my friends in America,
and brought me home with a sheaf of peace, rejoicing, may it be, with fear and trembling.
For I well know that unwatchfulness, elevation, or vain glory,
may soon open a door where destruction may enter,
and may speedily cast down to hell in torment, lamentation and woe!

Therefore, I will endeavour to trust in that Arm of strength, which began the work,
carried it on and perfects it, and as there is a patient continuance in obedience,
faith and well-doing, may glory, honour,
and immortality be the crown at the end of my days;
for which end I hope I crave the help of the spirits of my dear friends everywhere,
and of their prayers.

[.signed-section-closing]
With affectionate nearness, I remain your loving friend.

[.signed-section-signature]
Samuel Neale.

--
